// 単語問題データ（頻度帯 level × テーマ theme[任意]）。
// en=英単語 / ja=和訳 / kana=和訳の読み（日本語入力用）/ freq=頻度ランク(目安) / theme=任意。
// level は freq の頻度帯（bandOf）と一致させる。
export const WORD_LEVELS = [
  { level: 1, label: '基礎', cefr: 'A1', range: '1–1,000' },
  { level: 2, label: '初級', cefr: 'A2', range: '1,001–2,000' },
  { level: 3, label: '中級', cefr: 'B1', range: '2,001–3,000' },
  { level: 4, label: '上級', cefr: 'B2–C1', range: '3,001–5,000' },
]

// 頻度ランク → レベル（頻度帯）。5,000超は最上位帯へ。
const BAND_MAX = [1000, 2000, 3000, 5000]
export function bandOf(freq) {
  for (let i = 0; i < BAND_MAX.length; i++) if (freq <= BAND_MAX[i]) return i + 1
  return WORD_LEVELS.length
}

export const WORD_THEMES = ['日常', '旅行', 'ビジネス']

// 単語モード（英語・日本語/英語/日本語=入力、英語訳/日本語訳=4択クイズ）
export const WORD_MODES = [
  { key: 'both', label: '英語・日本語' },
  { key: 'en', label: '英語' },
  { key: 'ja', label: '日本語' },
  { key: 'quiz-en', label: '英語訳' },
  { key: 'quiz-ja', label: '日本語訳' },
]

export const WORDS = [
  // ---- L1 基礎（A1） ----
  { en: 'water', ja: '水', kana: 'みず', level: 1, theme: '日常' },
  { en: 'food', ja: '食べ物', kana: 'たべもの', level: 1, theme: '日常' },
  { en: 'friend', ja: '友達', kana: 'ともだち', level: 1, theme: '日常' },
  { en: 'house', ja: '家', kana: 'いえ', level: 1, theme: '日常' },
  { en: 'book', ja: '本', kana: 'ほん', level: 1, theme: '日常' },
  { en: 'dog', ja: '犬', kana: 'いぬ', level: 1, theme: '日常' },
  { en: 'cat', ja: '猫', kana: 'ねこ', level: 1, theme: '日常' },
  { en: 'eat', ja: '食べる', kana: 'たべる', level: 1, theme: '日常' },
  { en: 'run', ja: '走る', kana: 'はしる', level: 1, theme: '日常' },
  { en: 'happy', ja: '幸せ', kana: 'しあわせ', level: 1, theme: '日常' },
  { en: 'school', ja: '学校', kana: 'がっこう', level: 1, theme: '日常' },
  { en: 'family', ja: '家族', kana: 'かぞく', level: 1, theme: '日常' },
  { en: 'bag', ja: 'かばん', kana: 'かばん', level: 1, theme: '旅行' },
  { en: 'map', ja: '地図', kana: 'ちず', level: 1, theme: '旅行' },
  { en: 'hotel', ja: 'ホテル', kana: 'ほてる', level: 1, theme: '旅行' },
  { en: 'train', ja: '電車', kana: 'でんしゃ', level: 1, theme: '旅行' },
  { en: 'car', ja: '車', kana: 'くるま', level: 1, theme: '旅行' },
  { en: 'sea', ja: '海', kana: 'うみ', level: 1, theme: '旅行' },
  { en: 'road', ja: '道', kana: 'みち', level: 1, theme: '旅行' },
  { en: 'trip', ja: '旅行', kana: 'りょこう', level: 1, theme: '旅行' },
  { en: 'fly', ja: '飛ぶ', kana: 'とぶ', level: 1, theme: '旅行' },
  { en: 'work', ja: '仕事', kana: 'しごと', level: 1, theme: 'ビジネス' },
  { en: 'time', ja: '時間', kana: 'じかん', level: 1, theme: 'ビジネス' },
  { en: 'money', ja: 'お金', kana: 'おかね', level: 1, theme: 'ビジネス' },
  { en: 'name', ja: '名前', kana: 'なまえ', level: 1, theme: 'ビジネス' },
  { en: 'phone', ja: '電話', kana: 'でんわ', level: 1, theme: 'ビジネス' },
  { en: 'help', ja: '助ける', kana: 'たすける', level: 1, theme: 'ビジネス' },
  { en: 'write', ja: '書く', kana: 'かく', level: 1, theme: 'ビジネス' },
  { en: 'meet', ja: '会う', kana: 'あう', level: 1, theme: 'ビジネス' },
  { en: 'busy', ja: '忙しい', kana: 'いそがしい', level: 1, theme: 'ビジネス' },

  // ---- L2 初級（A2） ----
  { en: 'kitchen', ja: '台所', kana: 'だいどころ', level: 2, theme: '日常' },
  { en: 'weather', ja: '天気', kana: 'てんき', level: 2, theme: '日常' },
  { en: 'kind', ja: '親切', kana: 'しんせつ', level: 2, theme: '日常' },
  { en: 'breakfast', ja: '朝食', kana: 'ちょうしょく', level: 2, theme: '日常' },
  { en: 'garden', ja: '庭', kana: 'にわ', level: 2, theme: '日常' },
  { en: 'clean', ja: '掃除する', kana: 'そうじする', level: 2, theme: '日常' },
  { en: 'decide', ja: '決める', kana: 'きめる', level: 2, theme: '日常' },
  { en: 'weekend', ja: '週末', kana: 'しゅうまつ', level: 2, theme: '日常' },
  { en: 'healthy', ja: '健康', kana: 'けんこう', level: 2, theme: '日常' },
  { en: 'expensive', ja: '高い', kana: 'たかい', level: 2, theme: '日常' },
  { en: 'borrow', ja: '借りる', kana: 'かりる', level: 2, theme: '日常' },
  { en: 'airport', ja: '空港', kana: 'くうこう', level: 2, theme: '旅行' },
  { en: 'ticket', ja: '切符', kana: 'きっぷ', level: 2, theme: '旅行' },
  { en: 'reserve', ja: '予約する', kana: 'よやくする', level: 2, theme: '旅行' },
  { en: 'station', ja: '駅', kana: 'えき', level: 2, theme: '旅行' },
  { en: 'passport', ja: '旅券', kana: 'りょけん', level: 2, theme: '旅行' },
  { en: 'luggage', ja: '荷物', kana: 'にもつ', level: 2, theme: '旅行' },
  { en: 'foreign', ja: '外国の', kana: 'がいこくの', level: 2, theme: '旅行' },
  { en: 'arrive', ja: '到着する', kana: 'とうちゃくする', level: 2, theme: '旅行' },
  { en: 'guide', ja: '案内', kana: 'あんない', level: 2, theme: '旅行' },
  { en: 'meeting', ja: '会議', kana: 'かいぎ', level: 2, theme: 'ビジネス' },
  { en: 'report', ja: '報告', kana: 'ほうこく', level: 2, theme: 'ビジネス' },
  { en: 'office', ja: '会社', kana: 'かいしゃ', level: 2, theme: 'ビジネス' },
  { en: 'salary', ja: '給料', kana: 'きゅうりょう', level: 2, theme: 'ビジネス' },
  { en: 'manager', ja: '部長', kana: 'ぶちょう', level: 2, theme: 'ビジネス' },
  { en: 'customer', ja: '顧客', kana: 'こきゃく', level: 2, theme: 'ビジネス' },
  { en: 'prepare', ja: '準備する', kana: 'じゅんびする', level: 2, theme: 'ビジネス' },
  { en: 'attend', ja: '出席する', kana: 'しゅっせきする', level: 2, theme: 'ビジネス' },
  { en: 'deliver', ja: '届ける', kana: 'とどける', level: 2, theme: 'ビジネス' },
  { en: 'goods', ja: '商品', kana: 'しょうひん', level: 2, theme: 'ビジネス' },

  // ---- L3 中級（B1） ----
  { en: 'neighbor', ja: '近所の人', kana: 'きんじょのひと', level: 3, theme: '日常' },
  { en: 'improve', ja: '改善する', kana: 'かいぜんする', level: 3, theme: '日常' },
  { en: 'recently', ja: '最近', kana: 'さいきん', level: 3, theme: '日常' },
  { en: 'environment', ja: '環境', kana: 'かんきょう', level: 3, theme: '日常' },
  { en: 'opportunity', ja: '機会', kana: 'きかい', level: 3, theme: '日常' },
  { en: 'increase', ja: '増やす', kana: 'ふやす', level: 3, theme: '日常' },
  { en: 'available', ja: '利用できる', kana: 'りようできる', level: 3, theme: '日常' },
  { en: 'situation', ja: '状況', kana: 'じょうきょう', level: 3, theme: '日常' },
  { en: 'complain', ja: '不満を言う', kana: 'ふまんをいう', level: 3, theme: '日常' },
  { en: 'appreciate', ja: '感謝する', kana: 'かんしゃする', level: 3, theme: '日常' },
  { en: 'journey', ja: '旅', kana: 'たび', level: 3, theme: '旅行' },
  { en: 'currency', ja: '通貨', kana: 'つうか', level: 3, theme: '旅行' },
  { en: 'delay', ja: '遅れ', kana: 'おくれ', level: 3, theme: '旅行' },
  { en: 'departure', ja: '出発', kana: 'しゅっぱつ', level: 3, theme: '旅行' },
  { en: 'lodging', ja: '宿泊', kana: 'しゅくはく', level: 3, theme: '旅行' },
  { en: 'sightseeing', ja: '観光', kana: 'かんこう', level: 3, theme: '旅行' },
  { en: 'customs', ja: '税関', kana: 'ぜいかん', level: 3, theme: '旅行' },
  { en: 'destination', ja: '目的地', kana: 'もくてきち', level: 3, theme: '旅行' },
  { en: 'souvenir', ja: '土産', kana: 'みやげ', level: 3, theme: '旅行' },
  { en: 'schedule', ja: '予定', kana: 'よてい', level: 3, theme: 'ビジネス' },
  { en: 'propose', ja: '提案する', kana: 'ていあんする', level: 3, theme: 'ビジネス' },
  { en: 'client', ja: '取引先', kana: 'とりひきさき', level: 3, theme: 'ビジネス' },
  { en: 'deadline', ja: '締め切り', kana: 'しめきり', level: 3, theme: 'ビジネス' },
  { en: 'negotiate', ja: '交渉する', kana: 'こうしょうする', level: 3, theme: 'ビジネス' },
  { en: 'budget', ja: '予算', kana: 'よさん', level: 3, theme: 'ビジネス' },
  { en: 'contract', ja: '契約', kana: 'けいやく', level: 3, theme: 'ビジネス' },
  { en: 'colleague', ja: '同僚', kana: 'どうりょう', level: 3, theme: 'ビジネス' },
  { en: 'expand', ja: '拡大する', kana: 'かくだいする', level: 3, theme: 'ビジネス' },
  { en: 'profit', ja: '利益', kana: 'りえき', level: 3, theme: 'ビジネス' },
  { en: 'recommend', ja: '勧める', kana: 'すすめる', level: 3, theme: 'ビジネス' },

  // ---- L4 上級（B2–C1） ----
  { en: 'nevertheless', ja: 'それでも', kana: 'それでも', level: 4, theme: '日常' },
  { en: 'accomplish', ja: '成し遂げる', kana: 'なしとげる', level: 4, theme: '日常' },
  { en: 'consequence', ja: '結果', kana: 'けっか', level: 4, theme: '日常' },
  { en: 'inevitable', ja: '避けられない', kana: 'さけられない', level: 4, theme: '日常' },
  { en: 'sophisticated', ja: '洗練された', kana: 'せんれんされた', level: 4, theme: '日常' },
  { en: 'ambiguous', ja: '曖昧な', kana: 'あいまいな', level: 4, theme: '日常' },
  { en: 'perseverance', ja: '忍耐', kana: 'にんたい', level: 4, theme: '日常' },
  { en: 'deteriorate', ja: '悪化する', kana: 'あっかする', level: 4, theme: '日常' },
  { en: 'itinerary', ja: '旅程', kana: 'りょてい', level: 4, theme: '旅行' },
  { en: 'turbulence', ja: '乱気流', kana: 'らんきりゅう', level: 4, theme: '旅行' },
  { en: 'excursion', ja: '小旅行', kana: 'しょうりょこう', level: 4, theme: '旅行' },
  { en: 'hospitality', ja: 'もてなし', kana: 'もてなし', level: 4, theme: '旅行' },
  { en: 'expedition', ja: '遠征', kana: 'えんせい', level: 4, theme: '旅行' },
  { en: 'scenery', ja: '景色', kana: 'けしき', level: 4, theme: '旅行' },
  { en: 'invoice', ja: '請求書', kana: 'せいきゅうしょ', level: 4, theme: 'ビジネス' },
  { en: 'acquisition', ja: '買収', kana: 'ばいしゅう', level: 4, theme: 'ビジネス' },
  { en: 'comprehensive', ja: '包括的な', kana: 'ほうかつてきな', level: 4, theme: 'ビジネス' },
  { en: 'entrepreneur', ja: '起業家', kana: 'きぎょうか', level: 4, theme: 'ビジネス' },
  { en: 'stakeholder', ja: '利害関係者', kana: 'りがいかんけいしゃ', level: 4, theme: 'ビジネス' },
  { en: 'simultaneously', ja: '同時に', kana: 'どうじに', level: 4, theme: 'ビジネス' },
  { en: 'feasibility', ja: '実現性', kana: 'じつげんせい', level: 4, theme: 'ビジネス' },
  { en: 'procurement', ja: '調達', kana: 'ちょうたつ', level: 4, theme: 'ビジネス' },
  { en: 'consolidate', ja: '統合する', kana: 'とうごうする', level: 4, theme: 'ビジネス' },
  { en: 'leverage', ja: '活用する', kana: 'かつようする', level: 4, theme: 'ビジネス' },
  { en: 'contingency', ja: '不測の事態', kana: 'ふそくのじたい', level: 4, theme: 'ビジネス' },
  { en: 'delegate', ja: '委任する', kana: 'いにんする', level: 4, theme: 'ビジネス' },
  { en: 'streamline', ja: '効率化する', kana: 'こうりつかする', level: 4, theme: 'ビジネス' },
  { en: 'prospective', ja: '見込みの', kana: 'みこみの', level: 4, theme: 'ビジネス' },

  // ==== 拡充（Issue #15・各テーマ16語へ） ====
  // ---- L1 追加 ----
  { en: 'morning', ja: '朝', kana: 'あさ', level: 1, theme: '日常' },
  { en: 'night', ja: '夜', kana: 'よる', level: 1, theme: '日常' },
  { en: 'fruit', ja: '果物', kana: 'くだもの', level: 1, theme: '日常' },
  { en: 'sing', ja: '歌う', kana: 'うたう', level: 1, theme: '日常' },
  { en: 'ship', ja: '船', kana: 'ふね', level: 1, theme: '旅行' },
  { en: 'river', ja: '川', kana: 'かわ', level: 1, theme: '旅行' },
  { en: 'mountain', ja: '山', kana: 'やま', level: 1, theme: '旅行' },
  { en: 'town', ja: '町', kana: 'まち', level: 1, theme: '旅行' },
  { en: 'walk', ja: '歩く', kana: 'あるく', level: 1, theme: '旅行' },
  { en: 'ride', ja: '乗る', kana: 'のる', level: 1, theme: '旅行' },
  { en: 'far', ja: '遠い', kana: 'とおい', level: 1, theme: '旅行' },
  { en: 'shop', ja: '店', kana: 'みせ', level: 1, theme: 'ビジネス' },
  { en: 'sell', ja: '売る', kana: 'うる', level: 1, theme: 'ビジネス' },
  { en: 'pay', ja: '払う', kana: 'はらう', level: 1, theme: 'ビジネス' },
  { en: 'ask', ja: '尋ねる', kana: 'たずねる', level: 1, theme: 'ビジネス' },
  { en: 'talk', ja: '話す', kana: 'はなす', level: 1, theme: 'ビジネス' },
  { en: 'plan', ja: '計画', kana: 'けいかく', level: 1, theme: 'ビジネス' },
  { en: 'boss', ja: '上司', kana: 'じょうし', level: 1, theme: 'ビジネス' },

  // ---- L2 追加 ----
  { en: 'dinner', ja: '夕食', kana: 'ゆうしょく', level: 2, theme: '日常' },
  { en: 'hobby', ja: '趣味', kana: 'しゅみ', level: 2, theme: '日常' },
  { en: 'shopping', ja: '買い物', kana: 'かいもの', level: 2, theme: '日常' },
  { en: 'invite', ja: '招く', kana: 'まねく', level: 2, theme: '日常' },
  { en: 'repair', ja: '直す', kana: 'なおす', level: 2, theme: '日常' },
  { en: 'forest', ja: '森', kana: 'もり', level: 2, theme: '旅行' },
  { en: 'bridge', ja: '橋', kana: 'はし', level: 2, theme: '旅行' },
  { en: 'harbor', ja: '港', kana: 'みなと', level: 2, theme: '旅行' },
  { en: 'climb', ja: '登る', kana: 'のぼる', level: 2, theme: '旅行' },
  { en: 'view', ja: '景色', kana: 'けしき', level: 2, theme: '旅行' },
  { en: 'tour', ja: '見学', kana: 'けんがく', level: 2, theme: '旅行' },
  { en: 'beach', ja: '浜辺', kana: 'はまべ', level: 2, theme: '旅行' },
  { en: 'document', ja: '書類', kana: 'しょるい', level: 2, theme: 'ビジネス' },
  { en: 'project', ja: '企画', kana: 'きかく', level: 2, theme: 'ビジネス' },
  { en: 'contact', ja: '連絡', kana: 'れんらく', level: 2, theme: 'ビジネス' },
  { en: 'order', ja: '注文', kana: 'ちゅうもん', level: 2, theme: 'ビジネス' },
  { en: 'charge', ja: '料金', kana: 'りょうきん', level: 2, theme: 'ビジネス' },
  { en: 'section', ja: '部署', kana: 'ぶしょ', level: 2, theme: 'ビジネス' },

  // ---- L3 追加 ----
  { en: 'however', ja: 'しかし', kana: 'しかし', level: 3, theme: '日常' },
  { en: 'develop', ja: '発展する', kana: 'はってんする', level: 3, theme: '日常' },
  { en: 'average', ja: '平均', kana: 'へいきん', level: 3, theme: '日常' },
  { en: 'similar', ja: '似ている', kana: 'にている', level: 3, theme: '日常' },
  { en: 'prefer', ja: '好む', kana: 'このむ', level: 3, theme: '日常' },
  { en: 'reduce', ja: '減らす', kana: 'へらす', level: 3, theme: '日常' },
  { en: 'adventure', ja: '冒険', kana: 'ぼうけん', level: 3, theme: '旅行' },
  { en: 'region', ja: '地域', kana: 'ちいき', level: 3, theme: '旅行' },
  { en: 'route', ja: '経路', kana: 'けいろ', level: 3, theme: '旅行' },
  { en: 'distance', ja: '距離', kana: 'きょり', level: 3, theme: '旅行' },
  { en: 'depart', ja: '出発する', kana: 'しゅっぱつする', level: 3, theme: '旅行' },
  { en: 'arrival', ja: '到着', kana: 'とうちゃく', level: 3, theme: '旅行' },
  { en: 'passenger', ja: '乗客', kana: 'じょうきゃく', level: 3, theme: '旅行' },
  { en: 'invest', ja: '投資する', kana: 'とうしする', level: 3, theme: 'ビジネス' },
  { en: 'supply', ja: '供給', kana: 'きょうきゅう', level: 3, theme: 'ビジネス' },
  { en: 'demand', ja: '需要', kana: 'じゅよう', level: 3, theme: 'ビジネス' },
  { en: 'manage', ja: '管理する', kana: 'かんりする', level: 3, theme: 'ビジネス' },
  { en: 'achieve', ja: '達成する', kana: 'たっせいする', level: 3, theme: 'ビジネス' },

  // ---- L4 追加 ----
  { en: 'profound', ja: '深い', kana: 'ふかい', level: 4, theme: '日常' },
  { en: 'subtle', ja: '微妙な', kana: 'びみょうな', level: 4, theme: '日常' },
  { en: 'sincere', ja: '誠実な', kana: 'せいじつな', level: 4, theme: '日常' },
  { en: 'thorough', ja: '徹底的な', kana: 'てっていてきな', level: 4, theme: '日常' },
  { en: 'genuine', ja: '本物の', kana: 'ほんものの', level: 4, theme: '日常' },
  { en: 'modest', ja: '控えめな', kana: 'ひかえめな', level: 4, theme: '日常' },
  { en: 'eager', ja: '熱心な', kana: 'ねっしんな', level: 4, theme: '日常' },
  { en: 'humble', ja: '謙虚な', kana: 'けんきょな', level: 4, theme: '日常' },
  { en: 'voyage', ja: '航海', kana: 'こうかい', level: 4, theme: '旅行' },
  { en: 'panorama', ja: '全景', kana: 'ぜんけい', level: 4, theme: '旅行' },
  { en: 'vicinity', ja: '近辺', kana: 'きんぺん', level: 4, theme: '旅行' },
  { en: 'secluded', ja: '人里離れた', kana: 'ひとざとはなれた', level: 4, theme: '旅行' },
  { en: 'magnificent', ja: '壮大な', kana: 'そうだいな', level: 4, theme: '旅行' },
  { en: 'embark', ja: '乗船する', kana: 'じょうせんする', level: 4, theme: '旅行' },
  { en: 'detour', ja: '回り道', kana: 'まわりみち', level: 4, theme: '旅行' },
  { en: 'landscape', ja: '風景', kana: 'ふうけい', level: 4, theme: '旅行' },
  { en: 'terrain', ja: '地形', kana: 'ちけい', level: 4, theme: '旅行' },
  { en: 'wander', ja: 'さまよう', kana: 'さまよう', level: 4, theme: '旅行' },
  { en: 'negotiation', ja: '交渉', kana: 'こうしょう', level: 4, theme: 'ビジネス' },
  { en: 'compliance', ja: '法令順守', kana: 'ほうれいじゅんしゅ', level: 4, theme: 'ビジネス' },

  // ==== 頻度ベース拡充（Issue #26・最頻1,000帯の内容語） ====
  // 動詞
  { en: 'make', ja: '作る', kana: 'つくる', freq: 30, level: 1 },
  { en: 'take', ja: '取る', kana: 'とる', freq: 35, level: 1 },
  { en: 'come', ja: '来る', kana: 'くる', freq: 28, level: 1 },
  { en: 'see', ja: '見る', kana: 'みる', freq: 25, level: 1 },
  { en: 'know', ja: '知る', kana: 'しる', freq: 32, level: 1 },
  { en: 'get', ja: '得る', kana: 'える', freq: 38, level: 1 },
  { en: 'give', ja: '与える', kana: 'あたえる', freq: 42, level: 1 },
  { en: 'find', ja: '見つける', kana: 'みつける', freq: 48, level: 1 },
  { en: 'think', ja: '思う', kana: 'おもう', freq: 27, level: 1 },
  { en: 'tell', ja: '伝える', kana: 'つたえる', freq: 50, level: 1 },
  { en: 'become', ja: 'なる', kana: 'なる', freq: 55, level: 1 },
  { en: 'show', ja: '見せる', kana: 'みせる', freq: 60, level: 1 },
  { en: 'leave', ja: '去る', kana: 'さる', freq: 62, level: 1 },
  { en: 'feel', ja: '感じる', kana: 'かんじる', freq: 58, level: 1 },
  { en: 'put', ja: '置く', kana: 'おく', freq: 68, level: 1 },
  { en: 'bring', ja: '持ってくる', kana: 'もってくる', freq: 72, level: 1 },
  { en: 'begin', ja: '始める', kana: 'はじめる', freq: 64, level: 1 },
  { en: 'keep', ja: '保つ', kana: 'たもつ', freq: 78, level: 1 },
  { en: 'hold', ja: '持つ', kana: 'もつ', freq: 82, level: 1 },
  { en: 'hear', ja: '聞く', kana: 'きく', freq: 52, level: 1 },
  { en: 'understand', ja: '理解する', kana: 'りかいする', freq: 76, level: 1 },
  { en: 'stop', ja: '止める', kana: 'とめる', freq: 74, level: 1 },
  { en: 'read', ja: '読む', kana: 'よむ', freq: 54, level: 1 },
  { en: 'grow', ja: '育つ', kana: 'そだつ', freq: 86, level: 1 },
  { en: 'love', ja: '愛する', kana: 'あいする', freq: 80, level: 1, theme: '日常' },
  { en: 'wait', ja: '待つ', kana: 'まつ', freq: 70, level: 1 },
  { en: 'build', ja: '建てる', kana: 'たてる', freq: 92, level: 1 },
  { en: 'fall', ja: '落ちる', kana: 'おちる', freq: 88, level: 1 },
  { en: 'cut', ja: '切る', kana: 'きる', freq: 96, level: 1 },
  { en: 'carry', ja: '運ぶ', kana: 'はこぶ', freq: 98, level: 1 },
  { en: 'break', ja: '壊す', kana: 'こわす', freq: 102, level: 1 },
  { en: 'choose', ja: '選ぶ', kana: 'えらぶ', freq: 104, level: 1 },
  { en: 'catch', ja: '捕まえる', kana: 'つかまえる', freq: 106, level: 1 },
  { en: 'win', ja: '勝つ', kana: 'かつ', freq: 108, level: 1 },
  { en: 'lose', ja: '失う', kana: 'うしなう', freq: 112, level: 1 },
  { en: 'send', ja: '送る', kana: 'おくる', freq: 100, level: 1, theme: 'ビジネス' },
  { en: 'teach', ja: '教える', kana: 'おしえる', freq: 90, level: 1, theme: '日常' },
  { en: 'study', ja: '勉強する', kana: 'べんきょうする', freq: 84, level: 1, theme: '日常' },
  { en: 'play', ja: '遊ぶ', kana: 'あそぶ', freq: 79, level: 1, theme: '日常' },
  { en: 'enjoy', ja: '楽しむ', kana: 'たのしむ', freq: 94, level: 1, theme: '日常' },
  { en: 'explain', ja: '説明する', kana: 'せつめいする', freq: 116, level: 1 },
  { en: 'agree', ja: '同意する', kana: 'どういする', freq: 120, level: 1, theme: 'ビジネス' },
  { en: 'support', ja: '支える', kana: 'ささえる', freq: 122, level: 1 },
  // 名詞
  { en: 'man', ja: '男性', kana: 'だんせい', freq: 70, level: 1 },
  { en: 'woman', ja: '女性', kana: 'じょせい', freq: 75, level: 1 },
  { en: 'child', ja: '子ども', kana: 'こども', freq: 65, level: 1, theme: '日常' },
  { en: 'day', ja: '日', kana: 'ひ', freq: 40, level: 1 },
  { en: 'year', ja: '年', kana: 'とし', freq: 45, level: 1 },
  { en: 'way', ja: '方法', kana: 'ほうほう', freq: 81, level: 1 },
  { en: 'thing', ja: '物事', kana: 'ものごと', freq: 85, level: 1 },
  { en: 'life', ja: '人生', kana: 'じんせい', freq: 91, level: 1 },
  { en: 'hand', ja: '手', kana: 'て', freq: 95, level: 1, theme: '日常' },
  { en: 'place', ja: '場所', kana: 'ばしょ', freq: 89, level: 1 },
  { en: 'world', ja: '世界', kana: 'せかい', freq: 93, level: 1 },
  { en: 'problem', ja: '問題', kana: 'もんだい', freq: 101, level: 1 },
  { en: 'fact', ja: '事実', kana: 'じじつ', freq: 111, level: 1 },
  { en: 'group', ja: '集団', kana: 'しゅうだん', freq: 121, level: 1 },
  { en: 'number', ja: '数', kana: 'かず', freq: 107, level: 1 },
  { en: 'idea', ja: '考え', kana: 'かんがえ', freq: 115, level: 1 },
  { en: 'story', ja: '話', kana: 'はなし', freq: 118, level: 1 },
  { en: 'word', ja: '言葉', kana: 'ことば', freq: 109, level: 1 },
  { en: 'head', ja: '頭', kana: 'あたま', freq: 125, level: 1, theme: '日常' },
  { en: 'father', ja: '父', kana: 'ちち', freq: 131, level: 1, theme: '日常' },
  { en: 'mother', ja: '母', kana: 'はは', freq: 132, level: 1, theme: '日常' },
  { en: 'body', ja: '体', kana: 'からだ', freq: 145, level: 1, theme: '日常' },
  { en: 'parent', ja: '親', kana: 'おや', freq: 135, level: 1, theme: '日常' },
  { en: 'face', ja: '顔', kana: 'かお', freq: 142, level: 1, theme: '日常' },
  { en: 'health', ja: '健康', kana: 'けんこう', freq: 160, level: 1, theme: '日常' },
  { en: 'reason', ja: '理由', kana: 'りゆう', freq: 138, level: 1 },
  { en: 'teacher', ja: '先生', kana: 'せんせい', freq: 155, level: 1, theme: '日常' },
  { en: 'mind', ja: '心', kana: 'こころ', freq: 128, level: 1 },
  { en: 'power', ja: '力', kana: 'ちから', freq: 148, level: 1 },
  { en: 'music', ja: '音楽', kana: 'おんがく', freq: 165, level: 1, theme: '日常' },
  { en: 'movie', ja: '映画', kana: 'えいが', freq: 175, level: 1, theme: '日常' },
  { en: 'letter', ja: '手紙', kana: 'てがみ', freq: 158, level: 1, theme: '日常' },
  { en: 'paper', ja: '紙', kana: 'かみ', freq: 152, level: 1 },
  { en: 'company', ja: '会社', kana: 'かいしゃ', freq: 180, level: 1, theme: 'ビジネス' },
  { en: 'business', ja: '商売', kana: 'しょうばい', freq: 185, level: 1, theme: 'ビジネス' },
  { en: 'price', ja: '値段', kana: 'ねだん', freq: 190, level: 1, theme: 'ビジネス' },
  { en: 'market', ja: '市場', kana: 'しじょう', freq: 195, level: 1, theme: 'ビジネス' },
  { en: 'value', ja: '価値', kana: 'かち', freq: 200, level: 1, theme: 'ビジネス' },
  { en: 'street', ja: '通り', kana: 'とおり', freq: 178, level: 1, theme: '旅行' },
  { en: 'city', ja: '都会', kana: 'とかい', freq: 172, level: 1, theme: '旅行' },
  // 形容詞
  { en: 'good', ja: '良い', kana: 'よい', freq: 20, level: 1 },
  { en: 'new', ja: '新しい', kana: 'あたらしい', freq: 33, level: 1 },
  { en: 'great', ja: '偉大な', kana: 'いだいな', freq: 66, level: 1 },
  { en: 'big', ja: '大きい', kana: 'おおきい', freq: 44, level: 1 },
  { en: 'small', ja: '小さい', kana: 'ちいさい', freq: 46, level: 1 },
  { en: 'long', ja: '長い', kana: 'ながい', freq: 56, level: 1 },
  { en: 'short', ja: '短い', kana: 'みじかい', freq: 59, level: 1 },
  { en: 'high', ja: '高い', kana: 'たかい', freq: 61, level: 1 },
  { en: 'low', ja: '低い', kana: 'ひくい', freq: 113, level: 1 },
  { en: 'old', ja: '古い', kana: 'ふるい', freq: 51, level: 1 },
  { en: 'young', ja: '若い', kana: 'わかい', freq: 63, level: 1 },
  { en: 'right', ja: '正しい', kana: 'ただしい', freq: 67, level: 1 },
  { en: 'wrong', ja: '誤った', kana: 'あやまった', freq: 133, level: 1 },
  { en: 'important', ja: '重要な', kana: 'じゅうような', freq: 69, level: 1 },
  { en: 'different', ja: '異なる', kana: 'ことなる', freq: 73, level: 1 },
  { en: 'same', ja: '同じ', kana: 'おなじ', freq: 49, level: 1 },
  { en: 'easy', ja: '簡単な', kana: 'かんたんな', freq: 77, level: 1 },
  { en: 'difficult', ja: '難しい', kana: 'むずかしい', freq: 83, level: 1 },
  { en: 'early', ja: '早い', kana: 'はやい', freq: 71, level: 1 },
  { en: 'late', ja: '遅い', kana: 'おそい', freq: 103, level: 1 },
  { en: 'strong', ja: '強い', kana: 'つよい', freq: 87, level: 1 },
  { en: 'weak', ja: '弱い', kana: 'よわい', freq: 141, level: 1 },
  { en: 'beautiful', ja: '美しい', kana: 'うつくしい', freq: 97, level: 1 },
  { en: 'famous', ja: '有名な', kana: 'ゆうめいな', freq: 151, level: 1 },
  { en: 'free', ja: '自由な', kana: 'じゆうな', freq: 123, level: 1 },
]
