// 単語問題データ（頻度帯 level × テーマ theme[任意]）。
// en=英単語 / ja=和訳 / kana=和訳の読み（日本語入力用）/ freq=頻度ランク(目安) / theme=任意。
// level は freq の頻度帯（bandOf）と一致させる。
export const WORD_LEVELS = [
  { level: 1, label: '基礎', cefr: 'A1', range: '1–1,000' },
  { level: 2, label: '初級', cefr: 'A2', range: '1,001–2,000' },
  { level: 3, label: '中級', cefr: 'B1', range: '2,001–3,000' },
  { level: 4, label: '上級', cefr: 'B2–C1', range: '3,001–5,000' },
]

// 頻度ランク → レベル（頻度帯）。5,000超は最上位帯へ。
const BAND_MAX = [1000, 2000, 3000, 5000]
export function bandOf(freq) {
  for (let i = 0; i < BAND_MAX.length; i++) if (freq <= BAND_MAX[i]) return i + 1
  return WORD_LEVELS.length
}

export const WORD_THEMES = ['日常', '旅行', 'ビジネス']

// 単語モード（英語・日本語/英語/日本語=入力、英語訳/日本語訳=4択クイズ）
export const WORD_MODES = [
  { key: 'both', label: '英語・日本語' },
  { key: 'en', label: '英語' },
  { key: 'ja', label: '日本語' },
  { key: 'quiz-en', label: '英語訳' },
  { key: 'quiz-ja', label: '日本語訳' },
]

export const WORDS = [
  // ---- L1 基礎（A1） ----
  { en: 'water', ja: '水', kana: 'みず', level: 1, theme: '日常' },
  { en: 'food', ja: '食べ物', kana: 'たべもの', level: 1, theme: '日常' },
  { en: 'friend', ja: '友達', kana: 'ともだち', level: 1, theme: '日常' },
  { en: 'house', ja: '家', kana: 'いえ', level: 1, theme: '日常' },
  { en: 'book', ja: '本', kana: 'ほん', level: 1, theme: '日常' },
  { en: 'dog', ja: '犬', kana: 'いぬ', level: 1, theme: '日常' },
  { en: 'cat', ja: '猫', kana: 'ねこ', level: 1, theme: '日常' },
  { en: 'eat', ja: '食べる', kana: 'たべる', level: 1, theme: '日常' },
  { en: 'run', ja: '走る', kana: 'はしる', level: 1, theme: '日常' },
  { en: 'happy', ja: '幸せ', kana: 'しあわせ', level: 1, theme: '日常' },
  { en: 'school', ja: '学校', kana: 'がっこう', level: 1, theme: '日常' },
  { en: 'family', ja: '家族', kana: 'かぞく', level: 1, theme: '日常' },
  { en: 'bag', ja: 'かばん', kana: 'かばん', level: 1, theme: '旅行' },
  { en: 'map', ja: '地図', kana: 'ちず', level: 1, theme: '旅行' },
  { en: 'hotel', ja: 'ホテル', kana: 'ほてる', level: 1, theme: '旅行' },
  { en: 'train', ja: '電車', kana: 'でんしゃ', level: 1, theme: '旅行' },
  { en: 'car', ja: '車', kana: 'くるま', level: 1, theme: '旅行' },
  { en: 'sea', ja: '海', kana: 'うみ', level: 1, theme: '旅行' },
  { en: 'road', ja: '道', kana: 'みち', level: 1, theme: '旅行' },
  { en: 'trip', ja: '旅行', kana: 'りょこう', level: 1, theme: '旅行' },
  { en: 'fly', ja: '飛ぶ', kana: 'とぶ', level: 1, theme: '旅行' },
  { en: 'work', ja: '仕事', kana: 'しごと', level: 1, theme: 'ビジネス' },
  { en: 'time', ja: '時間', kana: 'じかん', level: 1, theme: 'ビジネス' },
  { en: 'money', ja: 'お金', kana: 'おかね', level: 1, theme: 'ビジネス' },
  { en: 'name', ja: '名前', kana: 'なまえ', level: 1, theme: 'ビジネス' },
  { en: 'phone', ja: '電話', kana: 'でんわ', level: 1, theme: 'ビジネス' },
  { en: 'help', ja: '助ける', kana: 'たすける', level: 1, theme: 'ビジネス' },
  { en: 'write', ja: '書く', kana: 'かく', level: 1, theme: 'ビジネス' },
  { en: 'meet', ja: '会う', kana: 'あう', level: 1, theme: 'ビジネス' },
  { en: 'busy', ja: '忙しい', kana: 'いそがしい', level: 1, theme: 'ビジネス' },

  // ---- L2 初級（A2） ----
  { en: 'kitchen', ja: '台所', kana: 'だいどころ', level: 2, theme: '日常' },
  { en: 'weather', ja: '天気', kana: 'てんき', level: 2, theme: '日常' },
  { en: 'kind', ja: '親切', kana: 'しんせつ', level: 2, theme: '日常' },
  { en: 'breakfast', ja: '朝食', kana: 'ちょうしょく', level: 2, theme: '日常' },
  { en: 'garden', ja: '庭', kana: 'にわ', level: 2, theme: '日常' },
  { en: 'clean', ja: '掃除する', kana: 'そうじする', level: 2, theme: '日常' },
  { en: 'decide', ja: '決める', kana: 'きめる', level: 2, theme: '日常' },
  { en: 'weekend', ja: '週末', kana: 'しゅうまつ', level: 2, theme: '日常' },
  { en: 'healthy', ja: '健康', kana: 'けんこう', level: 2, theme: '日常' },
  { en: 'expensive', ja: '高い', kana: 'たかい', level: 2, theme: '日常' },
  { en: 'borrow', ja: '借りる', kana: 'かりる', level: 2, theme: '日常' },
  { en: 'airport', ja: '空港', kana: 'くうこう', level: 2, theme: '旅行' },
  { en: 'ticket', ja: '切符', kana: 'きっぷ', level: 2, theme: '旅行' },
  { en: 'reserve', ja: '予約する', kana: 'よやくする', level: 2, theme: '旅行' },
  { en: 'station', ja: '駅', kana: 'えき', level: 2, theme: '旅行' },
  { en: 'passport', ja: '旅券', kana: 'りょけん', level: 2, theme: '旅行' },
  { en: 'luggage', ja: '荷物', kana: 'にもつ', level: 2, theme: '旅行' },
  { en: 'foreign', ja: '外国の', kana: 'がいこくの', level: 2, theme: '旅行' },
  { en: 'arrive', ja: '到着する', kana: 'とうちゃくする', level: 2, theme: '旅行' },
  { en: 'guide', ja: '案内', kana: 'あんない', level: 2, theme: '旅行' },
  { en: 'meeting', ja: '会議', kana: 'かいぎ', level: 2, theme: 'ビジネス' },
  { en: 'report', ja: '報告', kana: 'ほうこく', level: 2, theme: 'ビジネス' },
  { en: 'office', ja: '会社', kana: 'かいしゃ', level: 2, theme: 'ビジネス' },
  { en: 'salary', ja: '給料', kana: 'きゅうりょう', level: 2, theme: 'ビジネス' },
  { en: 'manager', ja: '部長', kana: 'ぶちょう', level: 2, theme: 'ビジネス' },
  { en: 'customer', ja: '顧客', kana: 'こきゃく', level: 2, theme: 'ビジネス' },
  { en: 'prepare', ja: '準備する', kana: 'じゅんびする', level: 2, theme: 'ビジネス' },
  { en: 'attend', ja: '出席する', kana: 'しゅっせきする', level: 2, theme: 'ビジネス' },
  { en: 'deliver', ja: '届ける', kana: 'とどける', level: 2, theme: 'ビジネス' },
  { en: 'goods', ja: '商品', kana: 'しょうひん', level: 2, theme: 'ビジネス' },

  // ---- L3 中級（B1） ----
  { en: 'neighbor', ja: '近所の人', kana: 'きんじょのひと', level: 3, theme: '日常' },
  { en: 'improve', ja: '改善する', kana: 'かいぜんする', level: 3, theme: '日常' },
  { en: 'recently', ja: '最近', kana: 'さいきん', level: 3, theme: '日常' },
  { en: 'environment', ja: '環境', kana: 'かんきょう', level: 3, theme: '日常' },
  { en: 'opportunity', ja: '機会', kana: 'きかい', level: 3, theme: '日常' },
  { en: 'increase', ja: '増やす', kana: 'ふやす', level: 3, theme: '日常' },
  { en: 'available', ja: '利用できる', kana: 'りようできる', level: 3, theme: '日常' },
  { en: 'situation', ja: '状況', kana: 'じょうきょう', level: 3, theme: '日常' },
  { en: 'complain', ja: '不満を言う', kana: 'ふまんをいう', level: 3, theme: '日常' },
  { en: 'appreciate', ja: '感謝する', kana: 'かんしゃする', level: 3, theme: '日常' },
  { en: 'journey', ja: '旅', kana: 'たび', level: 3, theme: '旅行' },
  { en: 'currency', ja: '通貨', kana: 'つうか', level: 3, theme: '旅行' },
  { en: 'delay', ja: '遅れ', kana: 'おくれ', level: 3, theme: '旅行' },
  { en: 'departure', ja: '出発', kana: 'しゅっぱつ', level: 3, theme: '旅行' },
  { en: 'lodging', ja: '宿泊', kana: 'しゅくはく', level: 3, theme: '旅行' },
  { en: 'sightseeing', ja: '観光', kana: 'かんこう', level: 3, theme: '旅行' },
  { en: 'customs', ja: '税関', kana: 'ぜいかん', level: 3, theme: '旅行' },
  { en: 'destination', ja: '目的地', kana: 'もくてきち', level: 3, theme: '旅行' },
  { en: 'souvenir', ja: '土産', kana: 'みやげ', level: 3, theme: '旅行' },
  { en: 'schedule', ja: '予定', kana: 'よてい', level: 3, theme: 'ビジネス' },
  { en: 'propose', ja: '提案する', kana: 'ていあんする', level: 3, theme: 'ビジネス' },
  { en: 'client', ja: '取引先', kana: 'とりひきさき', level: 3, theme: 'ビジネス' },
  { en: 'deadline', ja: '締め切り', kana: 'しめきり', level: 3, theme: 'ビジネス' },
  { en: 'negotiate', ja: '交渉する', kana: 'こうしょうする', level: 3, theme: 'ビジネス' },
  { en: 'budget', ja: '予算', kana: 'よさん', level: 3, theme: 'ビジネス' },
  { en: 'contract', ja: '契約', kana: 'けいやく', level: 3, theme: 'ビジネス' },
  { en: 'colleague', ja: '同僚', kana: 'どうりょう', level: 3, theme: 'ビジネス' },
  { en: 'expand', ja: '拡大する', kana: 'かくだいする', level: 3, theme: 'ビジネス' },
  { en: 'profit', ja: '利益', kana: 'りえき', level: 3, theme: 'ビジネス' },
  { en: 'recommend', ja: '勧める', kana: 'すすめる', level: 3, theme: 'ビジネス' },

  // ---- L4 上級（B2–C1） ----
  { en: 'nevertheless', ja: 'それでも', kana: 'それでも', level: 4, theme: '日常' },
  { en: 'accomplish', ja: '成し遂げる', kana: 'なしとげる', level: 4, theme: '日常' },
  { en: 'consequence', ja: '結果', kana: 'けっか', level: 4, theme: '日常' },
  { en: 'inevitable', ja: '避けられない', kana: 'さけられない', level: 4, theme: '日常' },
  { en: 'sophisticated', ja: '洗練された', kana: 'せんれんされた', level: 4, theme: '日常' },
  { en: 'ambiguous', ja: '曖昧な', kana: 'あいまいな', level: 4, theme: '日常' },
  { en: 'perseverance', ja: '忍耐', kana: 'にんたい', level: 4, theme: '日常' },
  { en: 'deteriorate', ja: '悪化する', kana: 'あっかする', level: 4, theme: '日常' },
  { en: 'itinerary', ja: '旅程', kana: 'りょてい', level: 4, theme: '旅行' },
  { en: 'turbulence', ja: '乱気流', kana: 'らんきりゅう', level: 4, theme: '旅行' },
  { en: 'excursion', ja: '小旅行', kana: 'しょうりょこう', level: 4, theme: '旅行' },
  { en: 'hospitality', ja: 'もてなし', kana: 'もてなし', level: 4, theme: '旅行' },
  { en: 'expedition', ja: '遠征', kana: 'えんせい', level: 4, theme: '旅行' },
  { en: 'scenery', ja: '景色', kana: 'けしき', level: 4, theme: '旅行' },
  { en: 'invoice', ja: '請求書', kana: 'せいきゅうしょ', level: 4, theme: 'ビジネス' },
  { en: 'acquisition', ja: '買収', kana: 'ばいしゅう', level: 4, theme: 'ビジネス' },
  { en: 'comprehensive', ja: '包括的な', kana: 'ほうかつてきな', level: 4, theme: 'ビジネス' },
  { en: 'entrepreneur', ja: '起業家', kana: 'きぎょうか', level: 4, theme: 'ビジネス' },
  { en: 'stakeholder', ja: '利害関係者', kana: 'りがいかんけいしゃ', level: 4, theme: 'ビジネス' },
  { en: 'simultaneously', ja: '同時に', kana: 'どうじに', level: 4, theme: 'ビジネス' },
  { en: 'feasibility', ja: '実現性', kana: 'じつげんせい', level: 4, theme: 'ビジネス' },
  { en: 'procurement', ja: '調達', kana: 'ちょうたつ', level: 4, theme: 'ビジネス' },
  { en: 'consolidate', ja: '統合する', kana: 'とうごうする', level: 4, theme: 'ビジネス' },
  { en: 'leverage', ja: '活用する', kana: 'かつようする', level: 4, theme: 'ビジネス' },
  { en: 'contingency', ja: '不測の事態', kana: 'ふそくのじたい', level: 4, theme: 'ビジネス' },
  { en: 'delegate', ja: '委任する', kana: 'いにんする', level: 4, theme: 'ビジネス' },
  { en: 'streamline', ja: '効率化する', kana: 'こうりつかする', level: 4, theme: 'ビジネス' },
  { en: 'prospective', ja: '見込みの', kana: 'みこみの', level: 4, theme: 'ビジネス' },

  // ==== 拡充（Issue #15・各テーマ16語へ） ====
  // ---- L1 追加 ----
  { en: 'morning', ja: '朝', kana: 'あさ', level: 1, theme: '日常' },
  { en: 'night', ja: '夜', kana: 'よる', level: 1, theme: '日常' },
  { en: 'fruit', ja: '果物', kana: 'くだもの', level: 1, theme: '日常' },
  { en: 'sing', ja: '歌う', kana: 'うたう', level: 1, theme: '日常' },
  { en: 'ship', ja: '船', kana: 'ふね', level: 1, theme: '旅行' },
  { en: 'river', ja: '川', kana: 'かわ', level: 1, theme: '旅行' },
  { en: 'mountain', ja: '山', kana: 'やま', level: 1, theme: '旅行' },
  { en: 'town', ja: '町', kana: 'まち', level: 1, theme: '旅行' },
  { en: 'walk', ja: '歩く', kana: 'あるく', level: 1, theme: '旅行' },
  { en: 'ride', ja: '乗る', kana: 'のる', level: 1, theme: '旅行' },
  { en: 'far', ja: '遠い', kana: 'とおい', level: 1, theme: '旅行' },
  { en: 'shop', ja: '店', kana: 'みせ', level: 1, theme: 'ビジネス' },
  { en: 'sell', ja: '売る', kana: 'うる', level: 1, theme: 'ビジネス' },
  { en: 'pay', ja: '払う', kana: 'はらう', level: 1, theme: 'ビジネス' },
  { en: 'ask', ja: '尋ねる', kana: 'たずねる', level: 1, theme: 'ビジネス' },
  { en: 'talk', ja: '話す', kana: 'はなす', level: 1, theme: 'ビジネス' },
  { en: 'plan', ja: '計画', kana: 'けいかく', level: 1, theme: 'ビジネス' },
  { en: 'boss', ja: '上司', kana: 'じょうし', level: 1, theme: 'ビジネス' },

  // ---- L2 追加 ----
  { en: 'dinner', ja: '夕食', kana: 'ゆうしょく', level: 2, theme: '日常' },
  { en: 'hobby', ja: '趣味', kana: 'しゅみ', level: 2, theme: '日常' },
  { en: 'shopping', ja: '買い物', kana: 'かいもの', level: 2, theme: '日常' },
  { en: 'invite', ja: '招く', kana: 'まねく', level: 2, theme: '日常' },
  { en: 'repair', ja: '直す', kana: 'なおす', level: 2, theme: '日常' },
  { en: 'forest', ja: '森', kana: 'もり', level: 2, theme: '旅行' },
  { en: 'bridge', ja: '橋', kana: 'はし', level: 2, theme: '旅行' },
  { en: 'harbor', ja: '港', kana: 'みなと', level: 2, theme: '旅行' },
  { en: 'climb', ja: '登る', kana: 'のぼる', level: 2, theme: '旅行' },
  { en: 'view', ja: '景色', kana: 'けしき', level: 2, theme: '旅行' },
  { en: 'tour', ja: '見学', kana: 'けんがく', level: 2, theme: '旅行' },
  { en: 'beach', ja: '浜辺', kana: 'はまべ', level: 2, theme: '旅行' },
  { en: 'document', ja: '書類', kana: 'しょるい', level: 2, theme: 'ビジネス' },
  { en: 'project', ja: '企画', kana: 'きかく', level: 2, theme: 'ビジネス' },
  { en: 'contact', ja: '連絡', kana: 'れんらく', level: 2, theme: 'ビジネス' },
  { en: 'order', ja: '注文', kana: 'ちゅうもん', level: 2, theme: 'ビジネス' },
  { en: 'charge', ja: '料金', kana: 'りょうきん', level: 2, theme: 'ビジネス' },
  { en: 'section', ja: '部署', kana: 'ぶしょ', level: 2, theme: 'ビジネス' },

  // ---- L3 追加 ----
  { en: 'however', ja: 'しかし', kana: 'しかし', level: 3, theme: '日常' },
  { en: 'develop', ja: '発展する', kana: 'はってんする', level: 3, theme: '日常' },
  { en: 'average', ja: '平均', kana: 'へいきん', level: 3, theme: '日常' },
  { en: 'similar', ja: '似ている', kana: 'にている', level: 3, theme: '日常' },
  { en: 'prefer', ja: '好む', kana: 'このむ', level: 3, theme: '日常' },
  { en: 'reduce', ja: '減らす', kana: 'へらす', level: 3, theme: '日常' },
  { en: 'adventure', ja: '冒険', kana: 'ぼうけん', level: 3, theme: '旅行' },
  { en: 'region', ja: '地域', kana: 'ちいき', level: 3, theme: '旅行' },
  { en: 'route', ja: '経路', kana: 'けいろ', level: 3, theme: '旅行' },
  { en: 'distance', ja: '距離', kana: 'きょり', level: 3, theme: '旅行' },
  { en: 'depart', ja: '出発する', kana: 'しゅっぱつする', level: 3, theme: '旅行' },
  { en: 'arrival', ja: '到着', kana: 'とうちゃく', level: 3, theme: '旅行' },
  { en: 'passenger', ja: '乗客', kana: 'じょうきゃく', level: 3, theme: '旅行' },
  { en: 'invest', ja: '投資する', kana: 'とうしする', level: 3, theme: 'ビジネス' },
  { en: 'supply', ja: '供給', kana: 'きょうきゅう', level: 3, theme: 'ビジネス' },
  { en: 'demand', ja: '需要', kana: 'じゅよう', level: 3, theme: 'ビジネス' },
  { en: 'manage', ja: '管理する', kana: 'かんりする', level: 3, theme: 'ビジネス' },
  { en: 'achieve', ja: '達成する', kana: 'たっせいする', level: 3, theme: 'ビジネス' },

  // ---- L4 追加 ----
  { en: 'profound', ja: '深い', kana: 'ふかい', level: 4, theme: '日常' },
  { en: 'subtle', ja: '微妙な', kana: 'びみょうな', level: 4, theme: '日常' },
  { en: 'sincere', ja: '誠実な', kana: 'せいじつな', level: 4, theme: '日常' },
  { en: 'thorough', ja: '徹底的な', kana: 'てっていてきな', level: 4, theme: '日常' },
  { en: 'genuine', ja: '本物の', kana: 'ほんものの', level: 4, theme: '日常' },
  { en: 'modest', ja: '控えめな', kana: 'ひかえめな', level: 4, theme: '日常' },
  { en: 'eager', ja: '熱心な', kana: 'ねっしんな', level: 4, theme: '日常' },
  { en: 'humble', ja: '謙虚な', kana: 'けんきょな', level: 4, theme: '日常' },
  { en: 'voyage', ja: '航海', kana: 'こうかい', level: 4, theme: '旅行' },
  { en: 'panorama', ja: '全景', kana: 'ぜんけい', level: 4, theme: '旅行' },
  { en: 'vicinity', ja: '近辺', kana: 'きんぺん', level: 4, theme: '旅行' },
  { en: 'secluded', ja: '人里離れた', kana: 'ひとざとはなれた', level: 4, theme: '旅行' },
  { en: 'magnificent', ja: '壮大な', kana: 'そうだいな', level: 4, theme: '旅行' },
  { en: 'embark', ja: '乗船する', kana: 'じょうせんする', level: 4, theme: '旅行' },
  { en: 'detour', ja: '回り道', kana: 'まわりみち', level: 4, theme: '旅行' },
  { en: 'landscape', ja: '風景', kana: 'ふうけい', level: 4, theme: '旅行' },
  { en: 'terrain', ja: '地形', kana: 'ちけい', level: 4, theme: '旅行' },
  { en: 'wander', ja: 'さまよう', kana: 'さまよう', level: 4, theme: '旅行' },
  { en: 'negotiation', ja: '交渉', kana: 'こうしょう', level: 4, theme: 'ビジネス' },
  { en: 'compliance', ja: '法令順守', kana: 'ほうれいじゅんしゅ', level: 4, theme: 'ビジネス' },

  // ==== 頻度ベース拡充（Issue #26・最頻1,000帯の内容語） ====
  // 動詞
  { en: 'make', ja: '作る', kana: 'つくる', freq: 30, level: 1 },
  { en: 'take', ja: '取る', kana: 'とる', freq: 35, level: 1 },
  { en: 'come', ja: '来る', kana: 'くる', freq: 28, level: 1 },
  { en: 'see', ja: '見る', kana: 'みる', freq: 25, level: 1 },
  { en: 'know', ja: '知る', kana: 'しる', freq: 32, level: 1 },
  { en: 'get', ja: '得る', kana: 'える', freq: 38, level: 1 },
  { en: 'give', ja: '与える', kana: 'あたえる', freq: 42, level: 1 },
  { en: 'find', ja: '見つける', kana: 'みつける', freq: 48, level: 1 },
  { en: 'think', ja: '思う', kana: 'おもう', freq: 27, level: 1 },
  { en: 'tell', ja: '伝える', kana: 'つたえる', freq: 50, level: 1 },
  { en: 'become', ja: 'なる', kana: 'なる', freq: 55, level: 1 },
  { en: 'show', ja: '見せる', kana: 'みせる', freq: 60, level: 1 },
  { en: 'leave', ja: '去る', kana: 'さる', freq: 62, level: 1 },
  { en: 'feel', ja: '感じる', kana: 'かんじる', freq: 58, level: 1 },
  { en: 'put', ja: '置く', kana: 'おく', freq: 68, level: 1 },
  { en: 'bring', ja: '持ってくる', kana: 'もってくる', freq: 72, level: 1 },
  { en: 'begin', ja: '始める', kana: 'はじめる', freq: 64, level: 1 },
  { en: 'keep', ja: '保つ', kana: 'たもつ', freq: 78, level: 1 },
  { en: 'hold', ja: '持つ', kana: 'もつ', freq: 82, level: 1 },
  { en: 'hear', ja: '聞く', kana: 'きく', freq: 52, level: 1 },
  { en: 'understand', ja: '理解する', kana: 'りかいする', freq: 76, level: 1 },
  { en: 'stop', ja: '止める', kana: 'とめる', freq: 74, level: 1 },
  { en: 'read', ja: '読む', kana: 'よむ', freq: 54, level: 1 },
  { en: 'grow', ja: '育つ', kana: 'そだつ', freq: 86, level: 1 },
  { en: 'love', ja: '愛する', kana: 'あいする', freq: 80, level: 1, theme: '日常' },
  { en: 'wait', ja: '待つ', kana: 'まつ', freq: 70, level: 1 },
  { en: 'build', ja: '建てる', kana: 'たてる', freq: 92, level: 1 },
  { en: 'fall', ja: '落ちる', kana: 'おちる', freq: 88, level: 1 },
  { en: 'cut', ja: '切る', kana: 'きる', freq: 96, level: 1 },
  { en: 'carry', ja: '運ぶ', kana: 'はこぶ', freq: 98, level: 1 },
  { en: 'break', ja: '壊す', kana: 'こわす', freq: 102, level: 1 },
  { en: 'choose', ja: '選ぶ', kana: 'えらぶ', freq: 104, level: 1 },
  { en: 'catch', ja: '捕まえる', kana: 'つかまえる', freq: 106, level: 1 },
  { en: 'win', ja: '勝つ', kana: 'かつ', freq: 108, level: 1 },
  { en: 'lose', ja: '失う', kana: 'うしなう', freq: 112, level: 1 },
  { en: 'send', ja: '送る', kana: 'おくる', freq: 100, level: 1, theme: 'ビジネス' },
  { en: 'teach', ja: '教える', kana: 'おしえる', freq: 90, level: 1, theme: '日常' },
  { en: 'study', ja: '勉強する', kana: 'べんきょうする', freq: 84, level: 1, theme: '日常' },
  { en: 'play', ja: '遊ぶ', kana: 'あそぶ', freq: 79, level: 1, theme: '日常' },
  { en: 'enjoy', ja: '楽しむ', kana: 'たのしむ', freq: 94, level: 1, theme: '日常' },
  { en: 'explain', ja: '説明する', kana: 'せつめいする', freq: 116, level: 1 },
  { en: 'agree', ja: '同意する', kana: 'どういする', freq: 120, level: 1, theme: 'ビジネス' },
  { en: 'support', ja: '支える', kana: 'ささえる', freq: 122, level: 1 },
  // 名詞
  { en: 'man', ja: '男性', kana: 'だんせい', freq: 70, level: 1 },
  { en: 'woman', ja: '女性', kana: 'じょせい', freq: 75, level: 1 },
  { en: 'child', ja: '子ども', kana: 'こども', freq: 65, level: 1, theme: '日常' },
  { en: 'day', ja: '日', kana: 'ひ', freq: 40, level: 1 },
  { en: 'year', ja: '年', kana: 'とし', freq: 45, level: 1 },
  { en: 'way', ja: '方法', kana: 'ほうほう', freq: 81, level: 1 },
  { en: 'thing', ja: '物事', kana: 'ものごと', freq: 85, level: 1 },
  { en: 'life', ja: '人生', kana: 'じんせい', freq: 91, level: 1 },
  { en: 'hand', ja: '手', kana: 'て', freq: 95, level: 1, theme: '日常' },
  { en: 'place', ja: '場所', kana: 'ばしょ', freq: 89, level: 1 },
  { en: 'world', ja: '世界', kana: 'せかい', freq: 93, level: 1 },
  { en: 'problem', ja: '問題', kana: 'もんだい', freq: 101, level: 1 },
  { en: 'fact', ja: '事実', kana: 'じじつ', freq: 111, level: 1 },
  { en: 'group', ja: '集団', kana: 'しゅうだん', freq: 121, level: 1 },
  { en: 'number', ja: '数', kana: 'かず', freq: 107, level: 1 },
  { en: 'idea', ja: '考え', kana: 'かんがえ', freq: 115, level: 1 },
  { en: 'story', ja: '話', kana: 'はなし', freq: 118, level: 1 },
  { en: 'word', ja: '言葉', kana: 'ことば', freq: 109, level: 1 },
  { en: 'head', ja: '頭', kana: 'あたま', freq: 125, level: 1, theme: '日常' },
  { en: 'father', ja: '父', kana: 'ちち', freq: 131, level: 1, theme: '日常' },
  { en: 'mother', ja: '母', kana: 'はは', freq: 132, level: 1, theme: '日常' },
  { en: 'body', ja: '体', kana: 'からだ', freq: 145, level: 1, theme: '日常' },
  { en: 'parent', ja: '親', kana: 'おや', freq: 135, level: 1, theme: '日常' },
  { en: 'face', ja: '顔', kana: 'かお', freq: 142, level: 1, theme: '日常' },
  { en: 'health', ja: '健康', kana: 'けんこう', freq: 160, level: 1, theme: '日常' },
  { en: 'reason', ja: '理由', kana: 'りゆう', freq: 138, level: 1 },
  { en: 'teacher', ja: '先生', kana: 'せんせい', freq: 155, level: 1, theme: '日常' },
  { en: 'mind', ja: '心', kana: 'こころ', freq: 128, level: 1 },
  { en: 'power', ja: '力', kana: 'ちから', freq: 148, level: 1 },
  { en: 'music', ja: '音楽', kana: 'おんがく', freq: 165, level: 1, theme: '日常' },
  { en: 'movie', ja: '映画', kana: 'えいが', freq: 175, level: 1, theme: '日常' },
  { en: 'letter', ja: '手紙', kana: 'てがみ', freq: 158, level: 1, theme: '日常' },
  { en: 'paper', ja: '紙', kana: 'かみ', freq: 152, level: 1 },
  { en: 'company', ja: '会社', kana: 'かいしゃ', freq: 180, level: 1, theme: 'ビジネス' },
  { en: 'business', ja: '商売', kana: 'しょうばい', freq: 185, level: 1, theme: 'ビジネス' },
  { en: 'price', ja: '値段', kana: 'ねだん', freq: 190, level: 1, theme: 'ビジネス' },
  { en: 'market', ja: '市場', kana: 'しじょう', freq: 195, level: 1, theme: 'ビジネス' },
  { en: 'value', ja: '価値', kana: 'かち', freq: 200, level: 1, theme: 'ビジネス' },
  { en: 'street', ja: '通り', kana: 'とおり', freq: 178, level: 1, theme: '旅行' },
  { en: 'city', ja: '都会', kana: 'とかい', freq: 172, level: 1, theme: '旅行' },
  // 形容詞
  { en: 'good', ja: '良い', kana: 'よい', freq: 20, level: 1 },
  { en: 'new', ja: '新しい', kana: 'あたらしい', freq: 33, level: 1 },
  { en: 'great', ja: '偉大な', kana: 'いだいな', freq: 66, level: 1 },
  { en: 'big', ja: '大きい', kana: 'おおきい', freq: 44, level: 1 },
  { en: 'small', ja: '小さい', kana: 'ちいさい', freq: 46, level: 1 },
  { en: 'long', ja: '長い', kana: 'ながい', freq: 56, level: 1 },
  { en: 'short', ja: '短い', kana: 'みじかい', freq: 59, level: 1 },
  { en: 'high', ja: '高い', kana: 'たかい', freq: 61, level: 1 },
  { en: 'low', ja: '低い', kana: 'ひくい', freq: 113, level: 1 },
  { en: 'old', ja: '古い', kana: 'ふるい', freq: 51, level: 1 },
  { en: 'young', ja: '若い', kana: 'わかい', freq: 63, level: 1 },
  { en: 'right', ja: '正しい', kana: 'ただしい', freq: 67, level: 1 },
  { en: 'wrong', ja: '誤った', kana: 'あやまった', freq: 133, level: 1 },
  { en: 'important', ja: '重要な', kana: 'じゅうような', freq: 69, level: 1 },
  { en: 'different', ja: '異なる', kana: 'ことなる', freq: 73, level: 1 },
  { en: 'same', ja: '同じ', kana: 'おなじ', freq: 49, level: 1 },
  { en: 'easy', ja: '簡単な', kana: 'かんたんな', freq: 77, level: 1 },
  { en: 'difficult', ja: '難しい', kana: 'むずかしい', freq: 83, level: 1 },
  { en: 'early', ja: '早い', kana: 'はやい', freq: 71, level: 1 },
  { en: 'late', ja: '遅い', kana: 'おそい', freq: 103, level: 1 },
  { en: 'strong', ja: '強い', kana: 'つよい', freq: 87, level: 1 },
  { en: 'weak', ja: '弱い', kana: 'よわい', freq: 141, level: 1 },
  { en: 'beautiful', ja: '美しい', kana: 'うつくしい', freq: 97, level: 1 },
  { en: 'famous', ja: '有名な', kana: 'ゆうめいな', freq: 151, level: 1 },
  { en: 'free', ja: '自由な', kana: 'じゆうな', freq: 123, level: 1 },

  // ==== 頻度ベース拡充（Issue #26・バッチ2） ====
  // 動詞
  { en: 'use', ja: '使う', kana: 'つかう', freq: 130, level: 1 },
  { en: 'try', ja: '試す', kana: 'ためす', freq: 205, level: 1 },
  { en: 'call', ja: '呼ぶ', kana: 'よぶ', freq: 162, level: 1 },
  { en: 'look', ja: '眺める', kana: 'ながめる', freq: 212, level: 1 },
  { en: 'need', ja: '要る', kana: 'いる', freq: 142, level: 1 },
  { en: 'want', ja: '望む', kana: 'のぞむ', freq: 152, level: 1 },
  { en: 'like', ja: '好む', kana: 'このむ', freq: 172, level: 1 },
  { en: 'move', ja: '動く', kana: 'うごく', freq: 182, level: 1 },
  { en: 'live', ja: '住む', kana: 'すむ', freq: 147, level: 1, theme: '日常' },
  { en: 'believe', ja: '信じる', kana: 'しんじる', freq: 222, level: 1 },
  { en: 'happen', ja: '起こる', kana: 'おこる', freq: 232, level: 1 },
  { en: 'buy', ja: '買う', kana: 'かう', freq: 166, level: 1, theme: '日常' },
  { en: 'sit', ja: '座る', kana: 'すわる', freq: 242, level: 1 },
  { en: 'stand', ja: '立つ', kana: 'たつ', freq: 236, level: 1 },
  { en: 'return', ja: '戻る', kana: 'もどる', freq: 252, level: 1 },
  { en: 'die', ja: '死ぬ', kana: 'しぬ', freq: 262, level: 1 },
  { en: 'remember', ja: '覚える', kana: 'おぼえる', freq: 246, level: 1 },
  { en: 'forget', ja: '忘れる', kana: 'わすれる', freq: 272, level: 1 },
  { en: 'change', ja: '変える', kana: 'かえる', freq: 176, level: 1 },
  { en: 'decrease', ja: '減る', kana: 'へる', freq: 282, level: 1 },
  { en: 'allow', ja: '許す', kana: 'ゆるす', freq: 292, level: 1 },
  { en: 'protect', ja: '守る', kana: 'まもる', freq: 302, level: 1 },
  { en: 'accept', ja: '受け入れる', kana: 'うけいれる', freq: 312, level: 1 },
  { en: 'refuse', ja: '断る', kana: 'ことわる', freq: 322, level: 1 },
  { en: 'compare', ja: '比べる', kana: 'くらべる', freq: 332, level: 1 },
  { en: 'introduce', ja: '紹介する', kana: 'しょうかいする', freq: 342, level: 1 },
  { en: 'save', ja: '救う', kana: 'すくう', freq: 306, level: 1 },
  { en: 'rise', ja: '昇る', kana: 'のぼる', freq: 316, level: 1 },
  { en: 'serve', ja: '仕える', kana: 'つかえる', freq: 352, level: 1 },
  { en: 'expect', ja: '予期する', kana: 'よきする', freq: 362, level: 1 },
  { en: 'offer', ja: '申し出る', kana: 'もうしでる', freq: 356, level: 1, theme: 'ビジネス' },
  { en: 'consider', ja: '考慮する', kana: 'こうりょする', freq: 372, level: 1 },
  { en: 'appear', ja: '現れる', kana: 'あらわれる', freq: 382, level: 1 },
  { en: 'imagine', ja: '想像する', kana: 'そうぞうする', freq: 392, level: 1 },
  { en: 'prevent', ja: '防ぐ', kana: 'ふせぐ', freq: 402, level: 1 },
  { en: 'continue', ja: '継続する', kana: 'けいぞくする', freq: 345, level: 1 },
  { en: 'provide', ja: '提供する', kana: 'ていきょうする', freq: 365, level: 1 },
  { en: 'speak', ja: '述べる', kana: 'のべる', freq: 348, level: 1 },
  // 名詞
  { en: 'week', ja: '週', kana: 'しゅう', freq: 132, level: 1 },
  { en: 'moment', ja: '瞬間', kana: 'しゅんかん', freq: 255, level: 1 },
  { en: 'room', ja: '部屋', kana: 'へや', freq: 161, level: 1, theme: '日常' },
  { en: 'door', ja: '扉', kana: 'とびら', freq: 201, level: 1, theme: '日常' },
  { en: 'window', ja: '窓', kana: 'まど', freq: 211, level: 1, theme: '日常' },
  { en: 'table', ja: '机', kana: 'つくえ', freq: 221, level: 1, theme: '日常' },
  { en: 'chair', ja: '椅子', kana: 'いす', freq: 231, level: 1, theme: '日常' },
  { en: 'wall', ja: '壁', kana: 'かべ', freq: 303, level: 1 },
  { en: 'floor', ja: '床', kana: 'ゆか', freq: 293, level: 1, theme: '日常' },
  { en: 'country', ja: '国', kana: 'くに', freq: 151, level: 1 },
  { en: 'government', ja: '政府', kana: 'せいふ', freq: 263, level: 1 },
  { en: 'law', ja: '法律', kana: 'ほうりつ', freq: 273, level: 1 },
  { en: 'police', ja: '警察', kana: 'けいさつ', freq: 283, level: 1, theme: '日常' },
  { en: 'art', ja: '芸術', kana: 'げいじゅつ', freq: 321, level: 1 },
  { en: 'science', ja: '科学', kana: 'かがく', freq: 311, level: 1 },
  { en: 'nature', ja: '自然', kana: 'しぜん', freq: 241, level: 1 },
  { en: 'field', ja: '分野', kana: 'ぶんや', freq: 331, level: 1 },
  { en: 'example', ja: '例', kana: 'れい', freq: 191, level: 1 },
  { en: 'question', ja: '質問', kana: 'しつもん', freq: 171, level: 1, theme: '日常' },
  { en: 'answer', ja: '答え', kana: 'こたえ', freq: 181, level: 1, theme: '日常' },
  { en: 'meaning', ja: '意味', kana: 'いみ', freq: 203, level: 1 },
  { en: 'point', ja: '要点', kana: 'ようてん', freq: 253, level: 1 },
  { en: 'side', ja: '側', kana: 'がわ', freq: 264, level: 1 },
  { en: 'center', ja: '中心', kana: 'ちゅうしん', freq: 274, level: 1 },
  { en: 'color', ja: '色', kana: 'いろ', freq: 167, level: 1, theme: '日常' },
  { en: 'sound', ja: '音', kana: 'おと', freq: 177, level: 1 },
  { en: 'light', ja: '光', kana: 'ひかり', freq: 187, level: 1 },
  { en: 'fire', ja: '炎', kana: 'ほのお', freq: 351, level: 1 },
  { en: 'wind', ja: '風', kana: 'かぜ', freq: 244, level: 1, theme: '日常' },
  { en: 'rain', ja: '雨', kana: 'あめ', freq: 224, level: 1, theme: '日常' },
  { en: 'snow', ja: '雪', kana: 'ゆき', freq: 234, level: 1, theme: '旅行' },
  { en: 'sky', ja: '空', kana: 'そら', freq: 214, level: 1, theme: '旅行' },
  { en: 'star', ja: '星', kana: 'ほし', freq: 284, level: 1, theme: '旅行' },
  { en: 'sun', ja: '太陽', kana: 'たいよう', freq: 254, level: 1 },
  { en: 'earth', ja: '地球', kana: 'ちきゅう', freq: 361, level: 1 },
  { en: 'tree', ja: '木', kana: 'き', freq: 173, level: 1 },
  { en: 'flower', ja: '花', kana: 'はな', freq: 178, level: 1, theme: '日常' },
  { en: 'animal', ja: '動物', kana: 'どうぶつ', freq: 204, level: 1, theme: '日常' },
  { en: 'bird', ja: '鳥', kana: 'とり', freq: 213, level: 1, theme: '日常' },
  { en: 'fish', ja: '魚', kana: 'さかな', freq: 163, level: 1, theme: '日常' },
  { en: 'meat', ja: '肉', kana: 'にく', freq: 168, level: 1, theme: '日常' },
  { en: 'rice', ja: '米', kana: 'こめ', freq: 174, level: 1, theme: '日常' },
  { en: 'tea', ja: '茶', kana: 'ちゃ', freq: 184, level: 1, theme: '日常' },
  { en: 'meal', ja: '食事', kana: 'しょくじ', freq: 194, level: 1, theme: '日常' },
  { en: 'vegetable', ja: '野菜', kana: 'やさい', freq: 206, level: 1, theme: '日常' },
  { en: 'milk', ja: '牛乳', kana: 'ぎゅうにゅう', freq: 216, level: 1, theme: '日常' },
  // 形容詞
  { en: 'sad', ja: '悲しい', kana: 'かなしい', freq: 202, level: 1 },
  { en: 'angry', ja: '怒った', kana: 'おこった', freq: 283, level: 1 },
  { en: 'tired', ja: '疲れた', kana: 'つかれた', freq: 243, level: 1, theme: '日常' },
  { en: 'nice', ja: '素敵な', kana: 'すてきな', freq: 193, level: 1 },
  { en: 'hot', ja: '暑い', kana: 'あつい', freq: 161, level: 1, theme: '日常' },
  { en: 'cold', ja: '寒い', kana: 'さむい', freq: 165, level: 1, theme: '日常' },
  { en: 'warm', ja: '暖かい', kana: 'あたたかい', freq: 233, level: 1, theme: '日常' },
  { en: 'cool', ja: '涼しい', kana: 'すずしい', freq: 245, level: 1, theme: '日常' },
  { en: 'heavy', ja: '重い', kana: 'おもい', freq: 223, level: 1 },
  { en: 'dark', ja: '暗い', kana: 'くらい', freq: 251, level: 1 },
  { en: 'bright', ja: '明るい', kana: 'あかるい', freq: 261, level: 1 },
  { en: 'quiet', ja: '静かな', kana: 'しずかな', freq: 271, level: 1 },
  { en: 'deep', ja: '深い', kana: 'ふかい', freq: 235, level: 1 },
  { en: 'wide', ja: '広い', kana: 'ひろい', freq: 207, level: 1 },
  { en: 'narrow', ja: '狭い', kana: 'せまい', freq: 291, level: 1 },
  { en: 'thin', ja: '薄い', kana: 'うすい', freq: 301, level: 1 },
  { en: 'dirty', ja: '汚い', kana: 'きたない', freq: 281, level: 1, theme: '日常' },
  { en: 'safe', ja: '安全な', kana: 'あんぜんな', freq: 248, level: 1, theme: '旅行' },
  { en: 'dangerous', ja: '危険な', kana: 'きけんな', freq: 257, level: 1 },
  { en: 'real', ja: '本当の', kana: 'ほんとうの', freq: 183, level: 1 },
  { en: 'main', ja: '主な', kana: 'おもな', freq: 275, level: 1 },
  { en: 'rich', ja: '豊かな', kana: 'ゆたかな', freq: 323, level: 1 },
  { en: 'poor', ja: '貧しい', kana: 'まずしい', freq: 333, level: 1 },
  { en: 'hungry', ja: '空腹の', kana: 'くうふくの', freq: 265, level: 1, theme: '日常' },
  { en: 'ready', ja: '用意できた', kana: 'よういできた', freq: 363, level: 1, theme: 'ビジネス' },
  // やや低頻度（L2: 1,001–2,000帯を埋め始める）
  { en: 'design', ja: '設計する', kana: 'せっけいする', freq: 1050, level: 2, theme: 'ビジネス' },
  { en: 'describe', ja: '描写する', kana: 'びょうしゃする', freq: 1100, level: 2 },
  { en: 'affect', ja: '影響する', kana: 'えいきょうする', freq: 1080, level: 2 },
  { en: 'cause', ja: '引き起こす', kana: 'ひきおこす', freq: 1120, level: 2 },
  { en: 'recognize', ja: '認識する', kana: 'にんしきする', freq: 1150, level: 2 },
  { en: 'discover', ja: '見いだす', kana: 'みいだす', freq: 1200, level: 2 },
  { en: 'realize', ja: '悟る', kana: 'さとる', freq: 1180, level: 2 },
  { en: 'clear', ja: '明確な', kana: 'めいかくな', freq: 1055, level: 2 },
  { en: 'simple', ja: '単純な', kana: 'たんじゅんな', freq: 1020, level: 2 },
  { en: 'complex', ja: '複雑な', kana: 'ふくざつな', freq: 1105, level: 2 },
  { en: 'common', ja: '一般的な', kana: 'いっぱんてきな', freq: 1060, level: 2 },
  { en: 'special', ja: '特別な', kana: 'とくべつな', freq: 1040, level: 2 },
  { en: 'true', ja: '真実の', kana: 'しんじつの', freq: 1030, level: 2 },
  { en: 'final', ja: '最終の', kana: 'さいしゅうの', freq: 1090, level: 2 },
  { en: 'possible', ja: '可能な', kana: 'かのうな', freq: 1070, level: 2 },
  { en: 'popular', ja: '人気の', kana: 'にんきの', freq: 1110, level: 2 },
  { en: 'effect', ja: '効果', kana: 'こうか', freq: 1085, level: 2 },

  // ==== 頻度ベース拡充（Issue #26・バッチ3） ====
  // 動詞
  { en: 'drink', ja: '飲む', kana: 'のむ', freq: 155, level: 1, theme: '日常' },
  { en: 'cook', ja: '料理する', kana: 'りょうりする', freq: 232, level: 1, theme: '日常' },
  { en: 'sleep', ja: '眠る', kana: 'ねむる', freq: 202, level: 1, theme: '日常' },
  { en: 'wake', ja: '起きる', kana: 'おきる', freq: 212, level: 1, theme: '日常' },
  { en: 'open', ja: '開ける', kana: 'あける', freq: 166, level: 1 },
  { en: 'close', ja: '閉める', kana: 'しめる', freq: 176, level: 1 },
  { en: 'start', ja: '開始する', kana: 'かいしする', freq: 186, level: 1 },
  { en: 'finish', ja: '終える', kana: 'おえる', freq: 196, level: 1 },
  { en: 'wash', ja: '洗う', kana: 'あらう', freq: 242, level: 1, theme: '日常' },
  { en: 'wear', ja: '身につける', kana: 'みにつける', freq: 252, level: 1, theme: '日常' },
  { en: 'throw', ja: '投げる', kana: 'なげる', freq: 262, level: 1 },
  { en: 'push', ja: '押す', kana: 'おす', freq: 222, level: 1 },
  { en: 'pull', ja: '引く', kana: 'ひく', freq: 226, level: 1 },
  { en: 'jump', ja: '跳ぶ', kana: 'とぶ', freq: 272, level: 1 },
  { en: 'swim', ja: '泳ぐ', kana: 'およぐ', freq: 237, level: 1, theme: '旅行' },
  { en: 'dance', ja: '踊る', kana: 'おどる', freq: 282, level: 1 },
  { en: 'paint', ja: '塗る', kana: 'ぬる', freq: 292, level: 1 },
  { en: 'count', ja: '数える', kana: 'かぞえる', freq: 247, level: 1 },
  { en: 'measure', ja: '測る', kana: 'はかる', freq: 302, level: 1 },
  { en: 'check', ja: '確認する', kana: 'かくにんする', freq: 217, level: 1, theme: 'ビジネス' },
  { en: 'fight', ja: '戦う', kana: 'たたかう', freq: 312, level: 1 },
  { en: 'share', ja: '分ける', kana: 'わける', freq: 257, level: 1 },
  { en: 'join', ja: '加わる', kana: 'くわわる', freq: 322, level: 1 },
  { en: 'visit', ja: '訪れる', kana: 'おとずれる', freq: 207, level: 1, theme: '旅行' },
  { en: 'stay', ja: '滞在する', kana: 'たいざいする', freq: 233, level: 1, theme: '旅行' },
  { en: 'receive', ja: '受け取る', kana: 'うけとる', freq: 243, level: 1, theme: 'ビジネス' },
  { en: 'earn', ja: '稼ぐ', kana: 'かせぐ', freq: 332, level: 1, theme: 'ビジネス' },
  { en: 'lend', ja: '貸す', kana: 'かす', freq: 342, level: 1 },
  { en: 'fix', ja: '直す', kana: 'なおす', freq: 252, level: 1 },
  { en: 'plant', ja: '植える', kana: 'うえる', freq: 352, level: 1 },
  { en: 'drive', ja: '運転する', kana: 'うんてんする', freq: 222, level: 1, theme: '旅行' },
  { en: 'spend', ja: '費やす', kana: 'ついやす', freq: 238, level: 1 },
  { en: 'draw', ja: '描く', kana: 'えがく', freq: 262, level: 1 },
  // 名詞
  { en: 'job', ja: '職業', kana: 'しょくぎょう', freq: 182, level: 1, theme: 'ビジネス' },
  { en: 'team', ja: '組', kana: 'くみ', freq: 272, level: 1, theme: 'ビジネス' },
  { en: 'member', ja: '一員', kana: 'いちいん', freq: 282, level: 1 },
  { en: 'minute', ja: '分', kana: 'ふん', freq: 192, level: 1 },
  { en: 'evening', ja: '夕方', kana: 'ゆうがた', freq: 202, level: 1, theme: '日常' },
  { en: 'afternoon', ja: '午後', kana: 'ごご', freq: 212, level: 1, theme: '日常' },
  { en: 'noon', ja: '正午', kana: 'しょうご', freq: 322, level: 1 },
  { en: 'season', ja: '季節', kana: 'きせつ', freq: 232, level: 1 },
  { en: 'spring', ja: '春', kana: 'はる', freq: 242, level: 1 },
  { en: 'summer', ja: '夏', kana: 'なつ', freq: 237, level: 1 },
  { en: 'autumn', ja: '秋', kana: 'あき', freq: 247, level: 1 },
  { en: 'winter', ja: '冬', kana: 'ふゆ', freq: 252, level: 1 },
  { en: 'birthday', ja: '誕生日', kana: 'たんじょうび', freq: 292, level: 1, theme: '日常' },
  { en: 'holiday', ja: '休日', kana: 'きゅうじつ', freq: 262, level: 1, theme: '日常' },
  { en: 'party', ja: '宴会', kana: 'えんかい', freq: 302, level: 1 },
  { en: 'gift', ja: '贈り物', kana: 'おくりもの', freq: 272, level: 1 },
  { en: 'box', ja: '箱', kana: 'はこ', freq: 222, level: 1 },
  { en: 'bottle', ja: '瓶', kana: 'びん', freq: 312, level: 1 },
  { en: 'clock', ja: '時計', kana: 'とけい', freq: 232, level: 1, theme: '日常' },
  { en: 'watch', ja: '腕時計', kana: 'うでどけい', freq: 332, level: 1, theme: '日常' },
  { en: 'key', ja: '鍵', kana: 'かぎ', freq: 202, level: 1, theme: '日常' },
  { en: 'bank', ja: '銀行', kana: 'ぎんこう', freq: 212, level: 1, theme: '旅行' },
  { en: 'store', ja: '商店', kana: 'しょうてん', freq: 252, level: 1 },
  { en: 'restaurant', ja: '食堂', kana: 'しょくどう', freq: 222, level: 1, theme: '旅行' },
  { en: 'hospital', ja: '病院', kana: 'びょういん', freq: 217, level: 1, theme: '日常' },
  { en: 'doctor', ja: '医者', kana: 'いしゃ', freq: 207, level: 1, theme: '日常' },
  { en: 'bus', ja: 'バス', kana: 'ばす', freq: 197, level: 1, theme: '旅行' },
  { en: 'bike', ja: '自転車', kana: 'じてんしゃ', freq: 252, level: 1, theme: '日常' },
  { en: 'plane', ja: '飛行機', kana: 'ひこうき', freq: 212, level: 1, theme: '旅行' },
  { en: 'park', ja: '公園', kana: 'こうえん', freq: 202, level: 1, theme: '日常' },
  { en: 'library', ja: '図書館', kana: 'としょかん', freq: 262, level: 1 },
  { en: 'museum', ja: '博物館', kana: 'はくぶつかん', freq: 322, level: 1, theme: '旅行' },
  { en: 'building', ja: '建物', kana: 'たてもの', freq: 242, level: 1 },
  { en: 'farm', ja: '農場', kana: 'のうじょう', freq: 342, level: 1 },
  { en: 'village', ja: '村', kana: 'むら', freq: 282, level: 1, theme: '旅行' },
  { en: 'lake', ja: '湖', kana: 'みずうみ', freq: 292, level: 1, theme: '旅行' },
  { en: 'island', ja: '島', kana: 'しま', freq: 272, level: 1, theme: '旅行' },
  { en: 'hill', ja: '丘', kana: 'おか', freq: 312, level: 1 },
  { en: 'cloud', ja: '雲', kana: 'くも', freq: 252, level: 1 },
  { en: 'storm', ja: '嵐', kana: 'あらし', freq: 352, level: 1 },
  { en: 'eye', ja: '目', kana: 'め', freq: 152, level: 1, theme: '日常' },
  { en: 'ear', ja: '耳', kana: 'みみ', freq: 232, level: 1, theme: '日常' },
  { en: 'mouth', ja: '口', kana: 'くち', freq: 202, level: 1, theme: '日常' },
  { en: 'tooth', ja: '歯', kana: 'は', freq: 242, level: 1, theme: '日常' },
  { en: 'arm', ja: '腕', kana: 'うで', freq: 222, level: 1, theme: '日常' },
  { en: 'leg', ja: '脚', kana: 'あし', freq: 227, level: 1, theme: '日常' },
  { en: 'finger', ja: '指', kana: 'ゆび', freq: 262, level: 1, theme: '日常' },
  { en: 'heart', ja: '心臓', kana: 'しんぞう', freq: 272, level: 1 },
  { en: 'voice', ja: '声', kana: 'こえ', freq: 212, level: 1 },
  { en: 'language', ja: '言語', kana: 'げんご', freq: 242, level: 1 },
  { en: 'sentence', ja: '文', kana: 'ぶん', freq: 292, level: 1 },
  { en: 'cost', ja: '費用', kana: 'ひよう', freq: 252, level: 1, theme: 'ビジネス' },
  { en: 'tax', ja: '税金', kana: 'ぜいきん', freq: 312, level: 1, theme: 'ビジネス' },
  { en: 'fee', ja: '料金', kana: 'りょうきん', freq: 282, level: 1, theme: '旅行' },
  { en: 'factory', ja: '工場', kana: 'こうじょう', freq: 302, level: 1, theme: 'ビジネス' },
  { en: 'machine', ja: '機械', kana: 'きかい', freq: 262, level: 1 },
  { en: 'tool', ja: '道具', kana: 'どうぐ', freq: 282, level: 1 },
  { en: 'game', ja: '試合', kana: 'しあい', freq: 202, level: 1 },
  { en: 'song', ja: '歌', kana: 'うた', freq: 212, level: 1, theme: '日常' },
  { en: 'picture', ja: '絵', kana: 'え', freq: 222, level: 1, theme: '日常' },
  { en: 'photo', ja: '写真', kana: 'しゃしん', freq: 232, level: 1, theme: '日常' },
  // 形容詞
  { en: 'afraid', ja: '怖い', kana: 'こわい', freq: 252, level: 1 },
  { en: 'glad', ja: '嬉しい', kana: 'うれしい', freq: 242, level: 1 },
  { en: 'proud', ja: '誇らしい', kana: 'ほこらしい', freq: 352, level: 1 },
  { en: 'surprised', ja: '驚いた', kana: 'おどろいた', freq: 322, level: 1 },
  { en: 'careful', ja: '慎重な', kana: 'しんちょうな', freq: 302, level: 1 },
  { en: 'clever', ja: '賢い', kana: 'かしこい', freq: 332, level: 1 },
  { en: 'honest', ja: '正直な', kana: 'しょうじきな', freq: 342, level: 1 },
  { en: 'gentle', ja: '優しい', kana: 'やさしい', freq: 262, level: 1 },
  { en: 'brave', ja: '勇敢な', kana: 'ゆうかんな', freq: 362, level: 1 },
  { en: 'calm', ja: '穏やかな', kana: 'おだやかな', freq: 352, level: 1 },
  { en: 'serious', ja: '真剣な', kana: 'しんけんな', freq: 312, level: 1 },
  { en: 'funny', ja: '面白い', kana: 'おもしろい', freq: 232, level: 1 },
  { en: 'soft', ja: '柔らかい', kana: 'やわらかい', freq: 272, level: 1 },
  { en: 'hard', ja: '硬い', kana: 'かたい', freq: 252, level: 1 },
  { en: 'sharp', ja: '鋭い', kana: 'するどい', freq: 342, level: 1 },
  { en: 'round', ja: '丸い', kana: 'まるい', freq: 262, level: 1 },
  { en: 'straight', ja: 'まっすぐな', kana: 'まっすぐな', freq: 322, level: 1 },
  { en: 'full', ja: '満ちた', kana: 'みちた', freq: 282, level: 1 },
  { en: 'empty', ja: '空の', kana: 'からの', freq: 292, level: 1 },
  { en: 'fresh', ja: '新鮮な', kana: 'しんせんな', freq: 302, level: 1, theme: '日常' },
  { en: 'delicious', ja: '美味しい', kana: 'おいしい', freq: 242, level: 1, theme: '日常' },
  { en: 'sweet', ja: '甘い', kana: 'あまい', freq: 232, level: 1, theme: '日常' },
  { en: 'sour', ja: '酸っぱい', kana: 'すっぱい', freq: 352, level: 1, theme: '日常' },
  { en: 'bitter', ja: '苦い', kana: 'にがい', freq: 332, level: 1, theme: '日常' },
  { en: 'cheap', ja: '安い', kana: 'やすい', freq: 222, level: 1, theme: 'ビジネス' },

  // ==== 頻度ベース拡充（Issue #26・バッチ4） ====
  // 動詞・身近な名詞・副詞（L1）
  { en: 'end', ja: '終わる', kana: 'おわる', freq: 305, level: 1 },
  { en: 'add', ja: '加える', kana: 'くわえる', freq: 315, level: 1 },
  { en: 'learn', ja: '学ぶ', kana: 'まなぶ', freq: 280, level: 1 },
  { en: 'mean', ja: '意味する', kana: 'いみする', freq: 320, level: 1 },
  { en: 'repeat', ja: '繰り返す', kana: 'くりかえす', freq: 330, level: 1 },
  { en: 'raise', ja: '上げる', kana: 'あげる', freq: 290, level: 1 },
  { en: 'lower', ja: '下げる', kana: 'さげる', freq: 340, level: 1 },
  { en: 'remove', ja: '取り除く', kana: 'とりのぞく', freq: 350, level: 1 },
  { en: 'collect', ja: '集める', kana: 'あつめる', freq: 310, level: 1 },
  { en: 'gather', ja: '集まる', kana: 'あつまる', freq: 360, level: 1 },
  { en: 'mix', ja: '混ぜる', kana: 'まぜる', freq: 370, level: 1 },
  { en: 'connect', ja: 'つなぐ', kana: 'つなぐ', freq: 320, level: 1 },
  { en: 'follow', ja: '従う', kana: 'したがう', freq: 300, level: 1 },
  { en: 'lead', ja: '導く', kana: 'みちびく', freq: 332, level: 1 },
  { en: 'doubt', ja: '疑う', kana: 'うたがう', freq: 380, level: 1 },
  { en: 'guess', ja: '推測する', kana: 'すいそくする', freq: 390, level: 1 },
  { en: 'shoe', ja: '靴', kana: 'くつ', freq: 252, level: 1, theme: '日常' },
  { en: 'hat', ja: '帽子', kana: 'ぼうし', freq: 272, level: 1, theme: '日常' },
  { en: 'coat', ja: '上着', kana: 'うわぎ', freq: 292, level: 1, theme: '日常' },
  { en: 'ring', ja: '指輪', kana: 'ゆびわ', freq: 362, level: 1 },
  { en: 'clothes', ja: '衣服', kana: 'いふく', freq: 282, level: 1, theme: '日常' },
  { en: 'cloth', ja: '布', kana: 'ぬの', freq: 382, level: 1 },
  { en: 'plate', ja: '皿', kana: 'さら', freq: 302, level: 1, theme: '日常' },
  { en: 'pot', ja: '鍋', kana: 'なべ', freq: 352, level: 1, theme: '日常' },
  { en: 'soap', ja: '石鹸', kana: 'せっけん', freq: 372, level: 1, theme: '日常' },
  { en: 'mirror', ja: '鏡', kana: 'かがみ', freq: 342, level: 1, theme: '日常' },
  { en: 'candle', ja: 'ろうそく', kana: 'ろうそく', freq: 402, level: 1 },
  { en: 'lamp', ja: '電灯', kana: 'でんとう', freq: 362, level: 1, theme: '日常' },
  { en: 'knife', ja: '包丁', kana: 'ほうちょう', freq: 352, level: 1, theme: '日常' },
  { en: 'bell', ja: '鈴', kana: 'すず', freq: 382, level: 1 },
  { en: 'gate', ja: '門', kana: 'もん', freq: 322, level: 1 },
  { en: 'shape', ja: '形', kana: 'かたち', freq: 302, level: 1 },
  { en: 'size', ja: '大きさ', kana: 'おおきさ', freq: 292, level: 1 },
  { en: 'weight', ja: '重さ', kana: 'おもさ', freq: 332, level: 1 },
  { en: 'length', ja: '長さ', kana: 'ながさ', freq: 352, level: 1 },
  { en: 'speed', ja: '速さ', kana: 'はやさ', freq: 312, level: 1 },
  { en: 'amount', ja: '量', kana: 'りょう', freq: 342, level: 1 },
  { en: 'taste', ja: '味', kana: 'あじ', freq: 282, level: 1, theme: '日常' },
  { en: 'smell', ja: '匂い', kana: 'におい', freq: 362, level: 1, theme: '日常' },
  { en: 'dream', ja: '夢', kana: 'ゆめ', freq: 272, level: 1 },
  { en: 'hope', ja: '希望', kana: 'きぼう', freq: 292, level: 1 },
  { en: 'fear', ja: '恐れ', kana: 'おそれ', freq: 352, level: 1 },
  { en: 'pain', ja: '痛み', kana: 'いたみ', freq: 322, level: 1, theme: '日常' },
  { en: 'medicine', ja: '薬', kana: 'くすり', freq: 282, level: 1, theme: '日常' },
  { en: 'illness', ja: '病気', kana: 'びょうき', freq: 292, level: 1, theme: '日常' },
  { en: 'address', ja: '住所', kana: 'じゅうしょ', freq: 302, level: 1, theme: '旅行' },
  { en: 'list', ja: '一覧', kana: 'いちらん', freq: 332, level: 1, theme: 'ビジネス' },
  { en: 'note', ja: '覚え書き', kana: 'おぼえがき', freq: 382, level: 1 },
  { en: 'message', ja: '伝言', kana: 'でんごん', freq: 322, level: 1, theme: '日常' },
  { en: 'always', ja: 'いつも', kana: 'いつも', freq: 262, level: 1 },
  { en: 'often', ja: 'しばしば', kana: 'しばしば', freq: 322, level: 1 },
  { en: 'sometimes', ja: '時々', kana: 'ときどき', freq: 282, level: 1 },
  { en: 'usually', ja: '普段', kana: 'ふだん', freq: 302, level: 1 },
  { en: 'already', ja: 'すでに', kana: 'すでに', freq: 292, level: 1 },
  { en: 'soon', ja: 'まもなく', kana: 'まもなく', freq: 312, level: 1 },
  { en: 'never', ja: '決して', kana: 'けっして', freq: 352, level: 1 },
  { en: 'maybe', ja: 'たぶん', kana: 'たぶん', freq: 372, level: 1 },
  // 抽象語・ビジネス語（L2: 1,001–2,000帯）
  { en: 'news', ja: '報道', kana: 'ほうどう', freq: 1200, level: 2 },
  { en: 'information', ja: '情報', kana: 'じょうほう', freq: 1050, level: 2 },
  { en: 'knowledge', ja: '知識', kana: 'ちしき', freq: 1100, level: 2 },
  { en: 'experience', ja: '経験', kana: 'けいけん', freq: 1080, level: 2 },
  { en: 'skill', ja: '技能', kana: 'ぎのう', freq: 1150, level: 2 },
  { en: 'ability', ja: '能力', kana: 'のうりょく', freq: 1120, level: 2 },
  { en: 'effort', ja: '努力', kana: 'どりょく', freq: 1160, level: 2 },
  { en: 'success', ja: '成功', kana: 'せいこう', freq: 1090, level: 2 },
  { en: 'failure', ja: '失敗', kana: 'しっぱい', freq: 1170, level: 2 },
  { en: 'chance', ja: '好機', kana: 'こうき', freq: 1180, level: 2 },
  { en: 'choice', ja: '選択', kana: 'せんたく', freq: 1110, level: 2 },
  { en: 'decision', ja: '決定', kana: 'けってい', freq: 1130, level: 2 },
  { en: 'goal', ja: '目標', kana: 'もくひょう', freq: 1140, level: 2, theme: 'ビジネス' },
  { en: 'purpose', ja: '目的', kana: 'もくてき', freq: 1125, level: 2 },
  { en: 'solution', ja: '解決', kana: 'かいけつ', freq: 1190, level: 2 },
  { en: 'method', ja: '手法', kana: 'しゅほう', freq: 1210, level: 2 },
  { en: 'system', ja: '仕組み', kana: 'しくみ', freq: 1100, level: 2 },
  { en: 'rule', ja: '規則', kana: 'きそく', freq: 1155, level: 2 },
  { en: 'opinion', ja: '意見', kana: 'いけん', freq: 1085, level: 2 },
  { en: 'thought', ja: '思考', kana: 'しこう', freq: 1220, level: 2 },
  { en: 'memory', ja: '記憶', kana: 'きおく', freq: 1175, level: 2 },
  { en: 'feeling', ja: '感情', kana: 'かんじょう', freq: 1145, level: 2 },
  { en: 'joy', ja: '喜び', kana: 'よろこび', freq: 1230, level: 2 },
  { en: 'anger', ja: '怒り', kana: 'いかり', freq: 1240, level: 2 },
  { en: 'sight', ja: '光景', kana: 'こうけい', freq: 1250, level: 2 },
  { en: 'wealth', ja: '富', kana: 'とみ', freq: 1300, level: 2 },
  { en: 'loss', ja: '損失', kana: 'そんしつ', freq: 1260, level: 2, theme: 'ビジネス' },
  { en: 'trade', ja: '貿易', kana: 'ぼうえき', freq: 1270, level: 2, theme: 'ビジネス' },
  { en: 'product', ja: '製品', kana: 'せいひん', freq: 1160, level: 2, theme: 'ビジネス' },
  { en: 'service', ja: '奉仕', kana: 'ほうし', freq: 1280, level: 2 },
  { en: 'industry', ja: '産業', kana: 'さんぎょう', freq: 1225, level: 2, theme: 'ビジネス' },
  { en: 'worker', ja: '労働者', kana: 'ろうどうしゃ', freq: 1235, level: 2, theme: 'ビジネス' },
  { en: 'staff', ja: '職員', kana: 'しょくいん', freq: 1245, level: 2, theme: 'ビジネス' },
  { en: 'data', ja: '資料', kana: 'しりょう', freq: 1185, level: 2, theme: 'ビジネス' },
  { en: 'file', ja: '書類', kana: 'しょるい', freq: 1290, level: 2, theme: 'ビジネス' },
  { en: 'produce', ja: '生産する', kana: 'せいさんする', freq: 1205, level: 2, theme: 'ビジネス' },
  { en: 'destroy', ja: '破壊する', kana: 'はかいする', freq: 1310, level: 2 },
  { en: 'attack', ja: '攻撃する', kana: 'こうげきする', freq: 1320, level: 2 },
  { en: 'defend', ja: '防御する', kana: 'ぼうぎょする', freq: 1330, level: 2 },
  { en: 'gain', ja: '獲得する', kana: 'かくとくする', freq: 1340, level: 2 },
  { en: 'spread', ja: '広げる', kana: 'ひろげる', freq: 1255, level: 2 },
  { en: 'divide', ja: '分割する', kana: 'ぶんかつする', freq: 1350, level: 2 },
  { en: 'separate', ja: '引き離す', kana: 'ひきはなす', freq: 1360, level: 2 },
  { en: 'control', ja: '制御する', kana: 'せいぎょする', freq: 1215, level: 2 },
  { en: 'command', ja: '命じる', kana: 'めいじる', freq: 1370, level: 2 },
  { en: 'forbid', ja: '禁じる', kana: 'きんじる', freq: 1380, level: 2 },
  { en: 'permit', ja: '許可する', kana: 'きょかする', freq: 1295, level: 2 },
  { en: 'judge', ja: '判断する', kana: 'はんだんする', freq: 1235, level: 2 },
  { en: 'suppose', ja: '仮定する', kana: 'かていする', freq: 1390, level: 2 },
  { en: 'trust', ja: '信頼する', kana: 'しんらいする', freq: 1245, level: 2 },
  { en: 'express', ja: '表現する', kana: 'ひょうげんする', freq: 1265, level: 2 },
  { en: 'discuss', ja: '議論する', kana: 'ぎろんする', freq: 1275, level: 2, theme: 'ビジネス' },
  { en: 'argue', ja: '言い争う', kana: 'いいあらそう', freq: 1400, level: 2 },
  { en: 'disagree', ja: '反対する', kana: 'はんたいする', freq: 1285, level: 2 },
  { en: 'suggest', ja: '提案する', kana: 'ていあんする', freq: 1195, level: 2, theme: 'ビジネス' },
  { en: 'announce', ja: '発表する', kana: 'はっぴょうする', freq: 1305, level: 2 },
  { en: 'mention', ja: '言及する', kana: 'げんきゅうする', freq: 1410, level: 2 },
  { en: 'replace', ja: '置き換える', kana: 'おきかえる', freq: 1325, level: 2 },
  { en: 'suddenly', ja: '突然', kana: 'とつぜん', freq: 1055, level: 2 },
  { en: 'perhaps', ja: '恐らく', kana: 'おそらく', freq: 1115, level: 2 },

  // ==== 頻度ベース拡充（Issue #26・バッチ5） ====
  // 身近な名詞（L1）
  { en: 'baby', ja: '赤ちゃん', kana: 'あかちゃん', freq: 280, level: 1, theme: '日常' },
  { en: 'husband', ja: '夫', kana: 'おっと', freq: 300, level: 1, theme: '日常' },
  { en: 'wife', ja: '妻', kana: 'つま', freq: 305, level: 1, theme: '日常' },
  { en: 'son', ja: '息子', kana: 'むすこ', freq: 290, level: 1, theme: '日常' },
  { en: 'daughter', ja: '娘', kana: 'むすめ', freq: 295, level: 1, theme: '日常' },
  { en: 'brother', ja: '兄', kana: 'あに', freq: 270, level: 1, theme: '日常' },
  { en: 'sister', ja: '姉', kana: 'あね', freq: 275, level: 1, theme: '日常' },
  { en: 'guest', ja: '客', kana: 'きゃく', freq: 350, level: 1 },
  { en: 'king', ja: '王', kana: 'おう', freq: 360, level: 1 },
  { en: 'queen', ja: '女王', kana: 'じょおう', freq: 380, level: 1 },
  { en: 'ground', ja: '地面', kana: 'じめん', freq: 340, level: 1 },
  { en: 'stone', ja: '石', kana: 'いし', freq: 322, level: 1 },
  { en: 'rock', ja: '岩', kana: 'いわ', freq: 362, level: 1 },
  { en: 'sand', ja: '砂', kana: 'すな', freq: 352, level: 1, theme: '旅行' },
  { en: 'ice', ja: '氷', kana: 'こおり', freq: 332, level: 1, theme: '日常' },
  { en: 'gold', ja: '金', kana: 'きん', freq: 342, level: 1 },
  { en: 'iron', ja: '鉄', kana: 'てつ', freq: 382, level: 1 },
  { en: 'oil', ja: '油', kana: 'あぶら', freq: 352, level: 1, theme: '日常' },
  { en: 'smoke', ja: '煙', kana: 'けむり', freq: 372, level: 1 },
  { en: 'wave', ja: '波', kana: 'なみ', freq: 342, level: 1, theme: '旅行' },
  { en: 'coast', ja: '海岸', kana: 'かいがん', freq: 362, level: 1, theme: '旅行' },
  { en: 'port', ja: '港', kana: 'みなと', freq: 352, level: 1, theme: '旅行' },
  { en: 'travel', ja: '旅行', kana: 'りょこう', freq: 300, level: 1, theme: '旅行' },
  { en: 'flight', ja: '飛行', kana: 'ひこう', freq: 360, level: 1, theme: '旅行' },
  { en: 'path', ja: '小道', kana: 'こみち', freq: 382, level: 1 },
  { en: 'ceiling', ja: '天井', kana: 'てんじょう', freq: 402, level: 1 },
  { en: 'stairs', ja: '階段', kana: 'かいだん', freq: 362, level: 1, theme: '日常' },
  { en: 'neck', ja: '首', kana: 'くび', freq: 322, level: 1, theme: '日常' },
  { en: 'shoulder', ja: '肩', kana: 'かた', freq: 342, level: 1, theme: '日常' },
  { en: 'knee', ja: '膝', kana: 'ひざ', freq: 382, level: 1, theme: '日常' },
  { en: 'chest', ja: '胸', kana: 'むね', freq: 362, level: 1, theme: '日常' },
  { en: 'back', ja: '背中', kana: 'せなか', freq: 332, level: 1, theme: '日常' },
  { en: 'breath', ja: '息', kana: 'いき', freq: 352, level: 1 },
  { en: 'skin', ja: '肌', kana: 'はだ', freq: 322, level: 1, theme: '日常' },
  { en: 'bone', ja: '骨', kana: 'ほね', freq: 342, level: 1, theme: '日常' },
  { en: 'blood', ja: '血', kana: 'ち', freq: 332, level: 1 },
  { en: 'peace', ja: '平和', kana: 'へいわ', freq: 342, level: 1 },
  { en: 'war', ja: '戦争', kana: 'せんそう', freq: 324, level: 1 },
  { en: 'gun', ja: '銃', kana: 'じゅう', freq: 382, level: 1 },
  { en: 'enemy', ja: '敵', kana: 'てき', freq: 352, level: 1 },
  // 抽象・社会・ビジネス語（L2: 1,001–2,000）
  { en: 'culture', ja: '文化', kana: 'ぶんか', freq: 1050, level: 2 },
  { en: 'society', ja: '社会', kana: 'しゃかい', freq: 1040, level: 2 },
  { en: 'economy', ja: '経済', kana: 'けいざい', freq: 1080, level: 2, theme: 'ビジネス' },
  { en: 'politics', ja: '政治', kana: 'せいじ', freq: 1100, level: 2 },
  { en: 'religion', ja: '宗教', kana: 'しゅうきょう', freq: 1200, level: 2 },
  { en: 'education', ja: '教育', kana: 'きょういく', freq: 1060, level: 2 },
  { en: 'research', ja: '研究', kana: 'けんきゅう', freq: 1090, level: 2 },
  { en: 'theory', ja: '理論', kana: 'りろん', freq: 1180, level: 2 },
  { en: 'evidence', ja: '証拠', kana: 'しょうこ', freq: 1190, level: 2 },
  { en: 'influence', ja: '影響', kana: 'えいきょう', freq: 1110, level: 2 },
  { en: 'benefit', ja: '恩恵', kana: 'おんけい', freq: 1160, level: 2, theme: 'ビジネス' },
  { en: 'advantage', ja: '利点', kana: 'りてん', freq: 1170, level: 2 },
  { en: 'quality', ja: '品質', kana: 'ひんしつ', freq: 1120, level: 2, theme: 'ビジネス' },
  { en: 'quantity', ja: '数量', kana: 'すうりょう', freq: 1250, level: 2 },
  { en: 'standard', ja: '基準', kana: 'きじゅん', freq: 1140, level: 2, theme: 'ビジネス' },
  { en: 'degree', ja: '程度', kana: 'ていど', freq: 1150, level: 2 },
  { en: 'rate', ja: '割合', kana: 'わりあい', freq: 1130, level: 2 },
  { en: 'total', ja: '合計', kana: 'ごうけい', freq: 1210, level: 2, theme: 'ビジネス' },
  { en: 'income', ja: '収入', kana: 'しゅうにゅう', freq: 1180, level: 2, theme: 'ビジネス' },
  { en: 'expense', ja: '支出', kana: 'ししゅつ', freq: 1260, level: 2, theme: 'ビジネス' },
  { en: 'investment', ja: '投資', kana: 'とうし', freq: 1170, level: 2, theme: 'ビジネス' },
  { en: 'debt', ja: '借金', kana: 'しゃっきん', freq: 1280, level: 2, theme: 'ビジネス' },
  { en: 'account', ja: '口座', kana: 'こうざ', freq: 1220, level: 2, theme: 'ビジネス' },
  { en: 'cash', ja: '現金', kana: 'げんきん', freq: 1160, level: 2, theme: '旅行' },
  { en: 'credit', ja: '信用', kana: 'しんよう', freq: 1290, level: 2, theme: 'ビジネス' },
  { en: 'export', ja: '輸出', kana: 'ゆしゅつ', freq: 1300, level: 2, theme: 'ビジネス' },
  { en: 'import', ja: '輸入', kana: 'ゆにゅう', freq: 1310, level: 2, theme: 'ビジネス' },
  { en: 'material', ja: '材料', kana: 'ざいりょう', freq: 1190, level: 2 },
  { en: 'resource', ja: '資源', kana: 'しげん', freq: 1240, level: 2, theme: 'ビジネス' },
  { en: 'progress', ja: '進歩', kana: 'しんぽ', freq: 1200, level: 2 },
  { en: 'growth', ja: '成長', kana: 'せいちょう', freq: 1130, level: 2, theme: 'ビジネス' },
  { en: 'development', ja: '発展', kana: 'はってん', freq: 1140, level: 2, theme: 'ビジネス' },
  { en: 'process', ja: '過程', kana: 'かてい', freq: 1150, level: 2 },
  { en: 'structure', ja: '構造', kana: 'こうぞう', freq: 1230, level: 2 },
  { en: 'function', ja: '機能', kana: 'きのう', freq: 1210, level: 2 },
  { en: 'pattern', ja: '模様', kana: 'もよう', freq: 1320, level: 2 },
  { en: 'type', ja: '種類', kana: 'しゅるい', freq: 1100, level: 2 },
  { en: 'form', ja: '形式', kana: 'けいしき', freq: 1240, level: 2 },
  { en: 'duty', ja: '義務', kana: 'ぎむ', freq: 1270, level: 2 },
  { en: 'responsibility', ja: '責任', kana: 'せきにん', freq: 1180, level: 2, theme: 'ビジネス' },
  { en: 'role', ja: '役割', kana: 'やくわり', freq: 1160, level: 2, theme: 'ビジネス' },
  { en: 'task', ja: '課題', kana: 'かだい', freq: 1170, level: 2, theme: 'ビジネス' },
  { en: 'talent', ja: '才能', kana: 'さいのう', freq: 1330, level: 2 },
  { en: 'mistake', ja: '過ち', kana: 'あやまち', freq: 1150, level: 2 },
  { en: 'danger', ja: '危険', kana: 'きけん', freq: 1120, level: 2 },
  { en: 'safety', ja: '安全', kana: 'あんぜん', freq: 1110, level: 2 },
  { en: 'battle', ja: '戦い', kana: 'たたかい', freq: 1280, level: 2 },
  { en: 'victory', ja: '勝利', kana: 'しょうり', freq: 1300, level: 2 },
  { en: 'army', ja: '軍隊', kana: 'ぐんたい', freq: 1340, level: 2 },
  { en: 'weapon', ja: '武器', kana: 'ぶき', freq: 1350, level: 2 },
  { en: 'citizen', ja: '市民', kana: 'しみん', freq: 1230, level: 2 },
  { en: 'capital', ja: '首都', kana: 'しゅと', freq: 1250, level: 2, theme: '旅行' },
  { en: 'border', ja: '国境', kana: 'こっきょう', freq: 1310, level: 2, theme: '旅行' },
  { en: 'couple', ja: '夫婦', kana: 'ふうふ', freq: 1220, level: 2, theme: '日常' },
  { en: 'leader', ja: '指導者', kana: 'しどうしゃ', freq: 1170, level: 2, theme: 'ビジネス' },
  { en: 'soldier', ja: '兵士', kana: 'へいし', freq: 1320, level: 2 },
  // 低頻度・抽象（L3: 2,001–3,000）
  { en: 'philosophy', ja: '哲学', kana: 'てつがく', freq: 2100, level: 3 },
  { en: 'democracy', ja: '民主主義', kana: 'みんしゅしゅぎ', freq: 2200, level: 3 },
  { en: 'strategy', ja: '戦略', kana: 'せんりゃく', freq: 2050, level: 3, theme: 'ビジネス' },
  { en: 'policy', ja: '方針', kana: 'ほうしん', freq: 2080, level: 3, theme: 'ビジネス' },
  { en: 'principle', ja: '原則', kana: 'げんそく', freq: 2150, level: 3 },
  { en: 'concept', ja: '概念', kana: 'がいねん', freq: 2120, level: 3 },
  { en: 'analysis', ja: '分析', kana: 'ぶんせき', freq: 2090, level: 3, theme: 'ビジネス' },
  { en: 'statistics', ja: '統計', kana: 'とうけい', freq: 2250, level: 3 },
  { en: 'proportion', ja: '比率', kana: 'ひりつ', freq: 2280, level: 3 },
  { en: 'estimate', ja: '見積もり', kana: 'みつもり', freq: 2180, level: 3, theme: 'ビジネス' },
  { en: 'forecast', ja: '予測', kana: 'よそく', freq: 2200, level: 3, theme: 'ビジネス' },
  { en: 'trend', ja: '傾向', kana: 'けいこう', freq: 2160, level: 3 },
  { en: 'factor', ja: '要因', kana: 'よういん', freq: 2140, level: 3 },
  { en: 'element', ja: '要素', kana: 'ようそ', freq: 2130, level: 3 },
  { en: 'aspect', ja: '側面', kana: 'そくめん', freq: 2240, level: 3 },
  { en: 'feature', ja: '特徴', kana: 'とくちょう', freq: 2110, level: 3 },
  { en: 'phenomenon', ja: '現象', kana: 'げんしょう', freq: 2260, level: 3 },

  // ==== 頻度ベース拡充（Issue #26・バッチ6） ====
  // 動詞（L1）
  { en: 'remain', ja: '残る', kana: 'のこる', freq: 305, level: 1 },
  { en: 'seem', ja: '思える', kana: 'おもえる', freq: 320, level: 1 },
  { en: 'include', ja: '含める', kana: 'ふくめる', freq: 330, level: 1 },
  { en: 'contain', ja: '含む', kana: 'ふくむ', freq: 340, level: 1 },
  { en: 'complete', ja: '完了する', kana: 'かんりょうする', freq: 350, level: 1, theme: 'ビジネス' },
  { en: 'handle', ja: '扱う', kana: 'あつかう', freq: 360, level: 1 },
  { en: 'suffer', ja: '苦しむ', kana: 'くるしむ', freq: 370, level: 1 },
  { en: 'hurt', ja: '傷つける', kana: 'きずつける', freq: 352, level: 1 },
  { en: 'kill', ja: '殺す', kana: 'ころす', freq: 342, level: 1 },
  { en: 'escape', ja: '逃げる', kana: 'にげる', freq: 332, level: 1 },
  { en: 'hide', ja: '隠す', kana: 'かくす', freq: 322, level: 1 },
  { en: 'seek', ja: '探す', kana: 'さがす', freq: 312, level: 1 },
  { en: 'examine', ja: '調べる', kana: 'しらべる', freq: 342, level: 1 },
  { en: 'disappear', ja: '消える', kana: 'きえる', freq: 352, level: 1 },
  { en: 'depend', ja: '頼る', kana: 'たよる', freq: 362, level: 1 },
  { en: 'wish', ja: '願う', kana: 'ねがう', freq: 332, level: 1 },
  { en: 'avoid', ja: '避ける', kana: 'さける', freq: 343, level: 1 },
  { en: 'admit', ja: '認める', kana: 'みとめる', freq: 363, level: 1 },
  { en: 'inform', ja: '知らせる', kana: 'しらせる', freq: 353, level: 1, theme: 'ビジネス' },
  { en: 'warn', ja: '警告する', kana: 'けいこくする', freq: 383, level: 1 },
  { en: 'promise', ja: '約束する', kana: 'やくそくする', freq: 323, level: 1 },
  { en: 'thank', ja: '感謝する', kana: 'かんしゃする', freq: 303, level: 1, theme: '日常' },
  { en: 'apologize', ja: '謝る', kana: 'あやまる', freq: 364, level: 1, theme: '日常' },
  { en: 'greet', ja: '挨拶する', kana: 'あいさつする', freq: 334, level: 1, theme: '日常' },
  { en: 'welcome', ja: '迎える', kana: 'むかえる', freq: 344, level: 1, theme: '日常' },
  { en: 'celebrate', ja: '祝う', kana: 'いわう', freq: 354, level: 1, theme: '日常' },
  { en: 'marry', ja: '結婚する', kana: 'けっこんする', freq: 333, level: 1, theme: '日常' },
  { en: 'practice', ja: '練習する', kana: 'れんしゅうする', freq: 324, level: 1, theme: '日常' },
  { en: 'waste', ja: '無駄にする', kana: 'むだにする', freq: 384, level: 1 },
  // 動詞（L2）
  { en: 'exist', ja: '存在する', kana: 'そんざいする', freq: 1100, level: 2 },
  { en: 'occur', ja: '生じる', kana: 'しょうじる', freq: 1150, level: 2 },
  { en: 'belong', ja: '属する', kana: 'ぞくする', freq: 1200, level: 2 },
  { en: 'establish', ja: '設立する', kana: 'せつりつする', freq: 1120, level: 2, theme: 'ビジネス' },
  { en: 'create', ja: '創造する', kana: 'そうぞうする', freq: 1080, level: 2 },
  { en: 'limit', ja: '制限する', kana: 'せいげんする', freq: 1160, level: 2 },
  { en: 'treat', ja: '治療する', kana: 'ちりょうする', freq: 1180, level: 2, theme: '日常' },
  { en: 'cure', ja: '癒す', kana: 'いやす', freq: 1250, level: 2 },
  { en: 'rescue', ja: '救助する', kana: 'きゅうじょする', freq: 1280, level: 2 },
  { en: 'search', ja: '検索する', kana: 'けんさくする', freq: 1140, level: 2 },
  { en: 'explore', ja: '探検する', kana: 'たんけんする', freq: 1220, level: 2, theme: '旅行' },
  { en: 'observe', ja: '観察する', kana: 'かんさつする', freq: 1230, level: 2 },
  { en: 'notice', ja: '注目する', kana: 'ちゅうもくする', freq: 1170, level: 2 },
  { en: 'require', ja: '必要とする', kana: 'ひつようとする', freq: 1090, level: 2 },
  { en: 'intend', ja: '意図する', kana: 'いとする', freq: 1300, level: 2 },
  { en: 'reject', ja: '拒む', kana: 'こばむ', freq: 1240, level: 2 },
  { en: 'approve', ja: '承認する', kana: 'しょうにんする', freq: 1260, level: 2, theme: 'ビジネス' },
  { en: 'deny', ja: '否定する', kana: 'ひていする', freq: 1270, level: 2 },
  { en: 'succeed', ja: '成功する', kana: 'せいこうする', freq: 1110, level: 2 },
  { en: 'fail', ja: '失敗する', kana: 'しっぱいする', freq: 1105, level: 2 },
  { en: 'compete', ja: '競争する', kana: 'きょうそうする', freq: 1190, level: 2, theme: 'ビジネス' },
  { en: 'manufacture', ja: '製造する', kana: 'せいぞうする', freq: 1320, level: 2, theme: 'ビジネス' },
  { en: 'consume', ja: '消費する', kana: 'しょうひする', freq: 1290, level: 2, theme: 'ビジネス' },
  // 形容詞（L1）
  { en: 'rare', ja: '珍しい', kana: 'めずらしい', freq: 350, level: 1 },
  { en: 'usual', ja: '普通の', kana: 'ふつうの', freq: 322, level: 1 },
  { en: 'strange', ja: '奇妙な', kana: 'きみょうな', freq: 362, level: 1 },
  { en: 'correct', ja: '適切な', kana: 'てきせつな', freq: 342, level: 1 },
  { en: 'necessary', ja: '必要な', kana: 'ひつような', freq: 332, level: 1 },
  { en: 'huge', ja: '巨大な', kana: 'きょだいな', freq: 363, level: 1 },
  { en: 'enough', ja: '十分な', kana: 'じゅうぶんな', freq: 343, level: 1 },
  { en: 'various', ja: '様々な', kana: 'さまざまな', freq: 353, level: 1 },
  { en: 'several', ja: 'いくつかの', kana: 'いくつかの', freq: 364, level: 1 },
  { en: 'whole', ja: '全部の', kana: 'ぜんぶの', freq: 333, level: 1 },
  { en: 'modern', ja: '現代の', kana: 'げんだいの', freq: 354, level: 1 },
  { en: 'recent', ja: '最近の', kana: 'さいきんの', freq: 344, level: 1 },
  { en: 'current', ja: '現在の', kana: 'げんざいの', freq: 355, level: 1 },
  { en: 'future', ja: '将来の', kana: 'しょうらいの', freq: 334, level: 1 },
  { en: 'past', ja: '過去の', kana: 'かこの', freq: 345, level: 1 },
  { en: 'next', ja: '次の', kana: 'つぎの', freq: 324, level: 1 },
  // 形容詞（L2）
  { en: 'normal', ja: '正常な', kana: 'せいじょうな', freq: 1100, level: 2 },
  { en: 'ordinary', ja: '平凡な', kana: 'へいぼんな', freq: 1250, level: 2 },
  { en: 'particular', ja: '特定の', kana: 'とくていの', freq: 1150, level: 2 },
  { en: 'certain', ja: '確かな', kana: 'たしかな', freq: 1080, level: 2 },
  { en: 'obvious', ja: '明らかな', kana: 'あきらかな', freq: 1200, level: 2 },
  { en: 'exact', ja: '正確な', kana: 'せいかくな', freq: 1170, level: 2 },
  { en: 'false', ja: '偽の', kana: 'にせの', freq: 1220, level: 2 },
  { en: 'actual', ja: '実際の', kana: 'じっさいの', freq: 1130, level: 2 },
  { en: 'impossible', ja: '不可能な', kana: 'ふかのうな', freq: 1190, level: 2 },
  { en: 'major', ja: '主要な', kana: 'しゅような', freq: 1120, level: 2 },
  { en: 'minor', ja: '些細な', kana: 'ささいな', freq: 1300, level: 2 },
  { en: 'severe', ja: '厳しい', kana: 'きびしい', freq: 1240, level: 2 },
  { en: 'mild', ja: '緩やかな', kana: 'ゆるやかな', freq: 1310, level: 2 },
  { en: 'powerful', ja: '強力な', kana: 'きょうりょくな', freq: 1160, level: 2 },
  { en: 'enormous', ja: '莫大な', kana: 'ばくだいな', freq: 1330, level: 2 },
  { en: 'vast', ja: '広大な', kana: 'こうだいな', freq: 1280, level: 2 },
  { en: 'broad', ja: '幅広い', kana: 'はばひろい', freq: 1270, level: 2 },
  { en: 'entire', ja: '全体の', kana: 'ぜんたいの', freq: 1180, level: 2 },
  { en: 'single', ja: '単一の', kana: 'たんいつの', freq: 1210, level: 2 },
  { en: 'double', ja: '二重の', kana: 'にじゅうの', freq: 1230, level: 2 },
  { en: 'plenty', ja: '豊富な', kana: 'ほうふな', freq: 1290, level: 2 },
  { en: 'ancient', ja: '古代の', kana: 'こだいの', freq: 1260, level: 2 },
  { en: 'previous', ja: '以前の', kana: 'いぜんの', freq: 1140, level: 2 },
  { en: 'initial', ja: '最初の', kana: 'さいしょの', freq: 1150, level: 2 },
  // 専門・抽象（L3: 2,001–3,000）
  { en: 'hypothesis', ja: '仮説', kana: 'かせつ', freq: 2200, level: 3 },
  { en: 'mechanism', ja: '機構', kana: 'きこう', freq: 2250, level: 3 },
  { en: 'framework', ja: '枠組み', kana: 'わくぐみ', freq: 2280, level: 3, theme: 'ビジネス' },
  { en: 'infrastructure', ja: '基盤', kana: 'きばん', freq: 2300, level: 3 },
  { en: 'innovation', ja: '革新', kana: 'かくしん', freq: 2150, level: 3, theme: 'ビジネス' },
  { en: 'efficiency', ja: '効率', kana: 'こうりつ', freq: 2100, level: 3, theme: 'ビジネス' },
  { en: 'productivity', ja: '生産性', kana: 'せいさんせい', freq: 2180, level: 3, theme: 'ビジネス' },
  { en: 'revenue', ja: '収益', kana: 'しゅうえき', freq: 2120, level: 3, theme: 'ビジネス' },
  { en: 'asset', ja: '資産', kana: 'しさん', freq: 2160, level: 3, theme: 'ビジネス' },
  { en: 'recession', ja: '不況', kana: 'ふきょう', freq: 2280, level: 3, theme: 'ビジネス' },

  // ==== 頻度ベース拡充（Issue #26・バッチ7：1,000語到達） ====
  // 動作動詞（L1）
  { en: 'enter', ja: '入る', kana: 'はいる', freq: 350, level: 1 },
  { en: 'exit', ja: '出る', kana: 'でる', freq: 360, level: 1 },
  { en: 'cross', ja: '渡る', kana: 'わたる', freq: 380, level: 1 },
  { en: 'reach', ja: '達する', kana: 'たっする', freq: 400, level: 1 },
  { en: 'approach', ja: '近寄る', kana: 'ちかよる', freq: 540, level: 1 },
  { en: 'pick', ja: '拾う', kana: 'ひろう', freq: 420, level: 1 },
  { en: 'drop', ja: '落とす', kana: 'おとす', freq: 430, level: 1 },
  { en: 'lift', ja: '持ち上げる', kana: 'もちあげる', freq: 560, level: 1 },
  { en: 'press', ja: '押さえる', kana: 'おさえる', freq: 440, level: 1 },
  { en: 'turn', ja: '回す', kana: 'まわす', freq: 382, level: 1 },
  { en: 'bend', ja: '曲げる', kana: 'まげる', freq: 580, level: 1 },
  { en: 'fold', ja: '折る', kana: 'おる', freq: 562, level: 1 },
  { en: 'tie', ja: '結ぶ', kana: 'むすぶ', freq: 540, level: 1 },
  { en: 'tear', ja: '破る', kana: 'やぶる', freq: 600, level: 1 },
  { en: 'burn', ja: '燃やす', kana: 'もやす', freq: 520, level: 1 },
  { en: 'freeze', ja: '凍る', kana: 'こおる', freq: 542, level: 1 },
  { en: 'melt', ja: '溶ける', kana: 'とける', freq: 564, level: 1 },
  { en: 'boil', ja: '沸かす', kana: 'わかす', freq: 500, level: 1, theme: '日常' },
  { en: 'dry', ja: '乾かす', kana: 'かわかす', freq: 522, level: 1, theme: '日常' },
  { en: 'fill', ja: '満たす', kana: 'みたす', freq: 480, level: 1 },
  { en: 'pour', ja: '注ぐ', kana: 'そそぐ', freq: 544, level: 1, theme: '日常' },
  { en: 'spill', ja: 'こぼす', kana: 'こぼす', freq: 600, level: 1, theme: '日常' },
  { en: 'shake', ja: '振る', kana: 'ふる', freq: 462, level: 1 },
  { en: 'hang', ja: '掛ける', kana: 'かける', freq: 482, level: 1 },
  { en: 'knock', ja: '叩く', kana: 'たたく', freq: 502, level: 1 },
  { en: 'shout', ja: '叫ぶ', kana: 'さけぶ', freq: 522, level: 1 },
  { en: 'whisper', ja: 'ささやく', kana: 'ささやく', freq: 640, level: 1 },
  { en: 'laugh', ja: '笑う', kana: 'わらう', freq: 360, level: 1, theme: '日常' },
  { en: 'cry', ja: '泣く', kana: 'なく', freq: 380, level: 1, theme: '日常' },
  { en: 'smile', ja: '微笑む', kana: 'ほほえむ', freq: 400, level: 1, theme: '日常' },
  { en: 'breathe', ja: '呼吸する', kana: 'こきゅうする', freq: 544, level: 1 },
  { en: 'bite', ja: '噛む', kana: 'かむ', freq: 520, level: 1 },
  { en: 'swallow', ja: '飲み込む', kana: 'のみこむ', freq: 600, level: 1 },
  { en: 'touch', ja: '触れる', kana: 'ふれる', freq: 420, level: 1 },
  { en: 'kick', ja: '蹴る', kana: 'ける', freq: 462, level: 1 },
  { en: 'hit', ja: '打つ', kana: 'うつ', freq: 382, level: 1 },
  { en: 'slide', ja: '滑る', kana: 'すべる', freq: 544, level: 1 },
  { en: 'roll', ja: '転がる', kana: 'ころがる', freq: 564, level: 1 },
  { en: 'float', ja: '浮かぶ', kana: 'うかぶ', freq: 520, level: 1 },
  { en: 'sink', ja: '沈む', kana: 'しずむ', freq: 544, level: 1 },
  { en: 'dive', ja: '潜る', kana: 'もぐる', freq: 580, level: 1, theme: '旅行' },
  { en: 'lock', ja: '施錠する', kana: 'せじょうする', freq: 620, level: 1 },
  // 動物（L1）
  { en: 'horse', ja: '馬', kana: 'うま', freq: 410, level: 1 },
  { en: 'cow', ja: '牛', kana: 'うし', freq: 420, level: 1 },
  { en: 'pig', ja: '豚', kana: 'ぶた', freq: 430, level: 1 },
  { en: 'sheep', ja: '羊', kana: 'ひつじ', freq: 440, level: 1 },
  { en: 'chicken', ja: '鶏', kana: 'にわとり', freq: 450, level: 1, theme: '日常' },
  { en: 'rabbit', ja: '兎', kana: 'うさぎ', freq: 460, level: 1 },
  { en: 'bear', ja: '熊', kana: 'くま', freq: 470, level: 1 },
  { en: 'wolf', ja: '狼', kana: 'おおかみ', freq: 480, level: 1 },
  { en: 'fox', ja: '狐', kana: 'きつね', freq: 490, level: 1 },
  { en: 'deer', ja: '鹿', kana: 'しか', freq: 500, level: 1 },
  { en: 'monkey', ja: '猿', kana: 'さる', freq: 510, level: 1 },
  { en: 'elephant', ja: '象', kana: 'ぞう', freq: 520, level: 1 },
  { en: 'tiger', ja: '虎', kana: 'とら', freq: 530, level: 1 },
  { en: 'snake', ja: '蛇', kana: 'へび', freq: 540, level: 1 },
  { en: 'frog', ja: '蛙', kana: 'かえる', freq: 550, level: 1 },
  { en: 'insect', ja: '昆虫', kana: 'こんちゅう', freq: 560, level: 1 },
  { en: 'bee', ja: '蜂', kana: 'はち', freq: 570, level: 1 },
  { en: 'ant', ja: '蟻', kana: 'あり', freq: 580, level: 1 },
  { en: 'butterfly', ja: '蝶', kana: 'ちょう', freq: 590, level: 1 },
  { en: 'worm', ja: '虫', kana: 'むし', freq: 600, level: 1 },
  // 食べ物（L1・日常）
  { en: 'egg', ja: '卵', kana: 'たまご', freq: 360, level: 1, theme: '日常' },
  { en: 'sugar', ja: '砂糖', kana: 'さとう', freq: 370, level: 1, theme: '日常' },
  { en: 'salt', ja: '塩', kana: 'しお', freq: 380, level: 1, theme: '日常' },
  { en: 'pepper', ja: '胡椒', kana: 'こしょう', freq: 600, level: 1, theme: '日常' },
  { en: 'noodle', ja: '麺', kana: 'めん', freq: 500, level: 1, theme: '日常' },
  { en: 'onion', ja: '玉ねぎ', kana: 'たまねぎ', freq: 520, level: 1, theme: '日常' },
  { en: 'potato', ja: 'じゃがいも', kana: 'じゃがいも', freq: 480, level: 1, theme: '日常' },
  { en: 'carrot', ja: '人参', kana: 'にんじん', freq: 530, level: 1, theme: '日常' },
  { en: 'beef', ja: '牛肉', kana: 'ぎゅうにく', freq: 450, level: 1, theme: '日常' },
  { en: 'pork', ja: '豚肉', kana: 'ぶたにく', freq: 460, level: 1, theme: '日常' },
  { en: 'lunch', ja: '昼食', kana: 'ちゅうしょく', freq: 400, level: 1, theme: '日常' },
  { en: 'snack', ja: '軽食', kana: 'けいしょく', freq: 540, level: 1, theme: '日常' },
  { en: 'apple', ja: '林檎', kana: 'りんご', freq: 410, level: 1, theme: '日常' },
  // 自然（L1）
  { en: 'root', ja: '根', kana: 'ね', freq: 560, level: 1 },
  { en: 'seed', ja: '種', kana: 'たね', freq: 520, level: 1 },
  { en: 'branch', ja: '枝', kana: 'えだ', freq: 530, level: 1 },
  { en: 'grass', ja: '草', kana: 'くさ', freq: 470, level: 1 },
  { en: 'desert', ja: '砂漠', kana: 'さばく', freq: 540, level: 1, theme: '旅行' },
  { en: 'ocean', ja: '海洋', kana: 'かいよう', freq: 480, level: 1, theme: '旅行' },
  { en: 'pond', ja: '池', kana: 'いけ', freq: 500, level: 1 },
  { en: 'well', ja: '井戸', kana: 'いど', freq: 580, level: 1 },
  { en: 'stream', ja: '小川', kana: 'おがわ', freq: 540, level: 1, theme: '旅行' },
  { en: 'waterfall', ja: '滝', kana: 'たき', freq: 560, level: 1, theme: '旅行' },
  { en: 'silver', ja: '銀', kana: 'ぎん', freq: 470, level: 1 },
  { en: 'wood', ja: '木材', kana: 'もくざい', freq: 520, level: 1 },
  { en: 'cave', ja: '洞窟', kana: 'どうくつ', freq: 600, level: 1, theme: '旅行' },
  // 人・社会・文書（L1）
  { en: 'person', ja: '人', kana: 'ひと', freq: 280, level: 1, theme: '日常' },
  { en: 'people', ja: '人々', kana: 'ひとびと', freq: 300, level: 1 },
  { en: 'human', ja: '人間', kana: 'にんげん', freq: 320, level: 1 },
  { en: 'adult', ja: '大人', kana: 'おとな', freq: 360, level: 1, theme: '日常' },
  { en: 'age', ja: '年齢', kana: 'ねんれい', freq: 380, level: 1 },
  { en: 'century', ja: '世紀', kana: 'せいき', freq: 540, level: 1 },
  { en: 'period', ja: '期間', kana: 'きかん', freq: 420, level: 1 },
  { en: 'generation', ja: '世代', kana: 'せだい', freq: 560, level: 1 },
  { en: 'public', ja: '大衆', kana: 'たいしゅう', freq: 600, level: 1 },
  { en: 'individual', ja: '個人', kana: 'こじん', freq: 580, level: 1 },
  { en: 'line', ja: '線', kana: 'せん', freq: 340, level: 1 },
  { en: 'title', ja: '題名', kana: 'だいめい', freq: 560, level: 1 },
  { en: 'topic', ja: '話題', kana: 'わだい', freq: 520, level: 1 },
  { en: 'subject', ja: '主題', kana: 'しゅだい', freq: 540, level: 1 },
  { en: 'content', ja: '内容', kana: 'ないよう', freq: 480, level: 1 },
  { en: 'detail', ja: '詳細', kana: 'しょうさい', freq: 500, level: 1, theme: 'ビジネス' },
  { en: 'summary', ja: '要約', kana: 'ようやく', freq: 620, level: 1, theme: 'ビジネス' },
  { en: 'conclusion', ja: '結論', kana: 'けつろん', freq: 580, level: 1 },
  { en: 'novel', ja: '小説', kana: 'しょうせつ', freq: 500, level: 1, theme: '日常' },
  { en: 'article', ja: '記事', kana: 'きじ', freq: 520, level: 1 },
  { en: 'magazine', ja: '雑誌', kana: 'ざっし', freq: 480, level: 1, theme: '日常' },
  { en: 'newspaper', ja: '新聞', kana: 'しんぶん', freq: 420, level: 1, theme: '日常' },
  { en: 'dictionary', ja: '辞書', kana: 'じしょ', freq: 500, level: 1 },
  { en: 'sign', ja: '看板', kana: 'かんばん', freq: 540, level: 1, theme: '旅行' },
  { en: 'reward', ja: '報酬', kana: 'ほうしゅう', freq: 640, level: 1, theme: 'ビジネス' },
  // 抽象・専門（L2）
  { en: 'gender', ja: '性別', kana: 'せいべつ', freq: 1100, level: 2 },
  { en: 'paragraph', ja: '段落', kana: 'だんらく', freq: 1200, level: 2 },
  { en: 'code', ja: '暗号', kana: 'あんごう', freq: 1250, level: 2 },
  { en: 'rank', ja: '順位', kana: 'じゅんい', freq: 1150, level: 2 },
  { en: 'grade', ja: '等級', kana: 'とうきゅう', freq: 1280, level: 2 },
  { en: 'bonus', ja: '賞与', kana: 'しょうよ', freq: 1320, level: 2, theme: 'ビジネス' },
  { en: 'treasure', ja: '宝', kana: 'たから', freq: 1180, level: 2 },
  { en: 'liquid', ja: '液体', kana: 'えきたい', freq: 1240, level: 2 },
  { en: 'insurance', ja: '保険', kana: 'ほけん', freq: 1160, level: 2, theme: 'ビジネス' },
  { en: 'pension', ja: '年金', kana: 'ねんきん', freq: 1310, level: 2, theme: 'ビジネス' },

  // ==== 頻度ベース拡充（Issue #27・バッチ8：第2千語帯） ====
  // 職業（L1/L2）
  { en: 'student', ja: '学生', kana: 'がくせい', freq: 620, level: 1, theme: '日常' },
  { en: 'pupil', ja: '生徒', kana: 'せいと', freq: 720, level: 1, theme: '日常' },
  { en: 'driver', ja: '運転手', kana: 'うんてんしゅ', freq: 700, level: 1, theme: '旅行' },
  { en: 'nurse', ja: '看護師', kana: 'かんごし', freq: 680, level: 1, theme: '日常' },
  { en: 'engineer', ja: '技師', kana: 'ぎし', freq: 1050, level: 2, theme: 'ビジネス' },
  { en: 'lawyer', ja: '弁護士', kana: 'べんごし', freq: 1080, level: 2 },
  { en: 'farmer', ja: '農家', kana: 'のうか', freq: 740, level: 1 },
  { en: 'carpenter', ja: '大工', kana: 'だいく', freq: 1200, level: 2 },
  { en: 'mechanic', ja: '整備士', kana: 'せいびし', freq: 1300, level: 2 },
  { en: 'pilot', ja: '操縦士', kana: 'そうじゅうし', freq: 1150, level: 2, theme: '旅行' },
  { en: 'sailor', ja: '船員', kana: 'せんいん', freq: 1250, level: 2 },
  { en: 'captain', ja: '船長', kana: 'せんちょう', freq: 1100, level: 2 },
  { en: 'chef', ja: '料理人', kana: 'りょうりにん', freq: 1120, level: 2, theme: '日常' },
  { en: 'waiter', ja: '給仕', kana: 'きゅうじ', freq: 1320, level: 2, theme: '旅行' },
  { en: 'clerk', ja: '店員', kana: 'てんいん', freq: 1090, level: 2, theme: 'ビジネス' },
  { en: 'secretary', ja: '秘書', kana: 'ひしょ', freq: 1180, level: 2, theme: 'ビジネス' },
  { en: 'accountant', ja: '会計士', kana: 'かいけいし', freq: 1340, level: 2, theme: 'ビジネス' },
  { en: 'banker', ja: '銀行員', kana: 'ぎんこういん', freq: 1290, level: 2, theme: 'ビジネス' },
  { en: 'merchant', ja: '商人', kana: 'しょうにん', freq: 1230, level: 2, theme: 'ビジネス' },
  { en: 'director', ja: '監督', kana: 'かんとく', freq: 1110, level: 2, theme: 'ビジネス' },
  { en: 'officer', ja: '役人', kana: 'やくにん', freq: 1160, level: 2 },
  { en: 'scientist', ja: '科学者', kana: 'かがくしゃ', freq: 1070, level: 2 },
  { en: 'professor', ja: '教授', kana: 'きょうじゅ', freq: 1130, level: 2 },
  { en: 'artist', ja: '芸術家', kana: 'げいじゅつか', freq: 1100, level: 2 },
  { en: 'painter', ja: '画家', kana: 'がか', freq: 1270, level: 2 },
  { en: 'musician', ja: '音楽家', kana: 'おんがくか', freq: 1240, level: 2 },
  { en: 'singer', ja: '歌手', kana: 'かしゅ', freq: 1060, level: 2, theme: '日常' },
  { en: 'dancer', ja: '踊り子', kana: 'おどりこ', freq: 1360, level: 2 },
  { en: 'actor', ja: '俳優', kana: 'はいゆう', freq: 1080, level: 2, theme: '日常' },
  { en: 'writer', ja: '作家', kana: 'さっか', freq: 1050, level: 2 },
  { en: 'poet', ja: '詩人', kana: 'しじん', freq: 1380, level: 2 },
  { en: 'author', ja: '著者', kana: 'ちょしゃ', freq: 1190, level: 2 },
  { en: 'journalist', ja: '記者', kana: 'きしゃ', freq: 1210, level: 2 },
  { en: 'photographer', ja: '写真家', kana: 'しゃしんか', freq: 1300, level: 2, theme: '日常' },
  { en: 'architect', ja: '建築家', kana: 'けんちくか', freq: 1280, level: 2 },
  { en: 'dentist', ja: '歯科医', kana: 'しかい', freq: 1220, level: 2, theme: '日常' },
  { en: 'surgeon', ja: '外科医', kana: 'げかい', freq: 1390, level: 2 },
  { en: 'priest', ja: '司祭', kana: 'しさい', freq: 1340, level: 2 },
  { en: 'monk', ja: '僧侶', kana: 'そうりょ', freq: 1400, level: 2 },
  { en: 'nun', ja: '修道女', kana: 'しゅうどうじょ', freq: 1450, level: 2 },
  { en: 'guard', ja: '警備員', kana: 'けいびいん', freq: 1250, level: 2 },
  { en: 'tailor', ja: '仕立て屋', kana: 'したてや', freq: 1420, level: 2 },
  { en: 'baker', ja: 'パン屋', kana: 'ぱんや', freq: 1230, level: 2, theme: '日常' },
  { en: 'butcher', ja: '肉屋', kana: 'にくや', freq: 1360, level: 2, theme: '日常' },
  { en: 'barber', ja: '床屋', kana: 'とこや', freq: 1330, level: 2, theme: '日常' },
  { en: 'gardener', ja: '庭師', kana: 'にわし', freq: 1410, level: 2 },
  { en: 'servant', ja: '召使い', kana: 'めしつかい', freq: 1370, level: 2 },
  { en: 'slave', ja: '奴隷', kana: 'どれい', freq: 1320, level: 2 },
  { en: 'firefighter', ja: '消防士', kana: 'しょうぼうし', freq: 1240, level: 2 },
  { en: 'fisherman', ja: '漁師', kana: 'りょうし', freq: 1260, level: 2 },
  { en: 'hunter', ja: '狩人', kana: 'かりゅうど', freq: 1430, level: 2 },
  { en: 'prince', ja: '王子', kana: 'おうじ', freq: 1140, level: 2 },
  { en: 'princess', ja: '王女', kana: 'おうじょ', freq: 1150, level: 2 },
  { en: 'president', ja: '大統領', kana: 'だいとうりょう', freq: 1090, level: 2 },
  { en: 'minister', ja: '大臣', kana: 'だいじん', freq: 1170, level: 2 },
  { en: 'mayor', ja: '市長', kana: 'しちょう', freq: 1310, level: 2 },
  { en: 'governor', ja: '知事', kana: 'ちじ', freq: 1350, level: 2 },
  // 建物・場所（L1/L2）
  { en: 'church', ja: '教会', kana: 'きょうかい', freq: 920, level: 1 },
  { en: 'temple', ja: '寺', kana: 'てら', freq: 880, level: 1, theme: '旅行' },
  { en: 'shrine', ja: '神社', kana: 'じんじゃ', freq: 940, level: 1, theme: '旅行' },
  { en: 'palace', ja: '宮殿', kana: 'きゅうでん', freq: 1180, level: 2, theme: '旅行' },
  { en: 'castle', ja: '城', kana: 'しろ', freq: 900, level: 1, theme: '旅行' },
  { en: 'prison', ja: '刑務所', kana: 'けいむしょ', freq: 1220, level: 2 },
  { en: 'university', ja: '大学', kana: 'だいがく', freq: 860, level: 1 },
  { en: 'clinic', ja: '診療所', kana: 'しんりょうじょ', freq: 1280, level: 2, theme: '日常' },
  { en: 'pharmacy', ja: '薬局', kana: 'やっきょく', freq: 1190, level: 2, theme: '日常' },
  { en: 'cafe', ja: '喫茶店', kana: 'きっさてん', freq: 1050, level: 2, theme: '旅行' },
  { en: 'theater', ja: '劇場', kana: 'げきじょう', freq: 1120, level: 2 },
  { en: 'cinema', ja: '映画館', kana: 'えいがかん', freq: 1080, level: 2, theme: '日常' },
  { en: 'stadium', ja: '競技場', kana: 'きょうぎじょう', freq: 1240, level: 2 },
  { en: 'gym', ja: '体育館', kana: 'たいいくかん', freq: 1160, level: 2, theme: '日常' },
  { en: 'zoo', ja: '動物園', kana: 'どうぶつえん', freq: 1100, level: 2, theme: '日常' },
  { en: 'gallery', ja: '画廊', kana: 'がろう', freq: 1380, level: 2 },
  { en: 'warehouse', ja: '倉庫', kana: 'そうこ', freq: 1300, level: 2, theme: 'ビジネス' },
  { en: 'garage', ja: '車庫', kana: 'しゃこ', freq: 1260, level: 2, theme: '日常' },
  { en: 'barn', ja: '納屋', kana: 'なや', freq: 1440, level: 2 },
  { en: 'cottage', ja: '山小屋', kana: 'やまごや', freq: 1420, level: 2, theme: '旅行' },
  { en: 'mansion', ja: '大邸宅', kana: 'だいていたく', freq: 1460, level: 2 },
  { en: 'hall', ja: '広間', kana: 'ひろま', freq: 1140, level: 2 },
  { en: 'basement', ja: '地下室', kana: 'ちかしつ', freq: 1290, level: 2, theme: '日常' },
  { en: 'attic', ja: '屋根裏', kana: 'やねうら', freq: 1450, level: 2, theme: '日常' },
  { en: 'porch', ja: '玄関', kana: 'げんかん', freq: 1230, level: 2, theme: '日常' },
  { en: 'chimney', ja: '煙突', kana: 'えんとつ', freq: 1410, level: 2 },
  { en: 'inn', ja: '宿', kana: 'やど', freq: 1150, level: 2, theme: '旅行' },
  { en: 'home', ja: '家庭', kana: 'かてい', freq: 700, level: 1, theme: '日常' },
  // 乗り物・交通（L1/L2）
  { en: 'subway', ja: '地下鉄', kana: 'ちかてつ', freq: 900, level: 1, theme: '旅行' },
  { en: 'ferry', ja: '連絡船', kana: 'れんらくせん', freq: 1280, level: 2, theme: '旅行' },
  { en: 'truck', ja: '貨物車', kana: 'かもつしゃ', freq: 1050, level: 2 },
  { en: 'tire', ja: 'タイヤ', kana: 'たいや', freq: 1180, level: 2 },
  { en: 'engine', ja: '発動機', kana: 'はつどうき', freq: 1160, level: 2 },
  { en: 'fuel', ja: '燃料', kana: 'ねんりょう', freq: 1200, level: 2 },
  { en: 'highway', ja: '高速道路', kana: 'こうそくどうろ', freq: 1090, level: 2, theme: '旅行' },
  { en: 'avenue', ja: '大通り', kana: 'おおどおり', freq: 1240, level: 2, theme: '旅行' },
  { en: 'lane', ja: '車線', kana: 'しゃせん', freq: 1320, level: 2, theme: '旅行' },
  { en: 'railway', ja: '鉄道', kana: 'てつどう', freq: 1070, level: 2, theme: '旅行' },
  { en: 'dock', ja: '波止場', kana: 'はとば', freq: 1430, level: 2, theme: '旅行' },
  // 家族（L1）
  { en: 'grandfather', ja: '祖父', kana: 'そふ', freq: 640, level: 1, theme: '日常' },
  { en: 'grandmother', ja: '祖母', kana: 'そぼ', freq: 645, level: 1, theme: '日常' },
  { en: 'grandson', ja: '孫', kana: 'まご', freq: 760, level: 1, theme: '日常' },
  { en: 'uncle', ja: '叔父', kana: 'おじ', freq: 680, level: 1, theme: '日常' },
  { en: 'aunt', ja: '叔母', kana: 'おば', freq: 685, level: 1, theme: '日常' },
  { en: 'cousin', ja: 'いとこ', kana: 'いとこ', freq: 720, level: 1, theme: '日常' },
  { en: 'nephew', ja: '甥', kana: 'おい', freq: 1280, level: 2, theme: '日常' },
  { en: 'niece', ja: '姪', kana: 'めい', freq: 1290, level: 2, theme: '日常' },
  { en: 'relative', ja: '親戚', kana: 'しんせき', freq: 1100, level: 2, theme: '日常' },
  { en: 'ancestor', ja: '先祖', kana: 'せんぞ', freq: 1230, level: 2 },
  { en: 'twin', ja: '双子', kana: 'ふたご', freq: 1180, level: 2, theme: '日常' },
  { en: 'widow', ja: '未亡人', kana: 'みぼうじん', freq: 1400, level: 2 },
  { en: 'bride', ja: '花嫁', kana: 'はなよめ', freq: 1160, level: 2, theme: '日常' },
  { en: 'groom', ja: '花婿', kana: 'はなむこ', freq: 1410, level: 2, theme: '日常' },
  // 体（L1/L2）
  { en: 'forehead', ja: '額', kana: 'ひたい', freq: 900, level: 1, theme: '日常' },
  { en: 'cheek', ja: '頬', kana: 'ほお', freq: 880, level: 1, theme: '日常' },
  { en: 'chin', ja: '顎', kana: 'あご', freq: 870, level: 1, theme: '日常' },
  { en: 'lip', ja: '唇', kana: 'くちびる', freq: 820, level: 1, theme: '日常' },
  { en: 'tongue', ja: '舌', kana: 'した', freq: 840, level: 1, theme: '日常' },
  { en: 'throat', ja: '喉', kana: 'のど', freq: 860, level: 1, theme: '日常' },
  { en: 'belly', ja: '腹', kana: 'はら', freq: 850, level: 1, theme: '日常' },
  { en: 'waist', ja: '腰', kana: 'こし', freq: 890, level: 1, theme: '日常' },
  { en: 'hip', ja: '尻', kana: 'しり', freq: 920, level: 1, theme: '日常' },
  { en: 'thigh', ja: '太もも', kana: 'ふともも', freq: 1180, level: 2, theme: '日常' },
  { en: 'ankle', ja: '足首', kana: 'あしくび', freq: 1100, level: 2, theme: '日常' },
  { en: 'heel', ja: 'かかと', kana: 'かかと', freq: 1160, level: 2, theme: '日常' },
  { en: 'toe', ja: 'つま先', kana: 'つまさき', freq: 1080, level: 2, theme: '日常' },
  { en: 'wrist', ja: '手首', kana: 'てくび', freq: 1050, level: 2, theme: '日常' },
  { en: 'elbow', ja: '肘', kana: 'ひじ', freq: 1120, level: 2, theme: '日常' },
  { en: 'palm', ja: '手のひら', kana: 'てのひら', freq: 1200, level: 2, theme: '日常' },
  { en: 'beard', ja: '髭', kana: 'ひげ', freq: 1140, level: 2, theme: '日常' },
  { en: 'eyebrow', ja: '眉', kana: 'まゆ', freq: 1300, level: 2, theme: '日常' },
  { en: 'muscle', ja: '筋肉', kana: 'きんにく', freq: 1090, level: 2, theme: '日常' },
  { en: 'nerve', ja: '神経', kana: 'しんけい', freq: 1170, level: 2 },
  { en: 'lung', ja: '肺', kana: 'はい', freq: 1220, level: 2 },
  { en: 'liver', ja: '肝臓', kana: 'かんぞう', freq: 1310, level: 2 },
  { en: 'brain', ja: '脳', kana: 'のう', freq: 1010, level: 2 },
  { en: 'rib', ja: '肋骨', kana: 'ろっこつ', freq: 1420, level: 2 },
  // 感情・抽象（L2）
  { en: 'pride', ja: '誇り', kana: 'ほこり', freq: 1080, level: 2 },
  { en: 'shame', ja: '恥', kana: 'はじ', freq: 1140, level: 2 },
  { en: 'guilt', ja: '罪悪感', kana: 'ざいあくかん', freq: 1300, level: 2 },
  { en: 'jealousy', ja: '嫉妬', kana: 'しっと', freq: 1380, level: 2 },
  { en: 'greed', ja: '強欲', kana: 'ごうよく', freq: 1400, level: 2 },
  { en: 'kindness', ja: '親切', kana: 'しんせつ', freq: 1090, level: 2, theme: '日常' },
  { en: 'courage', ja: '勇気', kana: 'ゆうき', freq: 1100, level: 2 },
  { en: 'worry', ja: '心配', kana: 'しんぱい', freq: 1020, level: 2, theme: '日常' },
  { en: 'anxiety', ja: '不安', kana: 'ふあん', freq: 1150, level: 2 },
  { en: 'stress', ja: '緊張', kana: 'きんちょう', freq: 1130, level: 2 },
  { en: 'comfort', ja: '快適さ', kana: 'かいてきさ', freq: 1260, level: 2 },
  { en: 'pleasure', ja: '楽しみ', kana: 'たのしみ', freq: 1110, level: 2 },
  { en: 'sorrow', ja: '悲しみ', kana: 'かなしみ', freq: 1240, level: 2 },
  { en: 'grief', ja: '悲嘆', kana: 'ひたん', freq: 1440, level: 2 },
  { en: 'faith', ja: '信仰', kana: 'しんこう', freq: 1190, level: 2 },
  { en: 'respect', ja: '尊敬', kana: 'そんけい', freq: 1070, level: 2 },
  { en: 'honor', ja: '名誉', kana: 'めいよ', freq: 1200, level: 2 },
  { en: 'fame', ja: '名声', kana: 'めいせい', freq: 1320, level: 2 },
  { en: 'reputation', ja: '評判', kana: 'ひょうばん', freq: 1210, level: 2, theme: 'ビジネス' },
  // 時・行事（L1/L2）
  { en: 'dawn', ja: '夜明け', kana: 'よあけ', freq: 1080, level: 2 },
  { en: 'dusk', ja: '夕暮れ', kana: 'ゆうぐれ', freq: 1380, level: 2 },
  { en: 'midnight', ja: '真夜中', kana: 'まよなか', freq: 1120, level: 2, theme: '日常' },
  { en: 'era', ja: '時代', kana: 'じだい', freq: 1040, level: 2 },
  { en: 'decade', ja: '十年', kana: 'じゅうねん', freq: 1180, level: 2 },
  { en: 'appointment', ja: '予約', kana: 'よやく', freq: 1060, level: 2, theme: '旅行' },
  { en: 'anniversary', ja: '記念日', kana: 'きねんび', freq: 1200, level: 2, theme: '日常' },
  { en: 'festival', ja: '祭り', kana: 'まつり', freq: 900, level: 1, theme: '旅行' },
  { en: 'ceremony', ja: '式典', kana: 'しきてん', freq: 1230, level: 2 },
  { en: 'event', ja: '行事', kana: 'ぎょうじ', freq: 1010, level: 2 },
  { en: 'occasion', ja: '場面', kana: 'ばめん', freq: 1170, level: 2 },
  // 自然・気象（L1/L2）
  { en: 'climate', ja: '風土', kana: 'ふうど', freq: 1190, level: 2 },
  { en: 'temperature', ja: '気温', kana: 'きおん', freq: 1050, level: 2 },
  { en: 'flood', ja: '洪水', kana: 'こうずい', freq: 1160, level: 2 },
  { en: 'drought', ja: '干ばつ', kana: 'かんばつ', freq: 1420, level: 2 },
  { en: 'earthquake', ja: '地震', kana: 'じしん', freq: 1040, level: 2 },
  { en: 'volcano', ja: '火山', kana: 'かざん', freq: 1240, level: 2, theme: '旅行' },
  { en: 'fog', ja: '霧', kana: 'きり', freq: 1130, level: 2 },
  { en: 'rainbow', ja: '虹', kana: 'にじ', freq: 940, level: 1, theme: '旅行' },
  { en: 'lightning', ja: '稲妻', kana: 'いなずま', freq: 1220, level: 2 },
  { en: 'thunder', ja: '雷', kana: 'かみなり', freq: 980, level: 1 },
  { en: 'shadow', ja: '影', kana: 'かげ', freq: 920, level: 1 },
  { en: 'horizon', ja: '地平線', kana: 'ちへいせん', freq: 1300, level: 2, theme: '旅行' },
  { en: 'cliff', ja: '崖', kana: 'がけ', freq: 1280, level: 2, theme: '旅行' },
  { en: 'peak', ja: '頂', kana: 'いただき', freq: 1180, level: 2, theme: '旅行' },
  { en: 'slope', ja: '坂', kana: 'さか', freq: 1100, level: 2 },
]
