// 単語問題データ（難易度 level 1-4 × テーマ theme）。
// 出題は「和訳を見て英単語を入力」。en は小文字の英単語1語。
export const WORD_LEVELS = [
  { level: 1, label: '基礎', cefr: 'A1' },
  { level: 2, label: '初級', cefr: 'A2' },
  { level: 3, label: '中級', cefr: 'B1' },
  { level: 4, label: '上級', cefr: 'B2–C1' },
]

export const WORD_THEMES = ['日常', '旅行', 'ビジネス']

export const WORDS = [
  // ---- L1 基礎（A1） ----
  { en: 'water', ja: '水', level: 1, theme: '日常' },
  { en: 'food', ja: '食べ物', level: 1, theme: '日常' },
  { en: 'friend', ja: '友達', level: 1, theme: '日常' },
  { en: 'house', ja: '家', level: 1, theme: '日常' },
  { en: 'book', ja: '本', level: 1, theme: '日常' },
  { en: 'dog', ja: '犬', level: 1, theme: '日常' },
  { en: 'cat', ja: '猫', level: 1, theme: '日常' },
  { en: 'eat', ja: '食べる', level: 1, theme: '日常' },
  { en: 'run', ja: '走る', level: 1, theme: '日常' },
  { en: 'happy', ja: '幸せな', level: 1, theme: '日常' },
  { en: 'school', ja: '学校', level: 1, theme: '日常' },
  { en: 'family', ja: '家族', level: 1, theme: '日常' },
  { en: 'bag', ja: 'かばん', level: 1, theme: '旅行' },
  { en: 'map', ja: '地図', level: 1, theme: '旅行' },
  { en: 'hotel', ja: 'ホテル', level: 1, theme: '旅行' },
  { en: 'train', ja: '電車', level: 1, theme: '旅行' },
  { en: 'car', ja: '車', level: 1, theme: '旅行' },
  { en: 'sea', ja: '海', level: 1, theme: '旅行' },
  { en: 'road', ja: '道', level: 1, theme: '旅行' },
  { en: 'trip', ja: '旅行', level: 1, theme: '旅行' },
  { en: 'fly', ja: '飛ぶ', level: 1, theme: '旅行' },
  { en: 'work', ja: '仕事', level: 1, theme: 'ビジネス' },
  { en: 'time', ja: '時間', level: 1, theme: 'ビジネス' },
  { en: 'money', ja: 'お金', level: 1, theme: 'ビジネス' },
  { en: 'name', ja: '名前', level: 1, theme: 'ビジネス' },
  { en: 'phone', ja: '電話', level: 1, theme: 'ビジネス' },
  { en: 'help', ja: '助ける', level: 1, theme: 'ビジネス' },
  { en: 'write', ja: '書く', level: 1, theme: 'ビジネス' },
  { en: 'call', ja: '電話する', level: 1, theme: 'ビジネス' },
  { en: 'busy', ja: '忙しい', level: 1, theme: 'ビジネス' },

  // ---- L2 初級（A2） ----
  { en: 'kitchen', ja: '台所', level: 2, theme: '日常' },
  { en: 'weather', ja: '天気', level: 2, theme: '日常' },
  { en: 'kind', ja: '親切な', level: 2, theme: '日常' },
  { en: 'breakfast', ja: '朝食', level: 2, theme: '日常' },
  { en: 'garden', ja: '庭', level: 2, theme: '日常' },
  { en: 'clean', ja: '掃除する', level: 2, theme: '日常' },
  { en: 'decide', ja: '決める', level: 2, theme: '日常' },
  { en: 'weekend', ja: '週末', level: 2, theme: '日常' },
  { en: 'healthy', ja: '健康な', level: 2, theme: '日常' },
  { en: 'expensive', ja: '高価な', level: 2, theme: '日常' },
  { en: 'borrow', ja: '借りる', level: 2, theme: '日常' },
  { en: 'airport', ja: '空港', level: 2, theme: '旅行' },
  { en: 'ticket', ja: '切符', level: 2, theme: '旅行' },
  { en: 'reserve', ja: '予約する', level: 2, theme: '旅行' },
  { en: 'station', ja: '駅', level: 2, theme: '旅行' },
  { en: 'passport', ja: 'パスポート', level: 2, theme: '旅行' },
  { en: 'luggage', ja: '荷物', level: 2, theme: '旅行' },
  { en: 'foreign', ja: '外国の', level: 2, theme: '旅行' },
  { en: 'arrive', ja: '到着する', level: 2, theme: '旅行' },
  { en: 'suitcase', ja: 'スーツケース', level: 2, theme: '旅行' },
  { en: 'meeting', ja: '会議', level: 2, theme: 'ビジネス' },
  { en: 'report', ja: '報告', level: 2, theme: 'ビジネス' },
  { en: 'email', ja: 'メール', level: 2, theme: 'ビジネス' },
  { en: 'office', ja: '会社', level: 2, theme: 'ビジネス' },
  { en: 'salary', ja: '給料', level: 2, theme: 'ビジネス' },
  { en: 'manager', ja: '部長', level: 2, theme: 'ビジネス' },
  { en: 'customer', ja: '顧客', level: 2, theme: 'ビジネス' },
  { en: 'prepare', ja: '準備する', level: 2, theme: 'ビジネス' },
  { en: 'attend', ja: '出席する', level: 2, theme: 'ビジネス' },
  { en: 'deliver', ja: '届ける', level: 2, theme: 'ビジネス' },

  // ---- L3 中級（B1） ----
  { en: 'neighbor', ja: '近所の人', level: 3, theme: '日常' },
  { en: 'improve', ja: '改善する', level: 3, theme: '日常' },
  { en: 'recently', ja: '最近', level: 3, theme: '日常' },
  { en: 'environment', ja: '環境', level: 3, theme: '日常' },
  { en: 'opportunity', ja: '機会', level: 3, theme: '日常' },
  { en: 'increase', ja: '増やす', level: 3, theme: '日常' },
  { en: 'available', ja: '利用できる', level: 3, theme: '日常' },
  { en: 'situation', ja: '状況', level: 3, theme: '日常' },
  { en: 'complain', ja: '不平を言う', level: 3, theme: '日常' },
  { en: 'appreciate', ja: '感謝する', level: 3, theme: '日常' },
  { en: 'journey', ja: '旅', level: 3, theme: '旅行' },
  { en: 'currency', ja: '通貨', level: 3, theme: '旅行' },
  { en: 'delay', ja: '遅れ', level: 3, theme: '旅行' },
  { en: 'departure', ja: '出発', level: 3, theme: '旅行' },
  { en: 'accommodation', ja: '宿泊施設', level: 3, theme: '旅行' },
  { en: 'sightseeing', ja: '観光', level: 3, theme: '旅行' },
  { en: 'customs', ja: '税関', level: 3, theme: '旅行' },
  { en: 'destination', ja: '目的地', level: 3, theme: '旅行' },
  { en: 'souvenir', ja: '土産', level: 3, theme: '旅行' },
  { en: 'schedule', ja: '予定', level: 3, theme: 'ビジネス' },
  { en: 'propose', ja: '提案する', level: 3, theme: 'ビジネス' },
  { en: 'client', ja: '取引先', level: 3, theme: 'ビジネス' },
  { en: 'deadline', ja: '締め切り', level: 3, theme: 'ビジネス' },
  { en: 'negotiate', ja: '交渉する', level: 3, theme: 'ビジネス' },
  { en: 'budget', ja: '予算', level: 3, theme: 'ビジネス' },
  { en: 'contract', ja: '契約', level: 3, theme: 'ビジネス' },
  { en: 'colleague', ja: '同僚', level: 3, theme: 'ビジネス' },
  { en: 'expand', ja: '拡大する', level: 3, theme: 'ビジネス' },
  { en: 'profit', ja: '利益', level: 3, theme: 'ビジネス' },
  { en: 'recommend', ja: '勧める', level: 3, theme: 'ビジネス' },

  // ---- L4 上級（B2–C1） ----
  { en: 'nevertheless', ja: 'それにもかかわらず', level: 4, theme: '日常' },
  { en: 'accomplish', ja: '成し遂げる', level: 4, theme: '日常' },
  { en: 'consequence', ja: '結果', level: 4, theme: '日常' },
  { en: 'inevitable', ja: '避けられない', level: 4, theme: '日常' },
  { en: 'sophisticated', ja: '洗練された', level: 4, theme: '日常' },
  { en: 'ambiguous', ja: '曖昧な', level: 4, theme: '日常' },
  { en: 'perseverance', ja: '忍耐', level: 4, theme: '日常' },
  { en: 'deteriorate', ja: '悪化する', level: 4, theme: '日常' },
  { en: 'itinerary', ja: '旅程', level: 4, theme: '旅行' },
  { en: 'turbulence', ja: '乱気流', level: 4, theme: '旅行' },
  { en: 'excursion', ja: '小旅行', level: 4, theme: '旅行' },
  { en: 'hospitality', ja: 'もてなし', level: 4, theme: '旅行' },
  { en: 'expedition', ja: '遠征', level: 4, theme: '旅行' },
  { en: 'picturesque', ja: '絵のように美しい', level: 4, theme: '旅行' },
  { en: 'invoice', ja: '請求書', level: 4, theme: 'ビジネス' },
  { en: 'acquisition', ja: '買収', level: 4, theme: 'ビジネス' },
  { en: 'comprehensive', ja: '包括的な', level: 4, theme: 'ビジネス' },
  { en: 'entrepreneur', ja: '起業家', level: 4, theme: 'ビジネス' },
  { en: 'stakeholder', ja: '利害関係者', level: 4, theme: 'ビジネス' },
  { en: 'simultaneously', ja: '同時に', level: 4, theme: 'ビジネス' },
  { en: 'feasibility', ja: '実現可能性', level: 4, theme: 'ビジネス' },
  { en: 'procurement', ja: '調達', level: 4, theme: 'ビジネス' },
  { en: 'consolidate', ja: '統合する', level: 4, theme: 'ビジネス' },
  { en: 'leverage', ja: '活用する', level: 4, theme: 'ビジネス' },
  { en: 'contingency', ja: '不測の事態', level: 4, theme: 'ビジネス' },
  { en: 'delegate', ja: '委任する', level: 4, theme: 'ビジネス' },
  { en: 'streamline', ja: '効率化する', level: 4, theme: 'ビジネス' },
  { en: 'prospective', ja: '見込みの', level: 4, theme: 'ビジネス' },
]
