// 英文と和文(表示用の漢字かな + 入力判定用のかな読み + 翻訳モード用の単語分割)のセット。
// rank: 1-3=日常会話 / 4-6=ビジネス会話。場面と丁寧さが上がるほど難度も上がる。
// kana の文末 。 はピリオド(.)として打つ。長音「ー」は読みに含めない。
// jaWords: 翻訳モードの単語チップ用。助詞・活用語尾まで細かく分割。連結すると ja(句点を除く)になる。

// ランクの定義(UI表示用)
export const RANKS = [
  { rank: 1, label: 'あいさつ・自己紹介', course: '日常会話', register: 'カジュアル' },
  { rank: 2, label: '日常生活', course: '日常会話', register: 'カジュアル' },
  { rank: 3, label: '旅行・外出', course: '日常会話', register: '丁寧' },
  { rank: 4, label: 'オフィスの基本', course: 'ビジネス会話', register: '丁寧' },
  { rank: 5, label: '電話・連絡', course: 'ビジネス会話', register: 'フォーマル' },
  { rank: 6, label: '会議・交渉', course: 'ビジネス会話', register: 'フォーマル' },
]

export const SENTENCES = [
  // ---- R1 あいさつ・自己紹介 / R2 日常生活 / R3 旅行・外出 ----
  { rank: 1, en: 'I go to school every day.', ja: '私は毎日学校へ行きます。', kana: 'わたしはまいにちがっこうへいきます。', jaWords: ['私', 'は', '毎日', '学校', 'へ', '行き', 'ます'] },
  { rank: 2, en: 'The weather is nice today.', ja: '今日は天気が良いです。', kana: 'きょうはてんきがよいです。', jaWords: ['今日', 'は', '天気', 'が', '良い', 'です'] },
  { rank: 1, en: 'I like to read books.', ja: '私は本を読むのが好きです。', kana: 'わたしはほんをよむのがすきです。', jaWords: ['私', 'は', '本', 'を', '読む', 'の', 'が', '好き', 'です'] },
  { rank: 2, en: 'She plays the piano well.', ja: '彼女はピアノを上手に弾きます。', kana: 'かのじょはぴあのをじょうずにひきます。', jaWords: ['彼女', 'は', 'ピアノ', 'を', '上手', 'に', '弾き', 'ます'] },
  { rank: 2, en: 'We had lunch together.', ja: '私たちは一緒に昼食を食べました。', kana: 'わたしたちはいっしょにちゅうしょくをたべました。', jaWords: ['私たち', 'は', '一緒', 'に', '昼食', 'を', '食べ', 'ました'] },
  { rank: 1, en: 'My brother lives in Tokyo.', ja: '私の兄は東京に住んでいます。', kana: 'わたしのあにはとうきょうにすんでいます。', jaWords: ['私', 'の', '兄', 'は', '東京', 'に', '住んで', 'います'] },
  { rank: 2, en: 'Please open the window.', ja: '窓を開けてください。', kana: 'まどをあけてください。', jaWords: ['窓', 'を', '開けて', 'ください'] },
  { rank: 2, en: 'This restaurant is very good.', ja: 'このレストランはとても良いです。', kana: 'このれすとらんはとてもよいです。', jaWords: ['この', 'レストラン', 'は', 'とても', '良い', 'です'] },
  { rank: 2, en: 'He runs in the park.', ja: '彼は公園で走ります。', kana: 'かれはこうえんではしります。', jaWords: ['彼', 'は', '公園', 'で', '走り', 'ます'] },
  { rank: 3, en: 'I want to travel abroad.', ja: '私は海外へ旅行したいです。', kana: 'わたしはかいがいへりょこうしたいです。', jaWords: ['私', 'は', '海外', 'へ', '旅行', 'したい', 'です'] },
  { rank: 3, en: 'The train arrives at nine.', ja: '電車は九時に着きます。', kana: 'でんしゃはくじにつきます。', jaWords: ['電車', 'は', '九時', 'に', '着き', 'ます'] },
  { rank: 1, en: 'Thank you for your help.', ja: '手伝ってくれてありがとう。', kana: 'てつだってくれてありがとう。', jaWords: ['手伝って', 'くれて', 'ありがとう'] },
  { rank: 2, en: 'It is cold this morning.', ja: '今朝は寒いです。', kana: 'けさはさむいです。', jaWords: ['今朝', 'は', '寒い', 'です'] },
  { rank: 1, en: 'Let us study Japanese.', ja: '日本語を勉強しましょう。', kana: 'にほんごをべんきょうしましょう。', jaWords: ['日本語', 'を', '勉強', 'しましょう'] },
  { rank: 2, en: 'The cat is sleeping now.', ja: '猫は今眠っています。', kana: 'ねこはいまねむっています。', jaWords: ['猫', 'は', '今', '眠って', 'います'] },
  { rank: 2, en: 'I will call you tomorrow.', ja: '明日電話します。', kana: 'あしたでんわします。', jaWords: ['明日', '電話', 'します'] },
  { rank: 2, en: 'What time is it now?', ja: '今何時ですか？', kana: 'いまなんじですか？', jaWords: ['今', '何時', 'です', 'か'] },
  { rank: 2, en: 'I am very hungry.', ja: 'とてもお腹が空きました。', kana: 'とてもおなかがすきました。', jaWords: ['とても', 'お腹', 'が', '空き', 'ました'] },
  { rank: 2, en: 'Let us eat dinner.', ja: '晩ご飯を食べましょう。', kana: 'ばんごはんをたべましょう。', jaWords: ['晩ご飯', 'を', '食べ', 'ましょう'] },
  { rank: 2, en: 'This tea is hot.', ja: 'このお茶は熱いです。', kana: 'このおちゃはあついです。', jaWords: ['この', 'お茶', 'は', '熱い', 'です'] },
  { rank: 1, en: 'I get up at six.', ja: '私は六時に起きます。', kana: 'わたしはろくじにおきます。', jaWords: ['私', 'は', '六時', 'に', '起き', 'ます'] },
  { rank: 1, en: 'She is my friend.', ja: '彼女は私の友達です。', kana: 'かのじょはわたしのともだちです。', jaWords: ['彼女', 'は', '私', 'の', '友達', 'です'] },
  { rank: 3, en: 'Where is the station?', ja: '駅はどこですか？', kana: 'えきはどこですか？', jaWords: ['駅', 'は', 'どこ', 'です', 'か'] },
  { rank: 1, en: 'I do not understand well.', ja: 'よく分かりません。', kana: 'よくわかりません。', jaWords: ['よく', '分かり', 'ません'] },
  { rank: 1, en: 'Please speak slowly.', ja: 'ゆっくり話してください。', kana: 'ゆっくりはなしてください。', jaWords: ['ゆっくり', '話して', 'ください'] },
  { rank: 2, en: 'It is raining outside.', ja: '外は雨が降っています。', kana: 'そとはあめがふっています。', jaWords: ['外', 'は', '雨', 'が', '降って', 'います'] },
  { rank: 1, en: 'I am a student.', ja: '私は学生です。', kana: 'わたしはがくせいです。', jaWords: ['私', 'は', '学生', 'です'] },
  { rank: 1, en: 'My birthday is in May.', ja: '私の誕生日は五月です。', kana: 'わたしのたんじょうびはごがつです。', jaWords: ['私', 'の', '誕生日', 'は', '五月', 'です'] },
  { rank: 2, en: 'Let us go shopping.', ja: '買い物に行きましょう。', kana: 'かいものにいきましょう。', jaWords: ['買い物', 'に', '行き', 'ましょう'] },
  { rank: 2, en: 'This bag is too heavy.', ja: 'この鞄は重すぎます。', kana: 'このかばんはおもすぎます。', jaWords: ['この', '鞄', 'は', '重', 'すぎ', 'ます'] },
  { rank: 2, en: 'I want to drink water.', ja: '水が飲みたいです。', kana: 'みずがのみたいです。', jaWords: ['水', 'が', '飲み', 'たい', 'です'] },
  { rank: 2, en: 'The movie was fun.', ja: '映画は楽しかったです。', kana: 'えいがはたのしかったです。', jaWords: ['映画', 'は', '楽しかった', 'です'] },
  { rank: 2, en: 'He is sleeping now.', ja: '彼は今寝ています。', kana: 'かれはいまねています。', jaWords: ['彼', 'は', '今', '寝て', 'います'] },
  { rank: 2, en: 'I will study tonight.', ja: '今夜勉強します。', kana: 'こんやべんきょうします。', jaWords: ['今夜', '勉強', 'します'] },
  { rank: 2, en: 'Are you free tomorrow?', ja: '明日は暇ですか？', kana: 'あしたはひまですか？', jaWords: ['明日', 'は', '暇', 'です', 'か'] },
  { rank: 1, en: 'I like Japanese food.', ja: '私は和食が好きです。', kana: 'わたしはわしょくがすきです。', jaWords: ['私', 'は', '和食', 'が', '好き', 'です'] },
  { rank: 2, en: 'Please wait a moment.', ja: '少し待ってください。', kana: 'すこしまってください。', jaWords: ['少し', '待って', 'ください'] },
  { rank: 2, en: 'My room is very small.', ja: '私の部屋はとても狭いです。', kana: 'わたしのへやはとてもせまいです。', jaWords: ['私', 'の', '部屋', 'は', 'とても', '狭い', 'です'] },
  { rank: 2, en: 'I walk to the office.', ja: '会社まで歩きます。', kana: 'かいしゃまであるきます。', jaWords: ['会社', 'まで', '歩き', 'ます'] },
  { rank: 2, en: 'The food was delicious.', ja: '料理は美味しかったです。', kana: 'りょうりはおいしかったです。', jaWords: ['料理', 'は', '美味しかった', 'です'] },
  { rank: 2, en: 'Can you help me?', ja: '手伝ってくれますか？', kana: 'てつだってくれますか？', jaWords: ['手伝って', 'くれ', 'ます', 'か'] },
  { rank: 3, en: 'I am looking for a hotel.', ja: 'ホテルを探しています。', kana: 'ほてるをさがしています。', jaWords: ['ホテル', 'を', '探して', 'います'] },
  { rank: 3, en: 'Turn right at the corner.', ja: '角を右に曲がってください。', kana: 'かどをみぎにまがってください。', jaWords: ['角', 'を', '右', 'に', '曲がって', 'ください'] },
  { rank: 3, en: 'How much is this?', ja: 'これはいくらですか？', kana: 'これはいくらですか？', jaWords: ['これ', 'は', 'いくら', 'です', 'か'] },
  { rank: 3, en: 'I forgot my umbrella.', ja: '傘を忘れました。', kana: 'かさをわすれました。', jaWords: ['傘', 'を', '忘れ', 'ました'] },
  { rank: 2, en: 'Let us take a break.', ja: '少し休みましょう。', kana: 'すこしやすみましょう。', jaWords: ['少し', '休み', 'ましょう'] },
  { rank: 2, en: 'The sky is very blue.', ja: '空がとても青いです。', kana: 'そらがとてもあおいです。', jaWords: ['空', 'が', 'とても', '青い', 'です'] },
  { rank: 1, en: 'I want to learn English.', ja: '英語を勉強したいです。', kana: 'えいごをべんきょうしたいです。', jaWords: ['英語', 'を', '勉強', 'したい', 'です'] },
  { rank: 1, en: 'My father is a doctor.', ja: '父は医者です。', kana: 'ちちはいしゃです。', jaWords: ['父', 'は', '医者', 'です'] },
  { rank: 2, en: 'We watched a baseball game.', ja: '野球の試合を見ました。', kana: 'やきゅうのしあいをみました。', jaWords: ['野球', 'の', '試合', 'を', '見', 'ました'] },
  { rank: 2, en: 'Please close the door.', ja: 'ドアを閉めてください。', kana: 'どあをしめてください。', jaWords: ['ドア', 'を', '閉めて', 'ください'] },
  { rank: 2, en: 'I am a little tired.', ja: '少し疲れました。', kana: 'すこしつかれました。', jaWords: ['少し', '疲れ', 'ました'] },
  { rank: 1, en: 'What is your name?', ja: 'お名前は何ですか？', kana: 'おなまえはなんですか？', jaWords: ['お名前', 'は', '何', 'です', 'か'] },
  { rank: 1, en: 'I live near the park.', ja: '私は公園の近くに住んでいます。', kana: 'わたしはこうえんのちかくにすんでいます。', jaWords: ['私', 'は', '公園', 'の', '近く', 'に', '住んで', 'います'] },
  { rank: 2, en: 'The test was difficult.', ja: 'テストは難しかったです。', kana: 'てすとはむずかしかったです。', jaWords: ['テスト', 'は', '難しかった', 'です'] },
  { rank: 1, en: 'See you again tomorrow.', ja: 'また明日会いましょう。', kana: 'またあしたあいましょう。', jaWords: ['また', '明日', '会い', 'ましょう'] },

  // ---- R3 旅行・外出(追加) ----
  { rank: 3, en: 'Where is the exit?', ja: '出口はどこですか？', kana: 'でぐちはどこですか？', jaWords: ['出口', 'は', 'どこ', 'です', 'か'] },
  { rank: 3, en: 'Could you take a photo?', ja: '写真を撮ってもらえますか？', kana: 'しゃしんをとってもらえますか？', jaWords: ['写真', 'を', '撮って', 'もらえ', 'ます', 'か'] },
  { rank: 3, en: 'I missed the last train.', ja: '終電を逃しました。', kana: 'しゅうでんをのがしました。', jaWords: ['終電', 'を', '逃し', 'ました'] },
  { rank: 3, en: 'Is there a bank near here?', ja: 'この近くに銀行はありますか？', kana: 'このちかくにぎんこうはありますか？', jaWords: ['この', '近く', 'に', '銀行', 'は', 'あり', 'ます', 'か'] },
  { rank: 3, en: 'How do I get to the airport?', ja: '空港へはどう行きますか？', kana: 'くうこうへはどういきますか？', jaWords: ['空港', 'へ', 'は', 'どう', '行き', 'ます', 'か'] },
  { rank: 3, en: 'I would like to reserve a room.', ja: '部屋を予約したいです。', kana: 'へやをよやくしたいです。', jaWords: ['部屋', 'を', '予約', 'したい', 'です'] },

  // ---- R4 オフィスの基本 ----
  { rank: 4, en: 'I will send the documents tomorrow.', ja: '明日資料を送ります。', kana: 'あしたしりょうをおくります。', jaWords: ['明日', '資料', 'を', '送り', 'ます'] },
  { rank: 4, en: 'Could you check this report?', ja: 'この報告書を確認してもらえますか？', kana: 'このほうこくしょをかくにんしてもらえますか？', jaWords: ['この', '報告書', 'を', '確認', 'して', 'もらえ', 'ます', 'か'] },
  { rank: 4, en: 'The meeting starts at ten.', ja: '会議は十時に始まります。', kana: 'かいぎはじゅうじにはじまります。', jaWords: ['会議', 'は', '十時', 'に', '始まり', 'ます'] },
  { rank: 4, en: 'I am a little behind schedule.', ja: '少し予定より遅れています。', kana: 'すこしよていよりおくれています。', jaWords: ['少し', '予定', 'より', '遅れて', 'います'] },
  { rank: 4, en: 'Please let me know by Friday.', ja: '金曜日までに教えてください。', kana: 'きんようびまでにおしえてください。', jaWords: ['金曜日', 'まで', 'に', '教えて', 'ください'] },
  { rank: 4, en: 'I have finished the work.', ja: '仕事が終わりました。', kana: 'しごとがおわりました。', jaWords: ['仕事', 'が', '終わり', 'ました'] },
  { rank: 4, en: 'Could you help me with this task?', ja: 'この作業を手伝ってもらえますか？', kana: 'このさぎょうをてつだってもらえますか？', jaWords: ['この', '作業', 'を', '手伝って', 'もらえ', 'ます', 'か'] },
  { rank: 4, en: 'I will report the results later.', ja: '後で結果を報告します。', kana: 'あとでけっかをほうこくします。', jaWords: ['後で', '結果', 'を', '報告', 'します'] },
  { rank: 4, en: 'I will be out of the office tomorrow.', ja: '明日は外出します。', kana: 'あしたはがいしゅつします。', jaWords: ['明日', 'は', '外出', 'します'] },
  { rank: 4, en: 'Could you send me the file?', ja: '資料を送ってもらえますか？', kana: 'しりょうをおくってもらえますか？', jaWords: ['資料', 'を', '送って', 'もらえ', 'ます', 'か'] },

  // ---- R5 電話・連絡 ----
  { rank: 5, en: 'Thank you for contacting us.', ja: 'ご連絡ありがとうございます。', kana: 'ごれんらくありがとうございます。', jaWords: ['ご連絡', 'ありがとう', 'ございます'] },
  { rank: 5, en: 'I would like to arrange a meeting.', ja: '打ち合わせをお願いしたいです。', kana: 'うちあわせをおねがいしたいです。', jaWords: ['打ち合わせ', 'を', 'お願い', 'し', 'たい', 'です'] },
  { rank: 5, en: 'Could you call me back later?', ja: '後で折り返し電話をもらえますか？', kana: 'あとでおりかえしでんわをもらえますか？', jaWords: ['後で', '折り返し', '電話', 'を', 'もらえ', 'ます', 'か'] },
  { rank: 5, en: 'I am sorry for the late reply.', ja: '返信が遅くなり申し訳ありません。', kana: 'へんしんがおそくなりもうしわけありません。', jaWords: ['返信', 'が', '遅く', 'なり', '申し訳', 'あり', 'ません'] },
  { rank: 5, en: 'Please check the attached document.', ja: '添付の資料をご確認ください。', kana: 'てんぷのしりょうをごかくにんください。', jaWords: ['添付', 'の', '資料', 'を', 'ご確認', 'ください'] },
  { rank: 5, en: 'I will contact you next week.', ja: '来週ご連絡します。', kana: 'らいしゅうごれんらくします。', jaWords: ['来週', 'ご連絡', 'します'] },
  { rank: 5, en: 'Could you tell me your phone number?', ja: '電話番号を教えてもらえますか？', kana: 'でんわばんごうをおしえてもらえますか？', jaWords: ['電話', '番号', 'を', '教えて', 'もらえ', 'ます', 'か'] },
  { rank: 5, en: 'I am calling about the meeting.', ja: '会議の件でお電話しました。', kana: 'かいぎのけんでおでんわしました。', jaWords: ['会議', 'の', '件', 'で', 'お電話', 'し', 'ました'] },
  { rank: 5, en: 'I will call you this afternoon.', ja: '午後にお電話します。', kana: 'ごごにおでんわします。', jaWords: ['午後', 'に', 'お電話', 'します'] },
  { rank: 5, en: 'Please reply by tomorrow.', ja: '明日までに返信してください。', kana: 'あしたまでにへんしんしてください。', jaWords: ['明日', 'まで', 'に', '返信', 'して', 'ください'] },

  // ---- R6 会議・交渉 ----
  { rank: 6, en: 'I would like to propose a new plan.', ja: '新しい計画を提案したいです。', kana: 'あたらしいけいかくをていあんしたいです。', jaWords: ['新しい', '計画', 'を', '提案', 'し', 'たい', 'です'] },
  { rank: 6, en: 'Could you give us a discount?', ja: '値引きしていただけますか？', kana: 'ねびきしていただけますか？', jaWords: ['値引き', 'して', 'いただけ', 'ます', 'か'] },
  { rank: 6, en: 'Let us discuss the details.', ja: '詳細を話し合いましょう。', kana: 'しょうさいをはなしあいましょう。', jaWords: ['詳細', 'を', '話し合い', 'ましょう'] },
  { rank: 6, en: 'I am afraid I disagree.', ja: '申し訳ありませんが反対です。', kana: 'もうしわけありませんがはんたいです。', jaWords: ['申し訳', 'あり', 'ません', 'が', '反対', 'です'] },
  { rank: 6, en: 'We need to reduce the cost.', ja: '費用を抑える必要があります。', kana: 'ひようをおさえるひつようがあります。', jaWords: ['費用', 'を', '抑える', '必要', 'が', 'あり', 'ます'] },
  { rank: 6, en: 'Thank you for your presentation.', ja: 'ご説明ありがとうございました。', kana: 'ごせつめいありがとうございました。', jaWords: ['ご説明', 'ありがとう', 'ございました'] },
  { rank: 6, en: 'Let us decide the schedule first.', ja: 'まず日程を決めましょう。', kana: 'まずにっていをきめましょう。', jaWords: ['まず', '日程', 'を', '決め', 'ましょう'] },
  { rank: 6, en: 'I will consider your proposal.', ja: 'ご提案を検討します。', kana: 'ごていあんをけんとうします。', jaWords: ['ご提案', 'を', '検討', 'します'] },
  { rank: 6, en: 'We agree with your plan.', ja: 'あなたの計画に賛成です。', kana: 'あなたのけいかくにさんせいです。', jaWords: ['あなた', 'の', '計画', 'に', '賛成', 'です'] },
  { rank: 6, en: 'Let us continue this next time.', ja: '続きは次回にしましょう。', kana: 'つづきはじかいにしましょう。', jaWords: ['続き', 'は', '次回', 'に', 'しましょう'] },
]
