// 英文と和文(表示用の漢字かな + 入力判定用のかな読み)のセット。
// パッセージは「英文(英語入力)」→「和文(ローマ字入力)」を交互に連結して作る。
// kana の文末 。 はピリオド(.)として打つ。長音「ー」はハイフン入力になるため読みに含めない。
export const SENTENCES = [
  { en: 'I go to school every day.', ja: '私は毎日学校へ行きます。', kana: 'わたしはまいにちがっこうへいきます。' },
  { en: 'The weather is nice today.', ja: '今日は天気が良いです。', kana: 'きょうはてんきがよいです。' },
  { en: 'I like to read books.', ja: '私は本を読むのが好きです。', kana: 'わたしはほんをよむのがすきです。' },
  { en: 'She plays the piano well.', ja: '彼女はピアノを上手に弾きます。', kana: 'かのじょはぴあのをじょうずにひきます。' },
  { en: 'We had lunch together.', ja: '私たちは一緒に昼食を食べました。', kana: 'わたしたちはいっしょにちゅうしょくをたべました。' },
  { en: 'My brother lives in Tokyo.', ja: '私の兄は東京に住んでいます。', kana: 'わたしのあにはとうきょうにすんでいます。' },
  { en: 'Please open the window.', ja: '窓を開けてください。', kana: 'まどをあけてください。' },
  { en: 'This restaurant is very good.', ja: 'このレストランはとても良いです。', kana: 'このれすとらんはとてもよいです。' },
  { en: 'He runs in the park.', ja: '彼は公園で走ります。', kana: 'かれはこうえんではしります。' },
  { en: 'I want to travel abroad.', ja: '私は海外へ旅行したいです。', kana: 'わたしはかいがいへりょこうしたいです。' },
  { en: 'The train arrives at nine.', ja: '電車は九時に着きます。', kana: 'でんしゃはくじにつきます。' },
  { en: 'Thank you for your help.', ja: '手伝ってくれてありがとう。', kana: 'てつだってくれてありがとう。' },
  { en: 'It is cold this morning.', ja: '今朝は寒いです。', kana: 'けさはさむいです。' },
  { en: 'Let us study Japanese.', ja: '日本語を勉強しましょう。', kana: 'にほんごをべんきょうしましょう。' },
  { en: 'The cat is sleeping now.', ja: '猫は今眠っています。', kana: 'ねこはいまねむっています。' },
  { en: 'I will call you tomorrow.', ja: '明日電話します。', kana: 'あしたでんわします。' },

  { en: 'What time is it now?', ja: '今何時ですか。', kana: 'いまなんじですか。' },
  { en: 'I am very hungry.', ja: 'とてもお腹が空きました。', kana: 'とてもおなかがすきました。' },
  { en: 'Let us eat dinner.', ja: '晩ご飯を食べましょう。', kana: 'ばんごはんをたべましょう。' },
  { en: 'This tea is hot.', ja: 'このお茶は熱いです。', kana: 'このおちゃはあついです。' },
  { en: 'I get up at six.', ja: '私は六時に起きます。', kana: 'わたしはろくじにおきます。' },
  { en: 'She is my friend.', ja: '彼女は私の友達です。', kana: 'かのじょはわたしのともだちです。' },
  { en: 'Where is the station?', ja: '駅はどこですか。', kana: 'えきはどこですか。' },
  { en: 'I do not understand well.', ja: 'よく分かりません。', kana: 'よくわかりません。' },
  { en: 'Please speak slowly.', ja: 'ゆっくり話してください。', kana: 'ゆっくりはなしてください。' },
  { en: 'It is raining outside.', ja: '外は雨が降っています。', kana: 'そとはあめがふっています。' },
  { en: 'I am a student.', ja: '私は学生です。', kana: 'わたしはがくせいです。' },
  { en: 'My birthday is in May.', ja: '私の誕生日は五月です。', kana: 'わたしのたんじょうびはごがつです。' },
  { en: 'Let us go shopping.', ja: '買い物に行きましょう。', kana: 'かいものにいきましょう。' },
  { en: 'This bag is too heavy.', ja: 'この鞄は重すぎます。', kana: 'このかばんはおもすぎます。' },
  { en: 'I want to drink water.', ja: '水が飲みたいです。', kana: 'みずがのみたいです。' },
  { en: 'The movie was fun.', ja: '映画は楽しかったです。', kana: 'えいがはたのしかったです。' },
  { en: 'He is sleeping now.', ja: '彼は今寝ています。', kana: 'かれはいまねています。' },
  { en: 'I will study tonight.', ja: '今夜勉強します。', kana: 'こんやべんきょうします。' },
  { en: 'Are you free tomorrow?', ja: '明日は暇ですか。', kana: 'あしたはひまですか。' },
  { en: 'I like Japanese food.', ja: '私は和食が好きです。', kana: 'わたしはわしょくがすきです。' },
  { en: 'Please wait a moment.', ja: '少し待ってください。', kana: 'すこしまってください。' },
  { en: 'My room is very small.', ja: '私の部屋はとても狭いです。', kana: 'わたしのへやはとてもせまいです。' },
  { en: 'I walk to the office.', ja: '会社まで歩きます。', kana: 'かいしゃまであるきます。' },
  { en: 'The food was delicious.', ja: '料理は美味しかったです。', kana: 'りょうりはおいしかったです。' },
  { en: 'Can you help me?', ja: '手伝ってくれますか。', kana: 'てつだってくれますか。' },
  { en: 'I am looking for a hotel.', ja: 'ホテルを探しています。', kana: 'ほてるをさがしています。' },
  { en: 'Turn right at the corner.', ja: '角を右に曲がってください。', kana: 'かどをみぎにまがってください。' },
  { en: 'How much is this?', ja: 'これはいくらですか。', kana: 'これはいくらですか。' },
  { en: 'I forgot my umbrella.', ja: '傘を忘れました。', kana: 'かさをわすれました。' },
  { en: 'Let us take a break.', ja: '少し休みましょう。', kana: 'すこしやすみましょう。' },
  { en: 'The sky is very blue.', ja: '空がとても青いです。', kana: 'そらがとてもあおいです。' },
  { en: 'I want to learn English.', ja: '英語を勉強したいです。', kana: 'えいごをべんきょうしたいです。' },
  { en: 'My father is a doctor.', ja: '父は医者です。', kana: 'ちちはいしゃです。' },
  { en: 'We watched a baseball game.', ja: '野球の試合を見ました。', kana: 'やきゅうのしあいをみました。' },
  { en: 'Please close the door.', ja: 'ドアを閉めてください。', kana: 'どあをしめてください。' },
  { en: 'I am a little tired.', ja: '少し疲れました。', kana: 'すこしつかれました。' },
  { en: 'What is your name?', ja: 'お名前は何ですか。', kana: 'おなまえはなんですか。' },
  { en: 'I live near the park.', ja: '私は公園の近くに住んでいます。', kana: 'わたしはこうえんのちかくにすんでいます。' },
  { en: 'The test was difficult.', ja: 'テストは難しかったです。', kana: 'てすとはむずかしかったです。' },
  { en: 'See you again tomorrow.', ja: 'また明日会いましょう。', kana: 'またあしたあいましょう。' },
]
