// 英文と和文(表示用の漢字かな + 入力判定用のかな読み + 翻訳モード用の単語分割)のセット。
// kana の文末 。 はピリオド(.)として打つ。長音「ー」は読みに含めない。
// jaWords: 翻訳モードの単語チップ用。連結すると ja(句点を除く)になる。
export const SENTENCES = [
  { en: 'I go to school every day.', ja: '私は毎日学校へ行きます。', kana: 'わたしはまいにちがっこうへいきます。', jaWords: ['私は', '毎日', '学校へ', '行きます'] },
  { en: 'The weather is nice today.', ja: '今日は天気が良いです。', kana: 'きょうはてんきがよいです。', jaWords: ['今日は', '天気が', '良いです'] },
  { en: 'I like to read books.', ja: '私は本を読むのが好きです。', kana: 'わたしはほんをよむのがすきです。', jaWords: ['私は', '本を', '読むのが', '好きです'] },
  { en: 'She plays the piano well.', ja: '彼女はピアノを上手に弾きます。', kana: 'かのじょはぴあのをじょうずにひきます。', jaWords: ['彼女は', 'ピアノを', '上手に', '弾きます'] },
  { en: 'We had lunch together.', ja: '私たちは一緒に昼食を食べました。', kana: 'わたしたちはいっしょにちゅうしょくをたべました。', jaWords: ['私たちは', '一緒に', '昼食を', '食べました'] },
  { en: 'My brother lives in Tokyo.', ja: '私の兄は東京に住んでいます。', kana: 'わたしのあにはとうきょうにすんでいます。', jaWords: ['私の', '兄は', '東京に', '住んでいます'] },
  { en: 'Please open the window.', ja: '窓を開けてください。', kana: 'まどをあけてください。', jaWords: ['窓を', '開けて', 'ください'] },
  { en: 'This restaurant is very good.', ja: 'このレストランはとても良いです。', kana: 'このれすとらんはとてもよいです。', jaWords: ['この', 'レストランは', 'とても', '良いです'] },
  { en: 'He runs in the park.', ja: '彼は公園で走ります。', kana: 'かれはこうえんではしります。', jaWords: ['彼は', '公園で', '走ります'] },
  { en: 'I want to travel abroad.', ja: '私は海外へ旅行したいです。', kana: 'わたしはかいがいへりょこうしたいです。', jaWords: ['私は', '海外へ', '旅行したいです'] },
  { en: 'The train arrives at nine.', ja: '電車は九時に着きます。', kana: 'でんしゃはくじにつきます。', jaWords: ['電車は', '九時に', '着きます'] },
  { en: 'Thank you for your help.', ja: '手伝ってくれてありがとう。', kana: 'てつだってくれてありがとう。', jaWords: ['手伝ってくれて', 'ありがとう'] },
  { en: 'It is cold this morning.', ja: '今朝は寒いです。', kana: 'けさはさむいです。', jaWords: ['今朝は', '寒いです'] },
  { en: 'Let us study Japanese.', ja: '日本語を勉強しましょう。', kana: 'にほんごをべんきょうしましょう。', jaWords: ['日本語を', '勉強しましょう'] },
  { en: 'The cat is sleeping now.', ja: '猫は今眠っています。', kana: 'ねこはいまねむっています。', jaWords: ['猫は', '今', '眠っています'] },
  { en: 'I will call you tomorrow.', ja: '明日電話します。', kana: 'あしたでんわします。', jaWords: ['明日', '電話します'] },

  { en: 'What time is it now?', ja: '今何時ですか。', kana: 'いまなんじですか。', jaWords: ['今', '何時ですか'] },
  { en: 'I am very hungry.', ja: 'とてもお腹が空きました。', kana: 'とてもおなかがすきました。', jaWords: ['とても', 'お腹が', '空きました'] },
  { en: 'Let us eat dinner.', ja: '晩ご飯を食べましょう。', kana: 'ばんごはんをたべましょう。', jaWords: ['晩ご飯を', '食べましょう'] },
  { en: 'This tea is hot.', ja: 'このお茶は熱いです。', kana: 'このおちゃはあついです。', jaWords: ['この', 'お茶は', '熱いです'] },
  { en: 'I get up at six.', ja: '私は六時に起きます。', kana: 'わたしはろくじにおきます。', jaWords: ['私は', '六時に', '起きます'] },
  { en: 'She is my friend.', ja: '彼女は私の友達です。', kana: 'かのじょはわたしのともだちです。', jaWords: ['彼女は', '私の', '友達です'] },
  { en: 'Where is the station?', ja: '駅はどこですか。', kana: 'えきはどこですか。', jaWords: ['駅は', 'どこですか'] },
  { en: 'I do not understand well.', ja: 'よく分かりません。', kana: 'よくわかりません。', jaWords: ['よく', '分かりません'] },
  { en: 'Please speak slowly.', ja: 'ゆっくり話してください。', kana: 'ゆっくりはなしてください。', jaWords: ['ゆっくり', '話して', 'ください'] },
  { en: 'It is raining outside.', ja: '外は雨が降っています。', kana: 'そとはあめがふっています。', jaWords: ['外は', '雨が', '降っています'] },
  { en: 'I am a student.', ja: '私は学生です。', kana: 'わたしはがくせいです。', jaWords: ['私は', '学生です'] },
  { en: 'My birthday is in May.', ja: '私の誕生日は五月です。', kana: 'わたしのたんじょうびはごがつです。', jaWords: ['私の', '誕生日は', '五月です'] },
  { en: 'Let us go shopping.', ja: '買い物に行きましょう。', kana: 'かいものにいきましょう。', jaWords: ['買い物に', '行きましょう'] },
  { en: 'This bag is too heavy.', ja: 'この鞄は重すぎます。', kana: 'このかばんはおもすぎます。', jaWords: ['この', '鞄は', '重すぎます'] },
  { en: 'I want to drink water.', ja: '水が飲みたいです。', kana: 'みずがのみたいです。', jaWords: ['水が', '飲みたいです'] },
  { en: 'The movie was fun.', ja: '映画は楽しかったです。', kana: 'えいがはたのしかったです。', jaWords: ['映画は', '楽しかったです'] },
  { en: 'He is sleeping now.', ja: '彼は今寝ています。', kana: 'かれはいまねています。', jaWords: ['彼は', '今', '寝ています'] },
  { en: 'I will study tonight.', ja: '今夜勉強します。', kana: 'こんやべんきょうします。', jaWords: ['今夜', '勉強します'] },
  { en: 'Are you free tomorrow?', ja: '明日は暇ですか。', kana: 'あしたはひまですか。', jaWords: ['明日は', '暇ですか'] },
  { en: 'I like Japanese food.', ja: '私は和食が好きです。', kana: 'わたしはわしょくがすきです。', jaWords: ['私は', '和食が', '好きです'] },
  { en: 'Please wait a moment.', ja: '少し待ってください。', kana: 'すこしまってください。', jaWords: ['少し', '待って', 'ください'] },
  { en: 'My room is very small.', ja: '私の部屋はとても狭いです。', kana: 'わたしのへやはとてもせまいです。', jaWords: ['私の', '部屋は', 'とても', '狭いです'] },
  { en: 'I walk to the office.', ja: '会社まで歩きます。', kana: 'かいしゃまであるきます。', jaWords: ['会社まで', '歩きます'] },
  { en: 'The food was delicious.', ja: '料理は美味しかったです。', kana: 'りょうりはおいしかったです。', jaWords: ['料理は', '美味しかったです'] },
  { en: 'Can you help me?', ja: '手伝ってくれますか。', kana: 'てつだってくれますか。', jaWords: ['手伝って', 'くれますか'] },
  { en: 'I am looking for a hotel.', ja: 'ホテルを探しています。', kana: 'ほてるをさがしています。', jaWords: ['ホテルを', '探しています'] },
  { en: 'Turn right at the corner.', ja: '角を右に曲がってください。', kana: 'かどをみぎにまがってください。', jaWords: ['角を', '右に', '曲がって', 'ください'] },
  { en: 'How much is this?', ja: 'これはいくらですか。', kana: 'これはいくらですか。', jaWords: ['これは', 'いくらですか'] },
  { en: 'I forgot my umbrella.', ja: '傘を忘れました。', kana: 'かさをわすれました。', jaWords: ['傘を', '忘れました'] },
  { en: 'Let us take a break.', ja: '少し休みましょう。', kana: 'すこしやすみましょう。', jaWords: ['少し', '休みましょう'] },
  { en: 'The sky is very blue.', ja: '空がとても青いです。', kana: 'そらがとてもあおいです。', jaWords: ['空が', 'とても', '青いです'] },
  { en: 'I want to learn English.', ja: '英語を勉強したいです。', kana: 'えいごをべんきょうしたいです。', jaWords: ['英語を', '勉強したいです'] },
  { en: 'My father is a doctor.', ja: '父は医者です。', kana: 'ちちはいしゃです。', jaWords: ['父は', '医者です'] },
  { en: 'We watched a baseball game.', ja: '野球の試合を見ました。', kana: 'やきゅうのしあいをみました。', jaWords: ['野球の', '試合を', '見ました'] },
  { en: 'Please close the door.', ja: 'ドアを閉めてください。', kana: 'どあをしめてください。', jaWords: ['ドアを', '閉めて', 'ください'] },
  { en: 'I am a little tired.', ja: '少し疲れました。', kana: 'すこしつかれました。', jaWords: ['少し', '疲れました'] },
  { en: 'What is your name?', ja: 'お名前は何ですか。', kana: 'おなまえはなんですか。', jaWords: ['お名前は', '何ですか'] },
  { en: 'I live near the park.', ja: '私は公園の近くに住んでいます。', kana: 'わたしはこうえんのちかくにすんでいます。', jaWords: ['私は', '公園の', '近くに', '住んでいます'] },
  { en: 'The test was difficult.', ja: 'テストは難しかったです。', kana: 'てすとはむずかしかったです。', jaWords: ['テストは', '難しかったです'] },
  { en: 'See you again tomorrow.', ja: 'また明日会いましょう。', kana: 'またあしたあいましょう。', jaWords: ['また', '明日', '会いましょう'] },
]
