// 英単語・和訳・かな読みのセット。
// ゲームでは「英語表示(英語入力)」→「和訳表示(ローマ字入力)」が交互に出る。
// kana はローマ字判定に使うひらがな読み。
export const WORDS = [
  { en: 'apple', ja: 'りんご', kana: 'りんご' },
  { en: 'orange', ja: 'オレンジ', kana: 'おれんじ' },
  { en: 'banana', ja: 'バナナ', kana: 'ばなな' },
  { en: 'water', ja: '水', kana: 'みず' },
  { en: 'fire', ja: '火', kana: 'ひ' },
  { en: 'mountain', ja: '山', kana: 'やま' },
  { en: 'river', ja: '川', kana: 'かわ' },
  { en: 'school', ja: '学校', kana: 'がっこう' },
  { en: 'teacher', ja: '先生', kana: 'せんせい' },
  { en: 'student', ja: '生徒', kana: 'せいと' },
  { en: 'book', ja: '本', kana: 'ほん' },
  { en: 'pencil', ja: '鉛筆', kana: 'えんぴつ' },
  { en: 'window', ja: '窓', kana: 'まど' },
  { en: 'door', ja: 'ドア', kana: 'どあ' },
  { en: 'table', ja: '机', kana: 'つくえ' },
  { en: 'chair', ja: '椅子', kana: 'いす' },
  { en: 'morning', ja: '朝', kana: 'あさ' },
  { en: 'evening', ja: '夕方', kana: 'ゆうがた' },
  { en: 'night', ja: '夜', kana: 'よる' },
  { en: 'friend', ja: '友達', kana: 'ともだち' },
  { en: 'family', ja: '家族', kana: 'かぞく' },
  { en: 'mother', ja: '母', kana: 'はは' },
  { en: 'father', ja: '父', kana: 'ちち' },
  { en: 'dog', ja: '犬', kana: 'いぬ' },
  { en: 'cat', ja: '猫', kana: 'ねこ' },
  { en: 'bird', ja: '鳥', kana: 'とり' },
  { en: 'flower', ja: '花', kana: 'はな' },
  { en: 'tree', ja: '木', kana: 'き' },
  { en: 'color', ja: '色', kana: 'いろ' },
  { en: 'music', ja: '音楽', kana: 'おんがく' },
  { en: 'science', ja: '科学', kana: 'かがく' },
  { en: 'history', ja: '歴史', kana: 'れきし' },
  { en: 'language', ja: '言語', kana: 'げんご' },
  { en: 'country', ja: '国', kana: 'くに' },
  { en: 'city', ja: '都市', kana: 'とし' },
  { en: 'station', ja: '駅', kana: 'えき' },
  { en: 'hospital', ja: '病院', kana: 'びょういん' },
  { en: 'doctor', ja: '医者', kana: 'いしゃ' },
  { en: 'money', ja: 'お金', kana: 'おかね' },
  { en: 'travel', ja: '旅行', kana: 'りょこう' },
  { en: 'summer', ja: '夏', kana: 'なつ' },
  { en: 'winter', ja: '冬', kana: 'ふゆ' },
  { en: 'weather', ja: '天気', kana: 'てんき' },
  { en: 'future', ja: '未来', kana: 'みらい' },
  { en: 'dream', ja: '夢', kana: 'ゆめ' },
  { en: 'happy', ja: '幸せ', kana: 'しあわせ' },
  { en: 'kitchen', ja: '台所', kana: 'だいどころ' },
  { en: 'garden', ja: '庭', kana: 'にわ' },
  { en: 'bridge', ja: '橋', kana: 'はし' },
  { en: 'island', ja: '島', kana: 'しま' },
]
